// Code generated by generate-services. DO NOT EDIT.

package dns

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletednsrecordsfortypeandname

# Delete all DNS records for a given record type and domain

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - resourceId: Resource ID
  - typeParam: Record type
  - recordName: Record name

# Returns the operation result or an error

Example:

	response := dns.Deletednsrecordsfortypeandname(ctx, client, tracer, tenantId, resourceId, typeParam, recordName)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: dns
operationId: deleteDnsRecordsForTypeAndName
*/
func Deletednsrecordsfortypeandname(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, resourceId string, typeParam string, recordName string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteDnsRecordsForTypeAndName", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("resourceId", resourceId), attribute.String("typeParam", typeParam), attribute.String("recordName", recordName)))
	defer span.End()

	path := utils.Path("/v4/dns/organisations/%s/resources/%s/records/type/%s/name/%s", tenantId, resourceId, typeParam, recordName)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
