// Code generated by generate-services. DO NOT EDIT.

package auth

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getgithub GET /v2/github — start GitHub OAuth transaction.

Source: cc-api GithubAPI.java getGithub()
Behavior: Creates a transaction ID in cache, returns it for the OAuth flow.
Issue: #223

Algorithm: Verify OAuth1 auth, create transaction_id in Redis for user; Return
`{ transactionId, redirectUri }` for the subsequent GitHub OAuth flow.
Legacy: cc-api GithubAPI.java:55-57 getGithub() -> OAuth2ClientHelper.java:88-106
Conformity: faithful — `UUID.randomUUID().toString()` keeps its dashes here (unlike the

	OAuth1 verifier, which cc-api strips), and `OAuthTransactionView(transactionId, null)`
	always carries a `redirectUri` key. Refs #2249

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := auth.Getgithub(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: auth
operationId: getGithub
*/
func Getgithub(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "getGithub")
	defer span.End()

	path := utils.Path("/v2/github")

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
