// Code generated by generate-services. DO NOT EDIT.

package auth

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getloginform GET /v2/session/login — login page, and the account-deletion trigger.

Source: cc-api SessionAPI.java:32-46 getLoginForm() → SessionHelper.java:49-84
Source: cc-api UsersHelper.java:127-133 handleKeys() → :454-488 finishDelete()

Returns an HTML login form. In production, cc-api uses FreeMarker templates;
here we serve a minimal HTML form. **Unless a `deletionKey` is present**, in
which case this endpoint is destructive and no credential is required: it is
the target of the account-deletion confirmation mail, and legacy completes
the deletion on this bare GET before any login step.

Query params `from_authorize`, `oauth_token`, `cli_token` are injected into
hidden form fields so the POST preserves the OAuth flow context.
Source: cc-api OAuth1ServerHelper.java:285-291 — redirect to tmpLogin with params
Issue: #220, #2484, #1615, #1595

📥 **Algo Source (Legacy):**
Serve the login form, after first resolving any key on the query string.
  - `handleKeys(crc, secondaryEmailKey, deletionKey)` runs BEFORE any form render
  - on a valid deletionKey: resolve it in the cache, run the finishDelete cascade,
    fire AccountDeletionEvent, answer 200 JSON `Success.ACCOUNT_DELETED` (301) —
    the login form is never rendered
  - on an unknown/expired key: render the form with the `INVALID_USER_DELETION_KEY`
    (7010) error display
  - otherwise: render the login form with the OAuth flow context in hidden fields
  - `login()`/`mfaLogin()` take no deletionKey at all, so no login path can delete

🔧 **Algo Rust (Implementation):**
  - `deletionKey` present → `finish_delete_from_key`, ahead of the dev auto-login hook
  - resolve the key in the `DELETE` cache keyspace → unknown ⇒ 200 form + banner
  - `find_by_id` the user → missing row ⇒ 200 form + USER_NOT_FOUND banner
  - `cascade_delete_user` → Err ⇒ 500 form + banner, key KEPT so the link is retryable
    (deliberate #1595 deviation from legacy's burn-first)
  - Ok ⇒ burn the key, 200 JSON `Message::success(301, …)`; the ACCOUNT_DELETION
    event fires only when the guarded UPDATE actually transitioned the row
  - no `deletionKey` → dev auto-login hook, then render `login_page_html`

Legacy: cc-api SessionAPI.java:32-46 getLoginForm()
Conformity: faithful — minimal HTML replaces cc-api FreeMarker template; the
deletion trigger matches legacy except for the #1595 burn-order deviation

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := auth.Getloginform(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: auth
operationId: getLoginForm
*/
func Getloginform(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "getLoginForm")
	defer span.End()

	path := utils.Path("/v2/session/login")

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
