// Code generated by generate-services. DO NOT EDIT.

package auth

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getsignupform GET /v2/session/signup — ISO signup page.

Source: cc-api SessionsAPI.java getSignupForm → SignupFormHelper.getSignupHtml
Issue: #1049 (was a Console-redirect placeholder; now renders the real form)

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := auth.Getsignupform(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: auth
operationId: getSignupForm
*/
func Getsignupform(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "getSignupForm")
	defer span.End()

	path := utils.Path("/v2/session/signup")

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
