// Code generated by generate-services. DO NOT EDIT.

package auth

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getgithublogin GET /v2/github/login — redirect to GitHub OAuth authorize.

Source: cc-api GithubAPI.java login()
Source: cc-api OAuth2ClientHelper.java:startLogin()
Flow: Load config from conf_oauth_services → redirect to GitHub authorize URL
Issue: #223

Algorithm: Load GitHub config from conf_oauth_services, redirect to GitHub authorize URL
Legacy: cc-api GithubAPI.java login() -> OAuth2ClientHelper.startLogin()
Conformity: faithful — standard OAuth2 redirect to GitHub

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := auth.Getgithublogin(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: auth
operationId: getGithubLogin
*/
func Getgithublogin(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[any] {
	ctx, span := tracer.Start(ctx, "getGithubLogin")
	defer span.End()

	path := utils.Path("/v2/github/login")

	// Make API call
	response := client.Get[any](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
