// Code generated by generate-services. DO NOT EDIT.

package auth

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Mfalogin Conformity: faithful — TOTP window and recovery code logic match cc-api MFAHelper

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := auth.Mfalogin(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: auth
operationId: mfaLogin
*/
func Mfalogin(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "mfaLogin")
	defer span.End()

	path := utils.Path("/v2/session/mfa_login")

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
