// Code generated by generate-services. DO NOT EDIT.

package auth

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Postreqtokenrequestquerystring POST /v2/oauth/request_token_query — OAuth 1.0a: request token via query string.

Source: cc-api OAuthAPI.java:58-82 postReqTokenRequestQueryString()
Issue: #219

Algorithm: Same as request_token but params from query string instead of form body
Legacy: cc-api OAuth1API.java:34 postReqTokenRequestQueryString()
Conformity: faithful — mirrors cc-api query-string variant

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := auth.Postreqtokenrequestquerystring(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: auth
operationId: postReqTokenRequestQueryString
*/
func Postreqtokenrequestquerystring(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "postReqTokenRequestQueryString")
	defer span.End()

	path := utils.Path("/v2/oauth/request_token_query")

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
