// Code generated by generate-services. DO NOT EDIT.

package open_telemetry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
CreateOpentelemetry **Legacy**: ovd OpenTelemetryController.scala:66 createOpenTelemetry()
**Algorithm**:
  - Validate gateway exists, provision via gateway client (stub)
  - Insert OTel + 3 indexes (logs, traces, metrics) in single transaction

**Conformity**: PARTIAL (gateway provisioning stub, DB inserts real)

POST /v4/tenants/{tenant_id}/opentelemetry -- create a new OpenTelemetry instance.

Source: references/legacy/ovd/modules/otel/controller/OpenTelemetryController.scala createOpenTelemetry()
Source: references/legacy/ovd/modules/otel/repository/OpenTelemetryRepository.scala dbInsertOpenTelemetry(), dbInsertOtelIndex()
Behavior: validates gateway exists, provisions via gateway client, creates OTel + 3 indexes

	(logs, traces, metrics) in a single transaction. Returns 201 with the new OpenTelemetryView.
	Currently stubs the gateway provisioning -- inserts DB records directly.

Issue: #645

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenant_id: Tenant ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := open_telemetry.CreateOpentelemetry(ctx, client, tracer, tenant_id, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: open_telemetry
operationId: create_opentelemetry
*/
func CreateOpentelemetry(ctx context.Context, c *client.Client, tracer trace.Tracer, tenant_id string, requestBody *models.WannabeOpenTelemetry) client.Response[models.OpenTelemetryView] {
	ctx, span := tracer.Start(ctx, "create_opentelemetry", trace.WithAttributes(attribute.String("tenant_id", tenant_id)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/opentelemetry", tenant_id)

	// Make API call
	response := client.Post[models.OpenTelemetryView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
