// Code generated by generate-services. DO NOT EDIT.

package open_telemetry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listotelnamespaces GET /v4/otel/organisations/{owner_id}/namespaces — the owner's ACTIVE
namespaces, newest first, read tokens included.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - owner_id: Owner organisation id (orga_<uuid>)

# Returns the operation result or an error

Example:

	response := open_telemetry.Listotelnamespaces(ctx, client, tracer, owner_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: OpenTelemetry
operationId: listOtelNamespaces
*/
func Listotelnamespaces(ctx context.Context, c *client.Client, tracer trace.Tracer, owner_id string) client.Response[[]models.OtelNamespace] {
	ctx, span := tracer.Start(ctx, "listOtelNamespaces", trace.WithAttributes(attribute.String("owner_id", owner_id)))
	defer span.End()

	path := utils.Path("/v4/otel/organisations/%s/namespaces", owner_id)

	// Make API call
	response := client.Get[[]models.OtelNamespace](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
