// Code generated by generate-services. DO NOT EDIT.

package open_telemetry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
ListOpentelemetry **Legacy**: ovd OpenTelemetryController.scala:235 listOpenTelemetry()
**Algorithm**:
  - SELECT all instances for tenant, fetch indexes per instance

**Conformity**: YES

GET /v4/tenants/{tenant_id}/opentelemetry -- list all OpenTelemetry instances for a tenant.

Source: references/legacy/ovd/modules/otel/controller/OpenTelemetryController.scala listOpenTelemetry()
Source: references/legacy/ovd/modules/otel/repository/OpenTelemetryRepository.scala dbListOpenTelemetry()
Behavior: returns all instances for the given tenant with their indexes, 200 OK.

	Scala fetches indexes per instance in parallel (foreachPar).

Issue: #645

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenant_id: Tenant ID

# Returns the operation result or an error

Example:

	response := open_telemetry.ListOpentelemetry(ctx, client, tracer, tenant_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: open_telemetry
operationId: list_opentelemetry
*/
func ListOpentelemetry(ctx context.Context, c *client.Client, tracer trace.Tracer, tenant_id string) client.Response[[]models.OpenTelemetryView] {
	ctx, span := tracer.Start(ctx, "list_opentelemetry", trace.WithAttributes(attribute.String("tenant_id", tenant_id)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/opentelemetry", tenant_id)

	// Make API call
	response := client.Get[[]models.OpenTelemetryView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
