// Code generated by generate-services. DO NOT EDIT.

package open_telemetry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
ListOtelIndexes **Legacy**: ovd OpenTelemetryController.scala:330 listOtelIndexes()
**Algorithm**:
  - SELECT all indexes for the given OTel instance

**Conformity**: YES

GET /v4/tenants/{tenant_id}/opentelemetry/{opentelemetry_id}/indexes -- list all indexes.

Source: references/legacy/ovd/modules/otel/controller/OpenTelemetryController.scala listOtelIndexes()
Source: references/legacy/ovd/modules/otel/repository/OpenTelemetryRepository.scala dbListOtelIndexes()
Behavior: returns all indexes for the given OTel instance, 200 OK
Issue: #645

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenant_id: Tenant ID
  - opentelemetry_id: OpenTelemetry instance ID

# Returns the operation result or an error

Example:

	response := open_telemetry.ListOtelIndexes(ctx, client, tracer, tenant_id, opentelemetry_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: open_telemetry
operationId: list_otel_indexes
*/
func ListOtelIndexes(ctx context.Context, c *client.Client, tracer trace.Tracer, tenant_id string, opentelemetry_id string) client.Response[[]models.OtelIndexView] {
	ctx, span := tracer.Start(ctx, "list_otel_indexes", trace.WithAttributes(attribute.String("tenant_id", tenant_id), attribute.String("opentelemetry_id", opentelemetry_id)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/opentelemetry/%s/indexes", tenant_id, opentelemetry_id)

	// Make API call
	response := client.Get[[]models.OtelIndexView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
