// Code generated by generate-services. DO NOT EDIT.

package open_telemetry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
UpdateOpentelemetry **Legacy**: ovd OpenTelemetryController.scala:284 updateOpenTelemetry()
**Algorithm**:
  - Fetch existing, patch label, UPDATE row, return updated view with indexes

**Conformity**: PARTIAL (only label patchable; Scala also patches gateway_id, statuses, tags)

PATCH /v4/tenants/{tenant_id}/opentelemetry/{opentelemetry_id} -- update an OpenTelemetry instance.

Source: references/legacy/ovd/modules/otel/controller/OpenTelemetryController.scala updateOpenTelemetry()
Source: references/legacy/ovd/modules/otel/repository/OpenTelemetryRepository.scala dbUpdateOpenTelemetry()
Behavior: patches name (label), updates statuses and tags. Returns updated view with indexes.

	Scala updates: label, gateway_id, statuses, tags (via dbUpdateOpenTelemetry).
	Currently only name is patchable (matching OpenTelemetryPatch).

Issue: #645

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenant_id: Tenant ID
  - opentelemetry_id: OpenTelemetry instance ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := open_telemetry.UpdateOpentelemetry(ctx, client, tracer, tenant_id, opentelemetry_id, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: open_telemetry
operationId: update_opentelemetry
*/
func UpdateOpentelemetry(ctx context.Context, c *client.Client, tracer trace.Tracer, tenant_id string, opentelemetry_id string, requestBody *models.OpenTelemetryPatch) client.Response[models.OpenTelemetryView] {
	ctx, span := tracer.Start(ctx, "update_opentelemetry", trace.WithAttributes(attribute.String("tenant_id", tenant_id), attribute.String("opentelemetry_id", opentelemetry_id)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/opentelemetry/%s", tenant_id, opentelemetry_id)

	// Make API call
	response := client.Patch[models.OpenTelemetryView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
