// Code generated by generate-services. DO NOT EDIT.

package misc

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getsummary GET /v2/summary — get a summary of the user's account.

📥 **Algo Source (Legacy):**
Fetch user profile + all orgs with membership role; basic mode returns orgs with app/addon lists; full mode (?full=true) adds OAuth1 consumers per org; user's own apps under "self" pseudo-org.
- Legacy note: cc-api SummaryHelper.java requires access_personal_information permission; basic mode still returns apps (Console3 sidebar needs them).

🔧 **Algo Rust (Implementation):**
- Conformity: faithful
Source: cc-api SummaryAPI.java getSummary() / getSummaryFull()

Basic mode (default): returns user info + org list with counts.
Full mode (?full=true): returns user info + orgs with their full
applications and OAuth1 consumers lists.
Issue: #110

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := misc.Getsummary(ctx, client, tracer, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: misc
operationId: getSummary
*/
func Getsummary(ctx context.Context, c *client.Client, tracer trace.Tracer, opts ...Option) client.Response[models.SummaryView] {
	ctx, span := tracer.Start(ctx, "getSummary")
	defer span.End()

	path := utils.Path("/v2/summary")

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[models.SummaryView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
