// Code generated by generate-services. DO NOT EDIT.

package misc

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetHeptapodPricePrevision GET /v2/saas/heptapod/{id}/heptapod.host/price-prevision — Heptapod price prevision.

📥 **Algo Source (Legacy):**
Return Heptapod pricing info for an organisation. This is called by Console3

	on the addon overview page. Returns empty pricing when Heptapod service not configured.

- Legacy note: cc-api SaaS pricing endpoint for Heptapod (GitLab/Gitea) integration.

🔧 **Algo Rust (Implementation):**
- Conformity: conditional-stub

Source: console3 legacy-client.js:626, orga-saas.sp.js:20
Spec: analysis-output/35-console3-api-consumption.md §Heptapod
Issue: #742

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation or owner ID

# Returns the operation result or an error

Example:

	response := misc.GetHeptapodPricePrevision(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: misc
operationId: get_heptapod_price_prevision
*/
func GetHeptapodPricePrevision(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "get_heptapod_price_prevision", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/saas/heptapod/%s/heptapod.host/price-prevision", id)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
