// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
AddInternalUserEmail PUT /internal/user/{userId}/emails/{email} — add email address for user (internal).

📥 **Algo Source (Legacy):**
Delegates to SelfEmailHelper.addWithUserId(crc, email, body, userId): validate the user +
target email, optionally promote an existing secondary to primary, rate-limit, then cache a
pending confirmation key and publish rh.sendMail(new SecondaryEmailCCMail(...)). The
secondary row is inserted ONLY after the user clicks the confirmation link (finshAdd).
- Legacy note: cc-api InternalUserEmailsAPI.java:85 addInternalEmailAddress() -> SelfEmailHelper.addWithUserId:149-204

🔧 **Algo Rust (Implementation):**
- Conformity: faithful — shares add_secondary_email_with_user_id with PUT /v2/self/emails/{email}.
- Publishes the SecondaryEmailCCMail confirmation email (messaging law #753); no direct INSERT.
Source: cc-api InternalUserEmailsAPI.java:85 addInternalEmailAddress()
Source: cc-api SelfEmailHelper.java:201 rh.sendMail(new SecondaryEmailCCMail(...))
Issue: #709

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - user_id: User ID
  - email: Email address

# Returns the operation result or an error

Example:

	response := internalapi.AddInternalUserEmail(ctx, client, tracer, user_id, email)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: internal
operationId: add_internal_user_email
*/
func AddInternalUserEmail(ctx context.Context, c *client.Client, tracer trace.Tracer, user_id string, email string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "add_internal_user_email", trace.WithAttributes(attribute.String("user_id", user_id), attribute.String("email", email)))
	defer span.End()

	path := utils.Path("/internal/user/%s/emails/%s", user_id, email)

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
