// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
CreateInternalAppliance Legacy: cc-api InternalApplicationsAPI.java:74 createAppliance()
Algorithm: authInternal() + isCCAdmin() + canManageOrganisationsApplications();
parse name from JSON body; insert ApplianceRepository row with id = "app_UUID",
ars_tenant from default zone config, name; publish etilotig ADD_APP command;
register backup entity via backup-manager (non-fatal); return serialized row.
Conformity: YES — implements the full legacy flow.

POST /v2/internal/applications/appliances — create appliance repository.

Source: cc-api InternalApplicationsAPI.java:74 createAppliance()
Schema: V1__Initial_schema.sql:229 — appliance_repositories (id VARCHAR(255) PK, ars_tenant VARCHAR(255), name VARCHAR(255))
Behavior: creates a new appliance repository entry with etilotig ADD_APP notify. Admin-only.
Issue: #159

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := internalapi.CreateInternalAppliance(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: internal
operationId: create_internal_appliance
*/
func CreateInternalAppliance(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "create_internal_appliance")
	defer span.End()

	path := utils.Path("/v2/internal/applications/appliances")

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
