// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetInternalBestAppForURI Legacy: cc-api InternalApplicationsAPI.java:353 getBestAppForUri()
Source: cc-api ApplicationFacade.java:316 getBestAppForUri(uri) — URI host/path split, vhost join ordered by longest path_begin
Source: cc-api ApplicationPersistHelper.java:211 getBestAppForUri(uri, userId) — owner + org-membership check, ApplicationWithOwner envelope
Algorithm: parse uri via axum::http::Uri, percent-decode the path (java.net.URI.getPath() semantics), and reject any host outside the RFC2396 server-authority charset;
a parse failure, missing scheme/host, invalid host, a malformed percent-escape, or a path that fails to decode all warn and fold into 404 APPLICATION_NOT_FOUND, mirroring Option.none() on a legacy IllegalArgumentException / null getHost();
find_best_app_for_uri(host, decoded path) -> None -> 404 APPLICATION_NOT_FOUND (4004); owner_id NULL -> 404 ORGA_NOT_FOUND (6004);
userId (first occurrence of a duplicated query param wins) absent or not a member of the owner org -> 404 ORGA_NOT_FOUND (6004); else 200 {appId, ownerId}.
Conformity: faithful — legacy URI host/path vhost routing + owner-membership check; response is ApplicationWithOwner {appId, ownerId}, not ApplicationView.
Documented divergences (legacy crashes to 500, we 404 instead — never the reverse): protocol-relative "//host/path" (no scheme, so we 404 where legacy would resolve host and match), opaque no-authority URIs like "http:example.com/x" (legacy NPEs on getHost()), and a NULL owner_id (legacy NPEs on the org lookup, we 404 6004).

GET /v2/internal/applications/best-app-for-uri/{uri} — find best app for a URI.

Source: cc-api InternalApplicationsAPI.java:353 getBestAppForUri()
Behavior: returns {appId, ownerId} for the app whose vhost best matches the URI's percent-decoded host+path (deletion_date IS NULL, longest path_begin wins), when userId (first occurrence wins) is a member of the app's owner org.
Issue: #159, #1842

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - uri: URI to match
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := internalapi.GetInternalBestAppForURI(ctx, client, tracer, uri, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: internal
operationId: get_internal_best_app_for_uri
*/
func GetInternalBestAppForURI(ctx context.Context, c *client.Client, tracer trace.Tracer, uri string, opts ...Option) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "get_internal_best_app_for_uri", trace.WithAttributes(attribute.String("uri", uri)))
	defer span.End()

	path := utils.Path("/v2/internal/applications/best-app-for-uri/%s", uri)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
