// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetInternalMigrationMailing POST /internal/migrationMailing — get migration mailing data (stub).

📥 **Algo Source (Legacy):**
Return error (not yet implemented); requires cross-module addon/org/user resolution
- Legacy note: cc-api InternalAPI.java:142 getMigrationData(); takes addon IDs, returns owner+email data

🔧 **Algo Rust (Implementation):**
- Conformity: stub
Source: cc-api InternalAPI.java:142 getMigrationData()
Issue: #709

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := internalapi.GetInternalMigrationMailing(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: internal
operationId: get_internal_migration_mailing
*/
func GetInternalMigrationMailing(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "get_internal_migration_mailing")
	defer span.End()

	path := utils.Path("/internal/migrationMailing")

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
