// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetInternalInvoicesPendingTransfer GET /v2/internal/invoices/pending_transfer — list invoices pending bank transfer.

Source: cc-api InternalInvoiceAPI.java:103 getInvoicesWithPendingTransfer()
Source: billing-api AdminRoutes.scala — getInvoicesPendingTransfer()
Issues: #709, #2016

📥 **Algo Source (Legacy):**
List all invoices with status PENDING and payment_provider = 'transfer'.
- Internal auth required
- Source: billing-api InvoiceDAO.scala

🔧 **Algo Rust (Implementation):**
- Verify internal auth
- ccapi_db::billing::list_invoices_pending_transfer(pool)
- Return serialized invoice rows
Conformity: real -- pure PG query, billing-api absorbed

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := internalapi.GetInternalInvoicesPendingTransfer(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: internal
operationId: get_internal_invoices_pending_transfer
*/
func GetInternalInvoicesPendingTransfer(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "get_internal_invoices_pending_transfer")
	defer span.End()

	path := utils.Path("/v2/internal/invoices/pending_transfer")

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
