// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetInternalAddonsByProvider GET /internal/addons/by-provider/{providerId} — list addons active between dates (internal).

Source: cc-api InternalAddonsAPI.java:146 getAddonsInternal()
Behavior: returns addons from a specific provider that were active between `since` and `until`.

	Active = created before `until` and (not deleted OR deleted after `since`).

Issue: #709

Algorithm: Internal auth, list addons for provider filtered by date range
Legacy: cc-api InternalAddonsAPI.java getAddonsByProvider()
Conformity: faithful -- used by billing/invoicing systems

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - provider_id: Addon provider ID
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := internalapi.GetInternalAddonsByProvider(ctx, client, tracer, provider_id, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: internal
operationId: get_internal_addons_by_provider
*/
func GetInternalAddonsByProvider(ctx context.Context, c *client.Client, tracer trace.Tracer, provider_id string, opts ...Option) client.Response[[]models.AddonView] {
	ctx, span := tracer.Start(ctx, "get_internal_addons_by_provider", trace.WithAttributes(attribute.String("provider_id", provider_id)))
	defer span.End()

	path := utils.Path("/internal/addons/by-provider/%s", provider_id)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.AddonView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
