// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"fmt"
	"net/url"
	"strings"
)

// Option defines a functional option for internalapi operations
type Option func(*Options)

// Options holds query parameters for internalapi operations
type Options struct {
	App         *string `url:"app,omitempty"`
	Appid       *string `url:"appId,omitempty"`
	Biscuit     *string `url:"biscuit,omitempty"`
	Branch      *string `url:"branch,omitempty"`
	Clientip    *string `url:"clientIp,omitempty"`
	Commit      *string `url:"commit,omitempty"`
	Consumer    *string `url:"consumer,omitempty"`
	EmployeeID  *string `url:"employee_id,omitempty"`
	EnvName     *string `url:"env_name,omitempty"`
	Forparam    *string `url:"forParam,omitempty"`
	LifetimeSec *int64  `url:"lifetime_sec,omitempty"`
	Limit       *int64  `url:"limit,omitempty"`
	Message     *string `url:"message,omitempty"`
	Namespace   *string `url:"namespace,omitempty"`
	Offset      *int64  `url:"offset,omitempty"`
	Owner       *string `url:"owner,omitempty"`
	Pin         *int    `url:"pin,omitempty"`
	Secret      *string `url:"secret,omitempty"`
	Since       *string `url:"since,omitempty"`
	Tenant      *string `url:"tenant,omitempty"`
	Token       *string `url:"token,omitempty"`
	Until       *string `url:"until,omitempty"`
	User        *string `url:"user,omitempty"`
	Userid      *string `url:"userId,omitempty"`
}

// WithApp sets the app query parameter
func WithApp(app string) Option {
	return func(o *Options) {
		o.App = &app
	}
}

// WithAppid sets the appId query parameter
func WithAppid(appId string) Option {
	return func(o *Options) {
		o.Appid = &appId
	}
}

// WithBiscuit sets the biscuit query parameter
func WithBiscuit(biscuit string) Option {
	return func(o *Options) {
		o.Biscuit = &biscuit
	}
}

// WithBranch sets the branch query parameter
func WithBranch(branch string) Option {
	return func(o *Options) {
		o.Branch = &branch
	}
}

// WithClientip sets the clientIp query parameter
func WithClientip(clientIp string) Option {
	return func(o *Options) {
		o.Clientip = &clientIp
	}
}

// WithCommit sets the commit query parameter
func WithCommit(commit string) Option {
	return func(o *Options) {
		o.Commit = &commit
	}
}

// WithConsumer sets the consumer query parameter
func WithConsumer(consumer string) Option {
	return func(o *Options) {
		o.Consumer = &consumer
	}
}

// WithEmployeeID sets the employee_id query parameter
func WithEmployeeID(employee_id string) Option {
	return func(o *Options) {
		o.EmployeeID = &employee_id
	}
}

// WithEnvName sets the env_name query parameter
func WithEnvName(env_name string) Option {
	return func(o *Options) {
		o.EnvName = &env_name
	}
}

// WithForparam sets the forParam query parameter
func WithForparam(forParam string) Option {
	return func(o *Options) {
		o.Forparam = &forParam
	}
}

// WithLifetimeSec sets the lifetime_sec query parameter
func WithLifetimeSec(lifetime_sec int64) Option {
	return func(o *Options) {
		o.LifetimeSec = &lifetime_sec
	}
}

// WithLimit sets the limit query parameter
func WithLimit(limit int64) Option {
	return func(o *Options) {
		o.Limit = &limit
	}
}

// WithMessage sets the message query parameter
func WithMessage(message string) Option {
	return func(o *Options) {
		o.Message = &message
	}
}

// WithNamespace sets the namespace query parameter
func WithNamespace(namespace string) Option {
	return func(o *Options) {
		o.Namespace = &namespace
	}
}

// WithOffset sets the offset query parameter
func WithOffset(offset int64) Option {
	return func(o *Options) {
		o.Offset = &offset
	}
}

// WithOwner sets the owner query parameter
func WithOwner(owner string) Option {
	return func(o *Options) {
		o.Owner = &owner
	}
}

// WithPin sets the pin query parameter
func WithPin(pin int) Option {
	return func(o *Options) {
		o.Pin = &pin
	}
}

// WithSecret sets the secret query parameter
func WithSecret(secret string) Option {
	return func(o *Options) {
		o.Secret = &secret
	}
}

// WithSince sets the since query parameter
func WithSince(since string) Option {
	return func(o *Options) {
		o.Since = &since
	}
}

// WithTenant sets the tenant query parameter
func WithTenant(tenant string) Option {
	return func(o *Options) {
		o.Tenant = &tenant
	}
}

// WithToken sets the token query parameter
func WithToken(token string) Option {
	return func(o *Options) {
		o.Token = &token
	}
}

// WithUntil sets the until query parameter
func WithUntil(until string) Option {
	return func(o *Options) {
		o.Until = &until
	}
}

// WithUser sets the user query parameter
func WithUser(user string) Option {
	return func(o *Options) {
		o.User = &user
	}
}

// WithUserid sets the userId query parameter
func WithUserid(userId string) Option {
	return func(o *Options) {
		o.Userid = &userId
	}
}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}

	var params []string
	if options.App != nil {
		params = append(params, fmt.Sprintf("app=%s", url.QueryEscape(*options.App)))
	}
	if options.Appid != nil {
		params = append(params, fmt.Sprintf("appId=%s", url.QueryEscape(*options.Appid)))
	}
	if options.Biscuit != nil {
		params = append(params, fmt.Sprintf("biscuit=%s", url.QueryEscape(*options.Biscuit)))
	}
	if options.Branch != nil {
		params = append(params, fmt.Sprintf("branch=%s", url.QueryEscape(*options.Branch)))
	}
	if options.Clientip != nil {
		params = append(params, fmt.Sprintf("clientIp=%s", url.QueryEscape(*options.Clientip)))
	}
	if options.Commit != nil {
		params = append(params, fmt.Sprintf("commit=%s", url.QueryEscape(*options.Commit)))
	}
	if options.Consumer != nil {
		params = append(params, fmt.Sprintf("consumer=%s", url.QueryEscape(*options.Consumer)))
	}
	if options.EmployeeID != nil {
		params = append(params, fmt.Sprintf("employee_id=%s", url.QueryEscape(*options.EmployeeID)))
	}
	if options.EnvName != nil {
		params = append(params, fmt.Sprintf("env_name=%s", url.QueryEscape(*options.EnvName)))
	}
	if options.Forparam != nil {
		params = append(params, fmt.Sprintf("forParam=%s", url.QueryEscape(*options.Forparam)))
	}
	if options.LifetimeSec != nil {
		params = append(params, fmt.Sprintf("lifetime_sec=%d", *options.LifetimeSec))
	}
	if options.Limit != nil {
		params = append(params, fmt.Sprintf("limit=%d", *options.Limit))
	}
	if options.Message != nil {
		params = append(params, fmt.Sprintf("message=%s", url.QueryEscape(*options.Message)))
	}
	if options.Namespace != nil {
		params = append(params, fmt.Sprintf("namespace=%s", url.QueryEscape(*options.Namespace)))
	}
	if options.Offset != nil {
		params = append(params, fmt.Sprintf("offset=%d", *options.Offset))
	}
	if options.Owner != nil {
		params = append(params, fmt.Sprintf("owner=%s", url.QueryEscape(*options.Owner)))
	}
	if options.Pin != nil {
		params = append(params, fmt.Sprintf("pin=%d", *options.Pin))
	}
	if options.Secret != nil {
		params = append(params, fmt.Sprintf("secret=%s", url.QueryEscape(*options.Secret)))
	}
	if options.Since != nil {
		params = append(params, fmt.Sprintf("since=%s", url.QueryEscape(*options.Since)))
	}
	if options.Tenant != nil {
		params = append(params, fmt.Sprintf("tenant=%s", url.QueryEscape(*options.Tenant)))
	}
	if options.Token != nil {
		params = append(params, fmt.Sprintf("token=%s", url.QueryEscape(*options.Token)))
	}
	if options.Until != nil {
		params = append(params, fmt.Sprintf("until=%s", url.QueryEscape(*options.Until)))
	}
	if options.User != nil {
		params = append(params, fmt.Sprintf("user=%s", url.QueryEscape(*options.User)))
	}
	if options.Userid != nil {
		params = append(params, fmt.Sprintf("userId=%s", url.QueryEscape(*options.Userid)))
	}

	if len(params) == 0 {
		return ""
	}
	return strings.Join(params, "&")
}
