// Code generated by generate-services. DO NOT EDIT.

package internalapi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
UnsetUserAdmin DELETE /v2/internal/users/{userId}/admin — clear the user admin flag.

Source: cc-api InternalUserAPI.java:20 @Path internal/users/{userId}
Source: cc-api InternalUserAPI.java:42-50 unsetAdmin() -> toggleAdmin(false) at :52-65
Schema: V1__Initial_schema.sql:925-940 — table users (admin)
Behavior: sets admin = false on users table. 401 not internal, 403 for any

	internal service other than ccadmin, 404 user not found. Bodyless:
	the Java method signs authInternal(crc, ""), so no payload layer.

Issue: #856, #1956, #2018

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - userId: User ID

# Returns the operation result or an error

Example:

	response := internalapi.UnsetUserAdmin(ctx, client, tracer, userId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: internal
operationId: unset_user_admin
*/
func UnsetUserAdmin(ctx context.Context, c *client.Client, tracer trace.Tracer, userId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "unset_user_admin", trace.WithAttributes(attribute.String("userId", userId)))
	defer span.End()

	path := utils.Path("/v2/internal/users/%s/admin", userId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
