// Code generated by generate-services. DO NOT EDIT.

package ipam

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Assignipaddresstoresource

# Assign IP address to a resource

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - regionId: Region ID
  - resourceId: Resource ID
  - ipVersion: IP Version

# Returns the operation result or an error

Example:

	response := ipam.Assignipaddresstoresource(ctx, client, tracer, tenantId, regionId, resourceId, ipVersion)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ipam
operationId: assignIpAddressToResource
*/
func Assignipaddresstoresource(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, regionId string, resourceId string, ipVersion string) client.Response[models.AssignedIpAddress] {
	ctx, span := tracer.Start(ctx, "assignIpAddressToResource", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("regionId", regionId), attribute.String("resourceId", resourceId), attribute.String("ipVersion", ipVersion)))
	defer span.End()

	path := utils.Path("/v4/ipam/organisations/%s/regions/%s/resources/%s/assign/%s", tenantId, regionId, resourceId, ipVersion)

	// Make API call
	response := client.Post[models.AssignedIpAddress](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
