// Code generated by generate-services. DO NOT EDIT.

package ipam

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createorupdateresourceacl

# Create or update an ACL for a specific resource

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - resourceId: Resource ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := ipam.Createorupdateresourceacl(ctx, client, tracer, tenantId, resourceId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ipam
operationId: createOrUpdateResourceAcl
*/
func Createorupdateresourceacl(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, resourceId string, requestBody *models.AccessControlList) client.Response[models.ResourceACL] {
	ctx, span := tracer.Start(ctx, "createOrUpdateResourceAcl", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("resourceId", resourceId)))
	defer span.End()

	path := utils.Path("/v4/ipam/organisations/%s/acl/resources/%s", tenantId, resourceId)

	// Make API call
	response := client.Put[models.ResourceACL](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
