// Code generated by generate-services. DO NOT EDIT.

package ipam

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getregionsforowner

# Get regions for a given owner

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:

# Returns the operation result or an error

Example:

	response := ipam.Getregionsforowner(ctx, client, tracer, tenantId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ipam
operationId: getRegionsForOwner
*/
func Getregionsforowner(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string) client.Response[[]models.Region2] {
	ctx, span := tracer.Start(ctx, "getRegionsForOwner", trace.WithAttributes(attribute.String("tenantId", tenantId)))
	defer span.End()

	path := utils.Path("/v4/ipam/organisations/%s/regions", tenantId)

	// Make API call
	response := client.Get[[]models.Region2](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
