// Code generated by generate-services. DO NOT EDIT.

package ipam

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listipaddressesforresource

# Get IP addresses for a specific resource

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - resourceId: Resource ID

# Returns the operation result or an error

Example:

	response := ipam.Listipaddressesforresource(ctx, client, tracer, tenantId, resourceId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ipam
operationId: listIpAddressesForResource
*/
func Listipaddressesforresource(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, resourceId string) client.Response[[]models.AssignedIpAddress] {
	ctx, span := tracer.Start(ctx, "listIpAddressesForResource", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("resourceId", resourceId)))
	defer span.End()

	path := utils.Path("/v4/ipam/organisations/%s/assignment/resources/%s", tenantId, resourceId)

	// Make API call
	response := client.Get[[]models.AssignedIpAddress](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
