// Code generated by generate-services. DO NOT EDIT.

package ipam

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Replaceregionforowner

# Update region for a given owner

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - regionId: Region ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := ipam.Replaceregionforowner(ctx, client, tracer, tenantId, regionId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ipam
operationId: replaceRegionForOwner
*/
func Replaceregionforowner(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, regionId string, requestBody *models.UpdateRegionInput) client.Response[models.Region2] {
	ctx, span := tracer.Start(ctx, "replaceRegionForOwner", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("regionId", regionId)))
	defer span.End()

	path := utils.Path("/v4/ipam/organisations/%s/regions/%s", tenantId, regionId)

	// Make API call
	response := client.Put[models.Region2](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
