// Code generated by generate-services. DO NOT EDIT.

package ipam

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Unfreezeipaddress

# Unfreeze IP address

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - resourceId: Resource ID
  - ipAddress: IP Address

# Returns the operation result or an error

Example:

	response := ipam.Unfreezeipaddress(ctx, client, tracer, tenantId, resourceId, ipAddress)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ipam
operationId: unfreezeIpAddress
*/
func Unfreezeipaddress(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, resourceId string, ipAddress string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "unfreezeIpAddress", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("resourceId", resourceId), attribute.String("ipAddress", ipAddress)))
	defer span.End()

	path := utils.Path("/v4/ipam/organisations/%s/resources/%s/ip/%s/unfreeze", tenantId, resourceId, ipAddress)

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
