// Code generated by generate-services. DO NOT EDIT.

package matomo

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Creatematomo POST /v2/providers/addon-matomo/resources — provision a new Matomo addon.

📥 Algo Source (Legacy): `MatomoProviderService.provision` — insert
(`PROVISIONING`) → create MySQL → create backend (Redis|KV) → resolve the PHP
product instance → create the PHP app (full env incl. Keycloak) → register
DNS → delete the default cleverapps vhost → set the favourite vhost → restart
without cache. Any partial failure marks the addon `PROVISIONING_ERROR` and
still returns 201 (`handleFailedDeployement`).

🔧 Algo Rust: same sequence in `orchestrate_provision`. On success the row
stays `PROVISIONING` (legacy parity — the legacy service never sets `ACTIVE`);
only a partial failure moves it to `PROVISIONING_ERROR`. Response `config` is
empty and `message` is `"Created"` (or the degraded message). Internal
endpoint — no per-user guard.

Issue: #660

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := matomo.Creatematomo(ctx, client, tracer, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: matomo
operationId: createMatomo
*/
func Creatematomo(ctx context.Context, c *client.Client, tracer trace.Tracer, requestBody *models.ProvisionRequest) client.Response[models.ProvisionResponse] {
	ctx, span := tracer.Start(ctx, "createMatomo")
	defer span.End()

	path := utils.Path("/v2/providers/addon-matomo/resources")

	// Make API call
	response := client.Post[models.ProvisionResponse](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
