// Code generated by generate-services. DO NOT EDIT.

package matomo

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletematomo

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonId:

# Returns the operation result or an error

Example:

	response := matomo.Deletematomo(ctx, client, tracer, addonId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: matomo
operationId: deleteMatomo
*/
func Deletematomo(ctx context.Context, c *client.Client, tracer trace.Tracer, addonId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteMatomo", trace.WithAttributes(attribute.String("addonId", addonId)))
	defer span.End()

	path := utils.Path("/v2/providers/addon-matomo/resources/%s", addonId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
