// Code generated by generate-services. DO NOT EDIT.

package grafana

// Option defines a functional option for grafana operations
type Option func(*Options)

// Options holds query parameters for grafana operations
type Options struct{}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}
	return ""
}
