// Code generated by generate-services. DO NOT EDIT.

package cc_admin_auth

// Option defines a functional option for cc_admin_auth operations
type Option func(*Options)

// Options holds query parameters for cc_admin_auth operations
type Options struct{}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}
	return ""
}
