// Code generated by generate-services. DO NOT EDIT.

package addons

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Addaddontagbyorgaandaddonid PUT /v2/organisations/{id}/addons/{addon_id}/tags/{tag} — add a tag.

Source: cc-api OrganisationAddonsAPI.java addTag()
Issue: #108

Algorithm: Verify org membership + addon ownership, insert tag
Legacy: cc-api OrganisationAddonsAPI.java addTag()
Conformity: faithful -- idempotent tag add with RBAC

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - addonId: Addon ID
  - tag: Tag

# Returns the operation result or an error

Example:

	response := addons.Addaddontagbyorgaandaddonid(ctx, client, tracer, id, addonId, tag)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: addons
operationId: addAddonTagByOrgaAndAddonId
*/
func Addaddontagbyorgaandaddonid(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, addonId string, tag string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "addAddonTagByOrgaAndAddonId", trace.WithAttributes(attribute.String("id", id), attribute.String("addonId", addonId), attribute.String("tag", tag)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/addons/%s/tags/%s", id, addonId, tag)

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
