// Code generated by generate-services. DO NOT EDIT.

package addons

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getselfaddonbyid GET /v2/self/addons/{addon_id} — get a personal addon.

Source: cc-api SelfAddonsAPI.java getAddon()
Issue: #108

Algorithm: Find addon by ID, verify ownership, build AddonView
Legacy: cc-api SelfAddonsAPI.java getAddon()
Conformity: faithful -- ownership check + 404 if not found

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonId: Addon ID

# Returns the operation result or an error

Example:

	response := addons.Getselfaddonbyid(ctx, client, tracer, addonId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: addons
operationId: getSelfAddonById
*/
func Getselfaddonbyid(ctx context.Context, c *client.Client, tracer trace.Tracer, addonId string) client.Response[models.AddonView] {
	ctx, span := tracer.Start(ctx, "getSelfAddonById", trace.WithAttributes(attribute.String("addonId", addonId)))
	defer span.End()

	path := utils.Path("/v2/self/addons/%s", addonId)

	// Make API call
	response := client.Get[models.AddonView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
