// Code generated by generate-services. DO NOT EDIT.

package addons

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getaddonmigration GET /v2/organisations/{id}/addons/{addon_id}/migrations/{migration_id} — get migration.

Source: cc-api OrganisationAddonsAPI.java getAddonMigration()
Source: cc-api AddonHelper.java:661-671 (getAddonMigrations with migrationId)
Source: cc-api AddonAPIHelper.java:278-298 (getMigrations — GET to provider)
Behavior: checks membership + addon ownership, proxies GET /{real_id}/migrations/{migration_id}

	to the addon provider, forwards response.

Issue: #108

Algorithm: Verify org membership + addon ownership, proxy GET /{real_id}/migrations/{id} to provider
Legacy: cc-api OrganisationAddonsAPI.java getAddonMigration() -> AddonAPIHelper.getMigrations()
Conformity: faithful -- provider proxy for single migration status

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - addonId: Addon ID
  - migrationId: Migration ID

# Returns the operation result or an error

Example:

	response := addons.Getaddonmigration(ctx, client, tracer, id, addonId, migrationId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: addons
operationId: getAddonMigration
*/
func Getaddonmigration(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, addonId string, migrationId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "getAddonMigration", trace.WithAttributes(attribute.String("id", id), attribute.String("addonId", addonId), attribute.String("migrationId", migrationId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/addons/%s/migrations/%s", id, addonId, migrationId)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
