// Code generated by generate-services. DO NOT EDIT.

package addons

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
V4GetAddonEnvFromProvider GET /v4/addon-providers/{provider_id}/addons/{real_id}/env

Proxy endpoint that forwards GET /addons/{real_id}/env to the addon provider.
Used by Terraform (config-provider), Console3, clever-tools.

Source: cc-api AuthorizationHelper.java:1292 authorize_v4_addonproviders()
Source: terraform-provider-clevercloud — clevercloud_config_provider resource
Spec: analysis-output/38-github-api-consumers.md §Terraform — config-provider
Issue: #313

Algorithm: Resolve provider URL, proxy GET /addons/{real_id}/env
Legacy: cc-api — v4 addon provider env proxy
Conformity: faithful -- Terraform config-provider resource uses this

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - provider_id: Addon provider ID (e.g., config-provider)
  - real_id: Provider-side addon real ID

# Returns the operation result or an error

Example:

	response := addons.V4GetAddonEnvFromProvider(ctx, client, tracer, provider_id, real_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: addons
operationId: v4_get_addon_env_from_provider
*/
func V4GetAddonEnvFromProvider(ctx context.Context, c *client.Client, tracer trace.Tracer, provider_id string, real_id string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "v4_get_addon_env_from_provider", trace.WithAttributes(attribute.String("provider_id", provider_id), attribute.String("real_id", real_id)))
	defer span.End()

	path := utils.Path("/v4/addon-providers/%s/addons/%s/env", provider_id, real_id)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
