// Code generated by generate-services. DO NOT EDIT.

package materia_incubator

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletematerialayeraddon

Deprovision an existing Materia layer addon (sync part)

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - layerId:
  - addonId:

# Returns the operation result or an error

Example:

	response := materia_incubator.Deletematerialayeraddon(ctx, client, tracer, layerId, addonId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: materia_incubator
operationId: deleteMateriaLayerAddon
*/
func Deletematerialayeraddon(ctx context.Context, c *client.Client, tracer trace.Tracer, layerId string, addonId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteMateriaLayerAddon", trace.WithAttributes(attribute.String("layerId", layerId), attribute.String("addonId", addonId)))
	defer span.End()

	path := utils.Path("/v2/providers/materia/%s/resources/%s", layerId, addonId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
