// Code generated by generate-services. DO NOT EDIT.

package log

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createdrainbyresource

Create drain.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - resourceId: Resource identifier for drain creation. Accepted prefixes: app_, postgresql_, mysql_, mongodb_, redis_, elasticsearch_.
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := log.Createdrainbyresource(ctx, client, tracer, ownerId, resourceId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: log
operationId: createDrainByResource
*/
func Createdrainbyresource(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, resourceId string, requestBody *models.WannabeDrain) client.Response[models.Drain] {
	ctx, span := tracer.Start(ctx, "createDrainByResource", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("resourceId", resourceId)))
	defer span.End()

	path := utils.Path("/v4/drains/organisations/%s/resources/%s/drains", ownerId, resourceId)

	// Make API call
	response := client.Post[models.Drain](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
