// Code generated by generate-services. DO NOT EDIT.

package log

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletedrain

Delete drain.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - applicationId:
  - drainId:

# Returns the operation result or an error

Example:

	response := log.Deletedrain(ctx, client, tracer, ownerId, applicationId, drainId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: log
operationId: deleteDrain
*/
func Deletedrain(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, applicationId string, drainId string) client.Response[models.Drain] {
	ctx, span := tracer.Start(ctx, "deleteDrain", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("applicationId", applicationId), attribute.String("drainId", drainId)))
	defer span.End()

	path := utils.Path("/v4/drains/organisations/%s/applications/%s/drains/%s", ownerId, applicationId, drainId)

	// Make API call
	response := client.Delete[models.Drain](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
