// Code generated by generate-services. DO NOT EDIT.

package log

import (
	"fmt"
	"strings"
)

// Option defines a functional option for log operations
type Option func(*Options)

// Options holds query parameters for log operations
type Options struct {
	Executionstatus      *[]string `url:"executionStatus,omitempty"`
	Executionstatusnotin *[]string `url:"executionStatusNotIn,omitempty"`
	Status               *[]string `url:"status,omitempty"`
}

// WithExecutionstatus sets the executionStatus query parameter
func WithExecutionstatus(executionStatus []string) Option {
	return func(o *Options) {
		o.Executionstatus = &executionStatus
	}
}

// WithExecutionstatusnotin sets the executionStatusNotIn query parameter
func WithExecutionstatusnotin(executionStatusNotIn []string) Option {
	return func(o *Options) {
		o.Executionstatusnotin = &executionStatusNotIn
	}
}

// WithStatus sets the status query parameter
func WithStatus(status []string) Option {
	return func(o *Options) {
		o.Status = &status
	}
}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}

	var params []string
	if options.Executionstatus != nil {
		params = append(params, fmt.Sprintf("executionStatus=%v", *options.Executionstatus))
	}
	if options.Executionstatusnotin != nil {
		params = append(params, fmt.Sprintf("executionStatusNotIn=%v", *options.Executionstatusnotin))
	}
	if options.Status != nil {
		params = append(params, fmt.Sprintf("status=%v", *options.Status))
	}

	if len(params) == 0 {
		return ""
	}
	return strings.Join(params, "&")
}
