// Code generated by generate-services. DO NOT EDIT.

package log

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Resetdraincursorbyresource

Reset drain cursor to now.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - resourceId: Resource identifier for drain target. Accepted prefixes: app_, cellar_, postgresql_, mysql_, mongodb_, elasticsearch_, redis_, pulsar_, matomo_, keycloak_, otoroshi_, cumulocity_, hivemq_, metabase_, xen_, ai_, kms_, kubernetes_, kv_, ts_, grist_. Generic addon_ prefix is not accepted.
  - drainId:

# Returns the operation result or an error

Example:

	response := log.Resetdraincursorbyresource(ctx, client, tracer, ownerId, resourceId, drainId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: log
operationId: resetDrainCursorByResource
*/
func Resetdraincursorbyresource(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, resourceId string, drainId string) client.Response[models.Drain] {
	ctx, span := tracer.Start(ctx, "resetDrainCursorByResource", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("resourceId", resourceId), attribute.String("drainId", drainId)))
	defer span.End()

	path := utils.Path("/v4/drains/organisations/%s/resources/%s/drains/%s/reset-cursor", ownerId, resourceId, drainId)

	// Make API call
	response := client.Patch[models.Drain](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
