// Code generated by generate-services. DO NOT EDIT.

package materia_kv

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getmateriakvv4

# Get a MateriaKV

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - resourceId:

# Returns the operation result or an error

Example:

	response := materia_kv.Getmateriakvv4(ctx, client, tracer, ownerId, resourceId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: materia_kv
operationId: getMateriaKvV4
*/
func Getmateriakvv4(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, resourceId string) client.Response[models.MateriaDB1] {
	ctx, span := tracer.Start(ctx, "getMateriaKvV4", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("resourceId", resourceId)))
	defer span.End()

	path := utils.Path("/v4/materia/organisations/%s/materia/databases/%s", ownerId, resourceId)

	// Make API call
	response := client.Get[models.MateriaDB1](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
