// Code generated by generate-services. DO NOT EDIT.

package tokens

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listtokens

List tokens for a tenant.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := tokens.Listtokens(ctx, client, tracer, tenantId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: tokens
operationId: listTokens
*/
func Listtokens(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, opts ...Option) client.Response[[]models.Token1] {
	ctx, span := tracer.Start(ctx, "listTokens", trace.WithAttributes(attribute.String("tenantId", tenantId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/tokens", tenantId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.Token1](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
