// Code generated by generate-services. DO NOT EDIT.

package otoroshi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getotoroshiconfigfile GET /v4/addon-providers/addon-otoroshi/addons/{otoroshi_id}/config.yaml

Source: references/legacy/ovd/modules/otoroshi/services/OtoroshiProviderService.scala — getConfigurationFile()
Source: references/legacy/ovd/modules/otoroshi/models/OtoroshiCtlConfig.scala — from()

📥 **Algo Source (Legacy):**
- Get full OtoroshiView (includes env vars from cc-api)
- Build OtoroshiCtlConfig from the view (hostname from api.url, credentials from api.user/secret)
- Serialize to YAML using circe-yaml Printer(preserveOrder=true, explicitStart=true)
- Return as text/yaml
- Source: ovd OtoroshiProviderService.scala:714 getConfigurationFile()

Issue: #313

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - OtoroshiId: Otoroshi instance ID

# Returns the operation result or an error

Example:

	response := otoroshi.Getotoroshiconfigfile(ctx, client, tracer, OtoroshiId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: otoroshi
operationId: getOtoroshiConfigFile
*/
func Getotoroshiconfigfile(ctx context.Context, c *client.Client, tracer trace.Tracer, OtoroshiId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "getOtoroshiConfigFile", trace.WithAttributes(attribute.String("OtoroshiId", OtoroshiId)))
	defer span.End()

	path := utils.Path("/v4/addon-providers/addon-otoroshi/addons/%s/config.yaml", OtoroshiId)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
