// Code generated by generate-services. DO NOT EDIT.

package otoroshi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getotoroshiproviderinformation

retrieve the Otoroshi provider information

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := otoroshi.Getotoroshiproviderinformation(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: otoroshi
operationId: getOtoroshiProviderInformation
*/
func Getotoroshiproviderinformation(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[models.ProviderInfos] {
	ctx, span := tracer.Start(ctx, "getOtoroshiProviderInformation")
	defer span.End()

	path := utils.Path("/v4/addon-providers/otoroshi")

	// Make API call
	response := client.Get[models.ProviderInfos](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
