// Code generated by generate-services. DO NOT EDIT.

package otoroshi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getotoroshiinfos

get all otoroshi info via internal path

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - OtoroshiId:

# Returns the operation result or an error

Example:

	response := otoroshi.Getotoroshiinfos(ctx, client, tracer, OtoroshiId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: otoroshi
operationId: getOtoroshiInfos
*/
func Getotoroshiinfos(ctx context.Context, c *client.Client, tracer trace.Tracer, OtoroshiId string) client.Response[models.OtoroshiView] {
	ctx, span := tracer.Start(ctx, "getOtoroshiInfos", trace.WithAttributes(attribute.String("OtoroshiId", OtoroshiId)))
	defer span.End()

	path := utils.Path("/v4/otoroshi/%s", OtoroshiId)

	// Make API call
	response := client.Get[models.OtoroshiView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
