// Code generated by generate-services. DO NOT EDIT.

package metrics

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listheatmap GET /v4/stats/organisations/{ownerId}/requests — request heatmap.

📥 **Algo Source (Legacy):**
`getHeatmap` — geo request heatmap over a date range.
  - resolveDateRange(from, to) → (resolvedFrom, resolvedTo); from > to → BadRequest.
  - RequestHeatmap(accesslogsToken, ownerId, applicationId|wildcard, from, to).toWarpScript →
    heatmap.mc2: FETCH `loadbalancer_client_http_request_location_count` over timespan = to-from,
    single-bucket BUCKETIZE, REDUCE ['geo_cell'], HHCODE-> decode (lon then lat) →
    `{ lat, long, accessCount }`.
  - execStack → stack.head[List[MetricsHeatmapResponse]].
  - Source: ovd .../actors/MetricsAPIActor.scala:458-489, RequestHeatmap.scala, heatmap.mc2

🔧 **Algo Rust (Implementation):**
  - `resolve_accesslogs_request` (ownerId, applicationId, then the from/to + since/until range) →
    400 on a bad id or on from > to.
  - render_heatmap (verbatim heatmap.mc2): from_us/to_us = ws_epoch_micros, double-quoted
    token/owner/app. The token is the STATIC `accesslogsToken` ctor field (no per-request fetch),
    read from `module.config().accesslogs_token`.
  - exec → parse_heatmap (top-of-stack `{ lat, long, accessCount }` list).
  - Return `Vec<MetricsHeatmapResponse>`.

Source: ovd modules/metrics/.../actors/MetricsAPIActor.scala:458-489 (getHeatmap)
Issue: #767

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Organisation/owner ID
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := metrics.Listheatmap(ctx, client, tracer, ownerId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: metrics
operationId: listHeatmap
*/
func Listheatmap(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, opts ...Option) client.Response[[]models.MetricsHeatmapResponse] {
	ctx, span := tracer.Start(ctx, "listHeatmap", trace.WithAttributes(attribute.String("ownerId", ownerId)))
	defer span.End()

	path := utils.Path("/v4/stats/organisations/%s/requests", ownerId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.MetricsHeatmapResponse](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
