// Code generated by generate-services. DO NOT EDIT.

package configuration_provider

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createconfigurationprovider

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := configuration_provider.Createconfigurationprovider(ctx, client, tracer, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: configuration_provider
operationId: createConfigurationProvider
*/
func Createconfigurationprovider(ctx context.Context, c *client.Client, tracer trace.Tracer, requestBody *models.ProvisionRequest) client.Response[models.ProvisionResponse] {
	ctx, span := tracer.Start(ctx, "createConfigurationProvider")
	defer span.End()

	path := utils.Path("/v2/providers/config-provider/resources")

	// Make API call
	response := client.Post[models.ProvisionResponse](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
