// Code generated by generate-services. DO NOT EDIT.

package configuration_provider

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteconfigurationprovider DELETE /v2/providers/config-provider/resources/{addon_id} — deprovision config-provider addon.

Legacy: ovd routes.scala:43 deleteAddonV2
Algorithm:
  - Fetch row first (build final view), then UPDATE status=DELETED
  - Returns 200 with body (NOT 204 like other providers)

Conformity: YES

Source: references/legacy/ovd/modules/configprovider/api/routes.scala deleteAddonV2
Behavior: marks as DELETED, returns 200 with addon view body (NOT 204!)
This is intentionally different from most other addon providers (KMS returns 204).
Issue: #2

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonId: ConfigProvider addon ID

# Returns the operation result or an error

Example:

	response := configuration_provider.Deleteconfigurationprovider(ctx, client, tracer, addonId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: configuration_provider
operationId: deleteConfigurationProvider
*/
func Deleteconfigurationprovider(ctx context.Context, c *client.Client, tracer trace.Tracer, addonId string) client.Response[models.ConfigProvider] {
	ctx, span := tracer.Start(ctx, "deleteConfigurationProvider", trace.WithAttributes(attribute.String("addonId", addonId)))
	defer span.End()

	path := utils.Path("/v2/providers/config-provider/resources/%s", addonId)

	// Make API call
	response := client.Delete[models.ConfigProvider](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
