// Code generated by generate-services. DO NOT EDIT.

package configuration_provider

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getconfigurationproviderenv

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonId:

# Returns the operation result or an error

Example:

	response := configuration_provider.Getconfigurationproviderenv(ctx, client, tracer, addonId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: configuration_provider
operationId: getConfigurationProviderEnv
*/
func Getconfigurationproviderenv(ctx context.Context, c *client.Client, tracer trace.Tracer, addonId string) client.Response[[]models.EnvVar] {
	ctx, span := tracer.Start(ctx, "getConfigurationProviderEnv", trace.WithAttributes(attribute.String("addonId", addonId)))
	defer span.End()

	path := utils.Path("/v4/addon-providers/config-provider/addons/%s/env", addonId)

	// Make API call
	response := client.Get[[]models.EnvVar](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
