// Code generated by generate-services. DO NOT EDIT.

package container_registry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteregistrytoken

Revoke a container registry access token.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - registryId:
  - tokenId:

# Returns the operation result or an error

Example:

	response := container_registry.Deleteregistrytoken(ctx, client, tracer, tenantId, registryId, tokenId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: container_registry
operationId: deleteRegistryToken
*/
func Deleteregistrytoken(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, registryId string, tokenId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteRegistryToken", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("registryId", registryId), attribute.String("tokenId", tokenId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/container-registry/%s/tokens/%s", tenantId, registryId, tokenId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
