// Code generated by generate-services. DO NOT EDIT.

package container_registry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
ListRegistries GET /v4/tenants/{tenant_id}/container-registry/registries — list all registries for a tenant.

Source: references/legacy/ovd/modules/container-registry/controllers/ContainerRegistryController.scala listRegistriesServerEndpoint
Source: references/legacy/ovd/modules/container-registry/repositories/ContainerRegistryRepository.scala findByTenantId
Behavior: returns all registries for the given tenant
Issue: #643

**Legacy**: ovd ContainerRegistryController.scala:110 listRegistriesServerEndpoint
**Algorithm**:
  - SELECT all registries by tenant_id, return list of views

**Conformity**: YES

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenant_id: Tenant ID

# Returns the operation result or an error

Example:

	response := container_registry.ListRegistries(ctx, client, tracer, tenant_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: container_registry
operationId: list_registries
*/
func ListRegistries(ctx context.Context, c *client.Client, tracer trace.Tracer, tenant_id string) client.Response[[]models.ContainerRegistry] {
	ctx, span := tracer.Start(ctx, "list_registries", trace.WithAttributes(attribute.String("tenant_id", tenant_id)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/container-registry/registries", tenant_id)

	// Make API call
	response := client.Get[[]models.ContainerRegistry](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
