// Code generated by generate-services. DO NOT EDIT.

package container_registry

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
ProvisionContainerRegistry POST /v2/providers/addon-container-registry/resources — provision a new container registry addon.

Source: references/legacy/ovd/modules/container-registry/services/ContainerRegistryProvisioningService.scala createRegistry
Behavior: creates a container_registry record with PENDING → PROVISIONED statuses,

	returns Heroku-style provision response with CC_DOCKER_REGISTRY_HOST env var

Issue: #643

**Legacy**: ovd ContainerRegistryController.scala (Heroku provision protocol)
**Algorithm**:
  - INSERT registry with PROVISIONED status, return Heroku ProvisionResponse with env vars

**Conformity**: YES

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := container_registry.ProvisionContainerRegistry(ctx, client, tracer, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: container_registry
operationId: provision_container_registry
*/
func ProvisionContainerRegistry(ctx context.Context, c *client.Client, tracer trace.Tracer, requestBody *models.ProvisionRequest) client.Response[models.ProvisionResponse] {
	ctx, span := tracer.Start(ctx, "provision_container_registry")
	defer span.End()

	path := utils.Path("/v2/providers/addon-container-registry/resources")

	// Make API call
	response := client.Post[models.ProvisionResponse](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
