// Code generated by generate-services. DO NOT EDIT.

package redis_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
RedisGetConfiguration

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Redis addon ID

# Returns the operation result or an error

Example:

	response := redis_addon.RedisGetConfiguration(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: redis_addon
operationId: redis_get_configuration
*/
func RedisGetConfiguration(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "redis_get_configuration", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/providers/redis-addon/internal/%s/configuration", id)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
