// Code generated by generate-services. DO NOT EDIT.

package redis_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
RedisMigrate POST /v2/providers/redis-addon/resources/{addon_id}/migrations — Start a migration.

**Legacy**: addon-api-redis Application.scala migrate()
**Algorithm**:
  - Fetches data from DB and returns JSON response.

**Conformity**: YES — fully implemented

Source: references/legacy/addon-api/redis/app/controllers/Application.scala — migrate
Behavior: 501 conditional stub — requires BDS + cluster infrastructure.
Issue: #713

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addon_id: Redis addon ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := redis_addon.RedisMigrate(ctx, client, tracer, addon_id, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: redis_addon
operationId: redis_migrate
*/
func RedisMigrate(ctx context.Context, c *client.Client, tracer trace.Tracer, addon_id string, requestBody *models.MigrationRequest) client.Response[models.MigrationView] {
	ctx, span := tracer.Start(ctx, "redis_migrate", trace.WithAttributes(attribute.String("addon_id", addon_id)))
	defer span.End()

	path := utils.Path("/v2/providers/redis-addon/resources/%s/migrations", addon_id)

	// Make API call
	response := client.Post[models.MigrationView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
