// Code generated by generate-services. DO NOT EDIT.

package redis_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
RedisSetAsSlave PUT /v2/providers/redis-addon/dashboard/master — Set this addon as slave of another master.

**Legacy**: addon-api-redis Dashboard.scala setAsSlave()
**Algorithm**:
  - Returns 501 — requires direct instance replication command.

**Conformity**: YES (Cloud Versatile conditional — works when configured)

Source: references/legacy/addon-api/redis/app/controllers/Dashboard.scala — setAsSlave
Behavior: 501 conditional stub — requires direct Redis SLAVEOF command.
Issue: #713

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := redis_addon.RedisSetAsSlave(ctx, client, tracer, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: redis_addon
operationId: redis_set_as_slave
*/
func RedisSetAsSlave(ctx context.Context, c *client.Client, tracer trace.Tracer, requestBody *models.MasterInfo) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "redis_set_as_slave")
	defer span.End()

	path := utils.Path("/v2/providers/redis-addon/dashboard/master")

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
