// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createdownloadurl Presign a direct S3 download URL

Returns `{ url, expiresAt }`: a presigned S3 URL the caller GETs the object bytes from, straight from the storage cluster. `expiresIn` sets its lifetime in seconds (300 by default) and is used as given, with no clamping. Both the bucket and the object must already exist. The caller must be authenticated and must be the add-on's owner (personal add-ons) or a member of the organisation in the path. An unknown add-on, bucket or object answers 404.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - CellarId: Cellar addon ID
  - bucketName: Bucket name
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := cellar.Createdownloadurl(ctx, client, tracer, ownerId, CellarId, bucketName, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cellar
operationId: createDownloadUrl
*/
func Createdownloadurl(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, CellarId string, bucketName string, requestBody *models.SignedUrlRequest) client.Response[models.SignedUrlResponse] {
	ctx, span := tracer.Start(ctx, "createDownloadUrl", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("CellarId", CellarId), attribute.String("bucketName", bucketName)))
	defer span.End()

	path := utils.Path("/v4/cellar/organisations/%s/cellar/%s/buckets/%s/objects/download-url", ownerId, CellarId, bucketName)

	// Make API call
	response := client.Post[models.SignedUrlResponse](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
