// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createuploadurl

generate a presigned URL for uploading an object

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - CellarId:
  - bucketName:
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := cellar.Createuploadurl(ctx, client, tracer, ownerId, CellarId, bucketName, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cellar
operationId: createUploadUrl
*/
func Createuploadurl(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, CellarId string, bucketName string, requestBody *models.SignedUrlRequest) client.Response[models.SignedUrlResponse] {
	ctx, span := tracer.Start(ctx, "createUploadUrl", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("CellarId", CellarId), attribute.String("bucketName", bucketName)))
	defer span.End()

	path := utils.Path("/v4/cellar/organisations/%s/cellar/%s/buckets/%s/objects/upload-url", ownerId, CellarId, bucketName)

	// Make API call
	response := client.Post[models.SignedUrlResponse](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
