// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createcellarbucket Create a bucket

Creates a bucket in this add-on's storage and returns its view: name, versioning status, and the object count, total size and timestamps read back from the cluster. Set `versioning` in the body to turn on object versioning at creation. The caller must be authenticated and must be the add-on's owner (personal add-ons) or a member of the organisation in the path. An unknown add-on answers 404, and a bucket name already in use answers 409.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - CellarId: Cellar addon ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := cellar.Createcellarbucket(ctx, client, tracer, ownerId, CellarId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cellar
operationId: createCellarBucket
*/
func Createcellarbucket(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, CellarId string, requestBody *models.CreateBucketRequest) client.Response[models.BucketView] {
	ctx, span := tracer.Start(ctx, "createCellarBucket", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("CellarId", CellarId)))
	defer span.End()

	path := utils.Path("/v4/cellar/organisations/%s/cellar/%s/buckets", ownerId, CellarId)

	// Make API call
	response := client.Post[models.BucketView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
