// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletecellarbucket Delete a bucket

Deletes a bucket from this add-on's storage and answers 200 with an empty body. The bucket must be empty unless `purgeObjects=true` is passed, which removes its objects first; a non-empty bucket without that flag answers 409. The caller must be authenticated and must be the add-on's owner (personal add-ons) or a member of the organisation in the path. An unknown add-on or bucket answers 404.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - CellarId: Cellar addon ID
  - bucketName: Bucket name
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := cellar.Deletecellarbucket(ctx, client, tracer, ownerId, CellarId, bucketName, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cellar
operationId: deleteCellarBucket
*/
func Deletecellarbucket(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, CellarId string, bucketName string, opts ...Option) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteCellarBucket", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("CellarId", CellarId), attribute.String("bucketName", bucketName)))
	defer span.End()

	path := utils.Path("/v4/cellar/organisations/%s/cellar/%s/buckets/%s", ownerId, CellarId, bucketName)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
