// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getcluster

get a Cellar cluster by ID

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - ClusterIndex:

# Returns the operation result or an error

Example:

	response := cellar.Getcluster(ctx, client, tracer, ownerId, ClusterIndex)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cellar
operationId: getCluster
*/
func Getcluster(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, ClusterIndex int64) client.Response[models.CellarCluster1] {
	ctx, span := tracer.Start(ctx, "getCluster", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.Int64("ClusterIndex", ClusterIndex)))
	defer span.End()

	path := utils.Path("/v4/cellar/organisations/%s/clusters/%s", ownerId, ClusterIndex)

	// Make API call
	response := client.Get[models.CellarCluster1](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
