// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listclusters

list all Cellar clusters

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := cellar.Listclusters(ctx, client, tracer, ownerId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cellar
operationId: listClusters
*/
func Listclusters(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, opts ...Option) client.Response[[]models.CellarCluster1] {
	ctx, span := tracer.Start(ctx, "listClusters", trace.WithAttributes(attribute.String("ownerId", ownerId)))
	defer span.End()

	path := utils.Path("/v4/cellar/organisations/%s/clusters", ownerId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.CellarCluster1](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
