// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"fmt"
	"net/url"
	"strings"
)

// Option defines a functional option for cellar operations
type Option func(*Options)

// Options holds query parameters for cellar operations
type Options struct {
	Count              *int    `url:"count,omitempty"`
	Cursor             *string `url:"cursor,omitempty"`
	Force              *bool   `url:"force,omitempty"`
	Includeunavailable *bool   `url:"includeUnavailable,omitempty"`
	Prefix             *string `url:"prefix,omitempty"`
	Purgeobjects       *bool   `url:"purgeObjects,omitempty"`
}

// WithCount sets the count query parameter
func WithCount(count int) Option {
	return func(o *Options) {
		o.Count = &count
	}
}

// WithCursor sets the cursor query parameter
func WithCursor(cursor string) Option {
	return func(o *Options) {
		o.Cursor = &cursor
	}
}

// WithForce sets the force query parameter
func WithForce(force bool) Option {
	return func(o *Options) {
		o.Force = &force
	}
}

// WithIncludeunavailable sets the includeUnavailable query parameter
func WithIncludeunavailable(includeUnavailable bool) Option {
	return func(o *Options) {
		o.Includeunavailable = &includeUnavailable
	}
}

// WithPrefix sets the prefix query parameter
func WithPrefix(prefix string) Option {
	return func(o *Options) {
		o.Prefix = &prefix
	}
}

// WithPurgeobjects sets the purgeObjects query parameter
func WithPurgeobjects(purgeObjects bool) Option {
	return func(o *Options) {
		o.Purgeobjects = &purgeObjects
	}
}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}

	var params []string
	if options.Count != nil {
		params = append(params, fmt.Sprintf("count=%d", *options.Count))
	}
	if options.Cursor != nil {
		params = append(params, fmt.Sprintf("cursor=%s", url.QueryEscape(*options.Cursor)))
	}
	if options.Force != nil {
		params = append(params, fmt.Sprintf("force=%t", *options.Force))
	}
	if options.Includeunavailable != nil {
		params = append(params, fmt.Sprintf("includeUnavailable=%t", *options.Includeunavailable))
	}
	if options.Prefix != nil {
		params = append(params, fmt.Sprintf("prefix=%s", url.QueryEscape(*options.Prefix)))
	}
	if options.Purgeobjects != nil {
		params = append(params, fmt.Sprintf("purgeObjects=%t", *options.Purgeobjects))
	}

	if len(params) == 0 {
		return ""
	}
	return strings.Join(params, "&")
}
