// Code generated by generate-services. DO NOT EDIT.

package cellar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Uploadcellarobject Upload an object through an issued upload link

Streams the request body straight into a bucket as the named object and returns the stored key, the byte count, the ETag and the content type echoed back from the request. No body-size limit applies on this route. This is the redemption route for a link issued by the `objects/{objectKey}/presigned-url` route: the caller must present that link's token, either in the `authorization` query parameter or as a `Bearer` header, and the token is accepted only for the exact add-on, bucket and object key it was issued for. The request `Content-Type` is stored with the object, falling back to `application/octet-stream` when absent, and `x-amz-meta-*` headers become the object's user metadata, lowercased with the prefix stripped. A request presenting no token, or one that cannot be verified, answers 401; a token that has expired, or that was issued for a different add-on, bucket or key, answers 403; and an unknown add-on or bucket answers 404.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - CellarId: Cellar addon ID
  - bucketName: Bucket name
  - objectKey: Object key

# Returns the operation result or an error

Example:

	response := cellar.Uploadcellarobject(ctx, client, tracer, ownerId, CellarId, bucketName, objectKey)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cellar
operationId: uploadCellarObject
*/
func Uploadcellarobject(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, CellarId string, bucketName string, objectKey string) client.Response[models.UploadObjectResponse] {
	ctx, span := tracer.Start(ctx, "uploadCellarObject", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("CellarId", CellarId), attribute.String("bucketName", bucketName), attribute.String("objectKey", objectKey)))
	defer span.End()

	path := utils.Path("/v4/cellar/organisations/%s/cellar/%s/buckets/%s/objects/upload/%s", ownerId, CellarId, bucketName, objectKey)

	// Make API call
	response := client.Post[models.UploadObjectResponse](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
