// Code generated by generate-services. DO NOT EDIT.

package base

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createresource

Create a new resource.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - productId:
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := base.Createresource(ctx, client, tracer, tenantId, productId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: base
operationId: createResource
*/
func Createresource(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, productId string, requestBody *models.WannabeResource) client.Response[models.Resource1] {
	ctx, span := tracer.Start(ctx, "createResource", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("productId", productId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/products/%s/resources", tenantId, productId)

	// Make API call
	response := client.Post[models.Resource1](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
