// Code generated by generate-services. DO NOT EDIT.

package base

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listavailableresources

Get available resources for a tenant.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:

# Returns the operation result or an error

Example:

	response := base.Listavailableresources(ctx, client, tracer, tenantId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: base
operationId: listAvailableResources
*/
func Listavailableresources(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string) client.Response[[]models.Resource1] {
	ctx, span := tracer.Start(ctx, "listAvailableResources", trace.WithAttributes(attribute.String("tenantId", tenantId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/resources", tenantId)

	// Make API call
	response := client.Get[[]models.Resource1](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
