// Code generated by generate-services. DO NOT EDIT.

package storage

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createcephpool

Create a new ceph pool.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := storage.Createcephpool(ctx, client, tracer, tenantId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: storage
operationId: createCephPool
*/
func Createcephpool(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, requestBody *models.WannabeCephPool) client.Response[models.CephPool] {
	ctx, span := tracer.Start(ctx, "createCephPool", trace.WithAttributes(attribute.String("tenantId", tenantId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/ceph-pools", tenantId)

	// Make API call
	response := client.Post[models.CephPool](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
