// Code generated by generate-services. DO NOT EDIT.

package storage

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createcephrbdnamespace

Create a new ceph rbd namespace.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := storage.Createcephrbdnamespace(ctx, client, tracer, tenantId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: storage
operationId: createCephRBDNamespace
*/
func Createcephrbdnamespace(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, requestBody *models.WannabeCephRBDNamespace) client.Response[models.CephRBDNamespace] {
	ctx, span := tracer.Start(ctx, "createCephRBDNamespace", trace.WithAttributes(attribute.String("tenantId", tenantId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/ceph-rbd-namespaces", tenantId)

	// Make API call
	response := client.Post[models.CephRBDNamespace](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
