// Code generated by generate-services. DO NOT EDIT.

package storage

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getstorage

Get an existing storage.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - storageId:

# Returns the operation result or an error

Example:

	response := storage.Getstorage(ctx, client, tracer, tenantId, storageId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: storage
operationId: getStorage
*/
func Getstorage(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, storageId string) client.Response[models.Storage1] {
	ctx, span := tracer.Start(ctx, "getStorage", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("storageId", storageId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/storages/%s", tenantId, storageId)

	// Make API call
	response := client.Get[models.Storage1](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
