// Code generated by generate-services. DO NOT EDIT.

package storage

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updatestorage PATCH /v4/tenants/{tenantId}/storages/{storageId} -- update a storage.

Source: ovd StorageController.scala updateStorage (patch semantics from Scala StoragePatch)
Schema: V0__init_storage_table.sql — table storage
Behavior: merges patch fields into existing storage. Returns 404 if not found.

	Note: Scala StoragePatch only has label field. Our API also supports configuration
	and tags for forward compatibility. `statuses` is deliberately NOT patchable —
	server-controlled lifecycle state (reaper marker + verified instigators).

Issue: #313, #774, #864, #1124

📥 **Algo Source (Legacy):**
Patch a storage resource.
- Authorize via authorize_v4_organisation (org membership on the path tenant)
- Scala StoragePatch has only label: Option[String]
- UPDATE storage SET label = newLabel WHERE id = storageId
- Source: ovd StorageController.scala (updateStorage route)

🔧 **Algo Rust (Implementation):**
  - `OvdAuth` + `storage_op:update` on the path tenant, bound to the path storage
    (`storage` scope fact)
  - Lock the storage row (`FOR UPDATE`) and its ceph_rbd_storage child in one
    transaction, 404 if the storage is absent; a missing child degrades to a
    metadata-only patch (axo tolerance for pre-#2900 childless rows)
  - Merge the patch over the locked row, write both rows, commit
  - Return 200 with updated StorageView or 404

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId: Tenant identifier
  - storageId: Storage identifier
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := storage.Updatestorage(ctx, client, tracer, tenantId, storageId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: storage
operationId: updateStorage
*/
func Updatestorage(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, storageId string, requestBody *models.StoragePatch) client.Response[models.Storage] {
	ctx, span := tracer.Start(ctx, "updateStorage", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("storageId", storageId)))
	defer span.End()

	path := utils.Path("/v4/tenants/%s/storages/%s", tenantId, storageId)

	// Make API call
	response := client.Patch[models.Storage](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
