// Code generated by generate-services. DO NOT EDIT.

package my_sql_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
MysqlGetDeployInstruction GET /internal/{id}/instruction — the BDS deploy instruction for a dedicated
addon (the VM/ops fetch it). Requires messaging. Source: Internal.getDeployInstruction.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: provision uuid

# Returns the operation result or an error

Example:

	response := my_sql_addon.MysqlGetDeployInstruction(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: my_sql_addon
operationId: mysql_get_deploy_instruction
*/
func MysqlGetDeployInstruction(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "mysql_get_deploy_instruction", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/providers/mysql-addon/internal/%s/instruction", id)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
