// Code generated by generate-services. DO NOT EDIT.

package cc_admin

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
AdminDeleteVariant DELETE /v2/internal/instances/variants/{variant_id} — admin delete instance variant.

Deletes an instance variant if no applications are still using it.
Returns 409 Conflict if applications reference this variant.

Algorithm:
  - Parse variant_id as UUID (400 if invalid)
  - Check if instances reference this variant (409 if count > 0)
  - Transaction: DELETE variant_default_env, DELETE variant_flavors, DELETE variant

Conformity: YES — matches cc-api AvailableInstancesHelper.deleteVariant()

Source: cc-api InternalInstancesAPI.java:43-46 deleteVariant() — `authInternal(crc,

	"")`, so the route is bodyless and takes no payload layer

Source: cc-api AvailableInstancesHelper.java:373-378 deleteVariant() — :375

	`!tk.right().isCCAdmin()` → 403 ACCESS_REQUIRES_CCADMIN_AUTHENTICATION

Spec: analysis-output/34-ccadmin-analysis.md §Internal API calls
Schema: V1__Initial_schema.sql:776 — table instance_variants, instances FK
Behavior: 401 when the caller is not an internal service, 403 for any internal

	service other than ccadmin, 400 bad UUID, 409 variant in use, 204 deleted

Issue: #405, #1956, #2018

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - variant_id: Variant UUID to delete

# Returns the operation result or an error

Example:

	response := cc_admin.AdminDeleteVariant(ctx, client, tracer, variant_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cc_admin
operationId: admin_delete_variant
*/
func AdminDeleteVariant(ctx context.Context, c *client.Client, tracer trace.Tracer, variant_id string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "admin_delete_variant", trace.WithAttributes(attribute.String("variant_id", variant_id)))
	defer span.End()

	path := utils.Path("/v2/internal/instances/variants/%s", variant_id)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
