// Code generated by generate-services. DO NOT EDIT.

package cc_admin

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetOrgJenkinsToken **Legacy**: cc-api InternalOrganisationsAPI.java:416 createJenkinsToken()
**Algorithm**:
  - Verify org exists (404)
  - Generate 32-char hex token + secret (16 random bytes each)
  - INSERT into oauth1_tokens with consumer_key='jenkins', member_id=org_id

**Conformity**: YES — Jenkins token creation matches cc-api pattern

GET /v2/internal/organisations/{id}/jenkins-token — create Jenkins token for org.

Source: cc-api InternalOrganisationsAPI.java:413 createJenkinsToken()
Schema: V1__Initial_schema.sql — table oauth1_tokens
Spec: analysis-output/34-ccadmin-analysis.md §Internal API Calls
Behavior: generates new OAuth1 token+secret scoped to org, 404 if org not found.

	401 not internal, 403 for any internal service other than
	gitlab-heptapod-integration-api — legacy checks that flag here and NOT
	isCCAdmin(), so ccadmin is refused too. Bodyless signing base.

Issue: #634, #2018

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation identifier

# Returns the operation result or an error

Example:

	response := cc_admin.GetOrgJenkinsToken(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cc_admin
operationId: get_org_jenkins_token
*/
func GetOrgJenkinsToken(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[models.AdminJenkinsTokenView] {
	ctx, span := tracer.Start(ctx, "get_org_jenkins_token", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/internal/organisations/%s/jenkins-token", id)

	// Make API call
	response := client.Get[models.AdminJenkinsTokenView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
