// Code generated by generate-services. DO NOT EDIT.

package cc_admin

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetAdminAddonDetail **Legacy**: ccadmin AddonController.info() — addon detail page
**Algorithm**:
  - Fetch addon by ID from addons table
  - Determine owner_type from owner_id prefix (user_ vs org_)
  - Fetch owner name/email from users or organisations table
  - Return combined AdminAddonDetailView with zone_id, ownership, system_tags

**Conformity**: YES — addon detail with owner resolution matches ccadmin

GET /v2/cc/addons/{id} — admin addon detail with owner info.

Source: ccadmin AddonController.info() — addon detail page
Spec: analysis-output/34-ccadmin-analysis.md §Addon Management
Behavior:
  - 401 if no valid auth
  - 403 if not almighty token
  - 404 if addon not found
  - 200 with AdminAddonDetailView (addon info + owner name/email)
  - owner_type is "USER" if owner_id starts with "user_", "ORGANISATION" otherwise

Issue: #378

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Addon identifier

# Returns the operation result or an error

Example:

	response := cc_admin.GetAdminAddonDetail(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cc_admin
operationId: get_admin_addon_detail
*/
func GetAdminAddonDetail(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[models.AdminAddonDetailView] {
	ctx, span := tracer.Start(ctx, "get_admin_addon_detail", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/cc/addons/%s", id)

	// Make API call
	response := client.Get[models.AdminAddonDetailView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
