// Code generated by generate-services. DO NOT EDIT.

package cc_admin

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GrantOrgDomain **Legacy**: cc-api InternalOrganisationsAPI.java:224 makeOrganisationOwnDomain()
**Algorithm**:
  - Verify org exists (404)
  - Check if domain_name exists in domains table; if not, INSERT with ownership_type=OWNED
  - INSERT domain_owners ON CONFLICT DO NOTHING (idempotent)

**Conformity**: YES — domain grant with upsert matches cc-api

PUT /v2/internal/organisations/{id}/domains/{domain} — grant a domain to an organisation.

Source: cc-api InternalOrganisationsAPI.java:224 grantDomain()
Spec: analysis-output/34-ccadmin-analysis.md §Internal API Calls
Behavior: 401 not internal (and no cc-admin session), 403 internal without

	access_organisations, 404 org not found, 204 on success (idempotent).
	Bodyless: legacy signs authInternal(crc, null).

Schema: V1__Initial_schema.sql — tables domains (706), domain_owners (695)
Issue: #393, #2018

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation identifier
  - domain: Domain name to grant

# Returns the operation result or an error

Example:

	response := cc_admin.GrantOrgDomain(ctx, client, tracer, id, domain)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cc_admin
operationId: grant_org_domain
*/
func GrantOrgDomain(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, domain string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "grant_org_domain", trace.WithAttributes(attribute.String("id", id), attribute.String("domain", domain)))
	defer span.End()

	path := utils.Path("/v2/internal/organisations/%s/domains/%s", id, domain)

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
