// Code generated by generate-services. DO NOT EDIT.

package cc_admin

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
SetOrgTags **Legacy**: cc-api InternalOrganisationsAPI.java:490 setOrganisationTags()
**Algorithm**:
  - Transaction: DELETE all existing tags, INSERT new tags one by one
  - Idempotent: org existence not checked (no 404)

**Conformity**: YES — delete-then-insert pattern matches cc-api

PUT /v2/internal/organisations/{id}/tags — replace all tags for an organisation.

Source: cc-api InternalOrganisationsAPI.java:490 setOrganisationTags()
Spec: analysis-output/34-ccadmin-analysis.md §Internal API Calls
Behavior: 401 not internal (and no cc-admin session), 403 internal service other

	than ccadmin, 200 on success (org existence not checked — idempotent).
	Body-signed: legacy signs the entity, so the route is layered with
	buffer_internal_auth_payload.

Issue: #388, #2018

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation identifier
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := cc_admin.SetOrgTags(ctx, client, tracer, id, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: cc_admin
operationId: set_org_tags
*/
func SetOrgTags(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, requestBody *models.SetTagsRequest) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "set_org_tags", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/internal/organisations/%s/tags", id)

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
