// Code generated by generate-services. DO NOT EDIT.

package network_group

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getnetworkgroupmember

# Get a Member of a NetworkGroup

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - networkGroupId:
  - memberId:

# Returns the operation result or an error

Example:

	response := network_group.Getnetworkgroupmember(ctx, client, tracer, ownerId, networkGroupId, memberId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: network_group
operationId: getNetworkGroupMember
*/
func Getnetworkgroupmember(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, networkGroupId string, memberId string) client.Response[models.Member] {
	ctx, span := tracer.Start(ctx, "getNetworkGroupMember", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("networkGroupId", networkGroupId), attribute.String("memberId", memberId)))
	defer span.End()

	path := utils.Path("/v4/networkgroups/organisations/%s/networkgroups/%s/members/%s", ownerId, networkGroupId, memberId)

	// Make API call
	response := client.Get[models.Member](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
