// Code generated by generate-services. DO NOT EDIT.

package network_group

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getnetworkgroupstream

# Stream real-time NetworkGroup updates

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - networkGroupId:

# Returns the operation result or an error

Example:

	response := network_group.Getnetworkgroupstream(ctx, client, tracer, ownerId, networkGroupId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: network_group
operationId: getNetworkGroupStream
*/
func Getnetworkgroupstream(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, networkGroupId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "getNetworkGroupStream", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("networkGroupId", networkGroupId)))
	defer span.End()

	path := utils.Path("/v4/networkgroups/organisations/%s/networkgroups/%s/stream", ownerId, networkGroupId)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
