// Code generated by generate-services. DO NOT EDIT.

package network_group

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listnetworkgroups GET /v4/networkgroups/organisations/{owner_id}/networkgroups

Algo Source: ovd NetworkGroupRoutes.scala getNetworkGroups — actor query
against in-memory `ngMap` filtered by `ownerId`, optionally tag-filtered.

Algo Rust: serve from [`crate::cache::NgCache::list_by_owner`] (hydrated from compacted
`networkgroups.events`). Apply tag intersection client-side. No DB, no ZK round-trip.

Source: references/legacy/ovd/modules/networkgroup/routes/NetworkGroupRoutes.scala — getNetworkGroups
Behavior: 200 with the owner's NGs (possibly empty); 403 if not an org member.
Issue: #313, #665, #676, #849, #1127

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Organisation ID
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := network_group.Listnetworkgroups(ctx, client, tracer, ownerId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: network_group
operationId: listNetworkGroups
*/
func Listnetworkgroups(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, opts ...Option) client.Response[[]models.NetworkGroup] {
	ctx, span := tracer.Start(ctx, "listNetworkGroups", trace.WithAttributes(attribute.String("ownerId", ownerId)))
	defer span.End()

	path := utils.Path("/v4/networkgroups/organisations/%s/networkgroups", ownerId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.NetworkGroup](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
