// Code generated by generate-services. DO NOT EDIT.

package loadbalancer_info

// Option defines a functional option for loadbalancer_info operations
type Option func(*Options)

// Options holds query parameters for loadbalancer_info operations
type Options struct{}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}
	return ""
}
