// Code generated by generate-services. DO NOT EDIT.

package products

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getaddonprovider GET /v2/products/addonproviders/{provider_id} — get a specific addon provider.

Source: cc-api ProductsAPI.java getAddonProvider()
Issue: #102

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - provider_id: Addon provider ID

# Returns the operation result or an error

Example:

	response := products.Getaddonprovider(ctx, client, tracer, provider_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: products
operationId: getAddonProvider
*/
func Getaddonprovider(ctx context.Context, c *client.Client, tracer trace.Tracer, provider_id string) client.Response[models.AddonProviderInfoFullView] {
	ctx, span := tracer.Start(ctx, "getAddonProvider", trace.WithAttributes(attribute.String("provider_id", provider_id)))
	defer span.End()

	path := utils.Path("/v2/products/addonproviders/%s", provider_id)

	// Make API call
	response := client.Get[models.AddonProviderInfoFullView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
