// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createserver

# Provision a new server on this region

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - regionId: Region ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := loadbalancer.Createserver(ctx, client, tracer, tenantId, regionId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: createServer
*/
func Createserver(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, regionId string, requestBody *models.RegisterServerInput) client.Response[models.ServerIdResponse] {
	ctx, span := tracer.Start(ctx, "createServer", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("regionId", regionId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/regions/%s/servers", tenantId, regionId)

	// Make API call
	response := client.Post[models.ServerIdResponse](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
