// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getloadbalancerconfiguration

# Get loadbalancer configuration

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - regionId: Region ID
  - loadbalancerId: Loadbalancer ID

# Returns the operation result or an error

Example:

	response := loadbalancer.Getloadbalancerconfiguration(ctx, client, tracer, tenantId, regionId, loadbalancerId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: getLoadbalancerConfiguration
*/
func Getloadbalancerconfiguration(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, regionId string, loadbalancerId string) client.Response[models.LoadbalancerListenersAndClusters] {
	ctx, span := tracer.Start(ctx, "getLoadbalancerConfiguration", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("regionId", regionId), attribute.String("loadbalancerId", loadbalancerId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/regions/%s/loadbalancers/%s/configuration", tenantId, regionId, loadbalancerId)

	// Make API call
	response := client.Get[models.LoadbalancerListenersAndClusters](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
