// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getserver

# Get server

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - regionId: Region ID
  - serverId: Server ID

# Returns the operation result or an error

Example:

	response := loadbalancer.Getserver(ctx, client, tracer, tenantId, regionId, serverId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: getServer
*/
func Getserver(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, regionId string, serverId string) client.Response[models.Server2] {
	ctx, span := tracer.Start(ctx, "getServer", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("regionId", regionId), attribute.String("serverId", serverId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/regions/%s/servers/%s", tenantId, regionId, serverId)

	// Make API call
	response := client.Get[models.Server2](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
