// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listserversfortenant Row 6 — `200 []` on empty.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId: Organisation/tenant ID

# Returns the operation result or an error

Example:

	response := loadbalancer.Listserversfortenant(ctx, client, tracer, tenantId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: listServersForTenant
*/
func Listserversfortenant(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string) client.Response[[]models.ServerView] {
	ctx, span := tracer.Start(ctx, "listServersForTenant", trace.WithAttributes(attribute.String("tenantId", tenantId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/servers", tenantId)

	// Make API call
	response := client.Get[[]models.ServerView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
