// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Unassignloadbalancercluster

# Remove cluster from loadbalancer

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - loadbalancerId: LoadBalancer ID
  - clusterId:

# Returns the operation result or an error

Example:

	response := loadbalancer.Unassignloadbalancercluster(ctx, client, tracer, tenantId, loadbalancerId, clusterId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: unassignLoadBalancerCluster
*/
func Unassignloadbalancercluster(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, loadbalancerId string, clusterId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "unassignLoadBalancerCluster", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("loadbalancerId", loadbalancerId), attribute.String("clusterId", clusterId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/loadbalancers/%s/clusters/%s", tenantId, loadbalancerId, clusterId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
