// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Unassignloadbalancerlistener

# Remove listener from loadbalancer

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - loadbalancerId: Loadbalancer ID
  - stringMaxLength128:

# Returns the operation result or an error

Example:

	response := loadbalancer.Unassignloadbalancerlistener(ctx, client, tracer, tenantId, loadbalancerId, stringMaxLength128)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: unassignLoadbalancerListener
*/
func Unassignloadbalancerlistener(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, loadbalancerId string, stringMaxLength128 string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "unassignLoadbalancerListener", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("loadbalancerId", loadbalancerId), attribute.String("stringMaxLength128", stringMaxLength128)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/loadbalancers/%s/listeners/%s", tenantId, loadbalancerId, stringMaxLength128)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
