// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateserverloadbalancercapacity

# Update server Load Balancer capacity

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - regionId: Region ID
  - serverId: Server ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := loadbalancer.Updateserverloadbalancercapacity(ctx, client, tracer, tenantId, regionId, serverId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: updateServerLoadBalancerCapacity
*/
func Updateserverloadbalancercapacity(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, regionId string, serverId string, requestBody *models.LoadBalancerCapacityInput) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "updateServerLoadBalancerCapacity", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("regionId", regionId), attribute.String("serverId", serverId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/regions/%s/servers/%s/loadbalancer-capacity", tenantId, regionId, serverId)

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
