// Code generated by generate-services. DO NOT EDIT.

package loadbalancer

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateloadbalancerstickyname

# Update loadbalancer sticky session name

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:
  - regionId: Region ID
  - loadbalancerId: Loadbalancer ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := loadbalancer.Updateloadbalancerstickyname(ctx, client, tracer, tenantId, regionId, loadbalancerId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: loadbalancer
operationId: updateLoadbalancerStickyName
*/
func Updateloadbalancerstickyname(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string, regionId string, loadbalancerId string, requestBody *models.StickyNameInput) client.Response[models.LoadBalancerView] {
	ctx, span := tracer.Start(ctx, "updateLoadbalancerStickyName", trace.WithAttributes(attribute.String("tenantId", tenantId), attribute.String("regionId", regionId), attribute.String("loadbalancerId", loadbalancerId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/regions/%s/loadbalancers/%s/sticky-name", tenantId, regionId, loadbalancerId)

	// Make API call
	response := client.Put[models.LoadBalancerView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
