// Code generated by generate-services. DO NOT EDIT.

package zone

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getregion Get a given region.

**Public, and authentication only ever widens** — same three authentication
branches as [`list_zones`], same owner set. The zone is looked up in the ACTIVE
set the caller is allowed to see, so a zone that exists but is granted through
a `zone_access` row answers 200 to a member of a granted organisation and 404 —
exactly as an unknown name does — to everyone else, an anonymous caller
included.

The 404 body is upstream's repository-miss envelope, byte-identical to what
production returns (measured 2026-08-25):
`{"apiRequestId":"request_http_…","code":"clever.core.not-found","context":{"operation":"Find","kind":"Zone","name":"<name>","type":"Operation"},"error":"<name> not found, operation=[Find]"}`.

Source: ovd ZoneActor.scala:120-129 findZone + queries.selectZone
Source: ovd RepositoryProtocols.scala:97 (the NotFound arm)
Source: live capture api.clever-cloud.com /v4/products/zones/zzz-unknown (2026-08-25)
Issues: #313, #1266, #3069

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - zoneName: Zone name (e.g. 'par', 'mtl')
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := zone.Getregion(ctx, client, tracer, zoneName, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: zone
operationId: getRegion
*/
func Getregion(ctx context.Context, c *client.Client, tracer trace.Tracer, zoneName string, opts ...Option) client.Response[models.Region] {
	ctx, span := tracer.Start(ctx, "getRegion", trace.WithAttributes(attribute.String("zoneName", zoneName)))
	defer span.End()

	path := utils.Path("/v4/products/zones/%s", zoneName)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[models.Region](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
