// Code generated by generate-services. DO NOT EDIT.

package zone

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getregion

# Get given region

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - zoneName:
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := zone.Getregion(ctx, client, tracer, zoneName, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: zone
operationId: getRegion
*/
func Getregion(ctx context.Context, c *client.Client, tracer trace.Tracer, zoneName string, opts ...Option) client.Response[models.Region] {
	ctx, span := tracer.Start(ctx, "getRegion", trace.WithAttributes(attribute.String("zoneName", zoneName)))
	defer span.End()

	path := utils.Path("/v4/products/zones/%s", zoneName)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[models.Region](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
