// Code generated by generate-services. DO NOT EDIT.

package self

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Validateemail GET /v2/self/validate_email — validate email from token link.

📥 **Algo Source (Legacy):**
Lookup validationKey in Redis, delete key (one-time), mark email_validated=true in DB, redirect to console
- Legacy note: cc-api SelfAPI.java:126-130 validateEmail() + UsersHelper.java:485-501; Redis key format matches

🔧 **Algo Rust (Implementation):**
- Conformity: faithful
Source: cc-api SelfAPI.java:126-130 validateEmail()
Source: cc-api UsersHelper.java:485-501 validateEmail()
Spec: analysis-output/02-ccapi-analysis.md §Self — validateEmail
Issue: #102

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := self.Validateemail(ctx, client, tracer, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: self
operationId: validateEmail
*/
func Validateemail(ctx context.Context, c *client.Client, tracer trace.Tracer, opts ...Option) client.Response[models.Message] {
	ctx, span := tracer.Start(ctx, "validateEmail")
	defer span.End()

	path := utils.Path("/v2/self/validate_email")

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[models.Message](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
