// Code generated by generate-services. DO NOT EDIT.

package postgresql_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PostgresqlListMigrations `GET /resources/{addonId}/migrations`, `Application.getMigrationsView` —
ALWAYS a 200 array, no addon existence check at all (map trap T5): an
unknown or unparsable `addonId` matches zero rows and answers `[]`.

Source: rewrite/rust/src/migration/controller.rs — get_migrations_view
Issue: #712 (migration slice)

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addon_id: PostgreSQL addon string id (postgresql_<uuid>)

# Returns the operation result or an error

Example:

	response := postgresql_addon.PostgresqlListMigrations(ctx, client, tracer, addon_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql_addon
operationId: postgresql_list_migrations
*/
func PostgresqlListMigrations(ctx context.Context, c *client.Client, tracer trace.Tracer, addon_id string) client.Response[[]models.PostgresqlMigrationConsoleView] {
	ctx, span := tracer.Start(ctx, "postgresql_list_migrations", trace.WithAttributes(attribute.String("addon_id", addon_id)))
	defer span.End()

	path := utils.Path("/v2/providers/postgresql-addon/resources/%s/migrations", addon_id)

	// Make API call
	response := client.Get[[]models.PostgresqlMigrationConsoleView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
