// Code generated by generate-services. DO NOT EDIT.

package postgresql_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PostgresqlPromoteReplicaInternal Source: references/legacy/addon-api/postgresql/app/controllers/Internal.scala:365

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: PostgreSQL addon string id (postgresql_<uuid>)

# Returns the operation result or an error

Example:

	response := postgresql_addon.PostgresqlPromoteReplicaInternal(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql_addon
operationId: postgresql_promote_replica_internal
*/
func PostgresqlPromoteReplicaInternal(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[models.PostgresqlProvisionResponse] {
	ctx, span := tracer.Start(ctx, "postgresql_promote_replica_internal", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/providers/postgresql-addon/internal/%s/promoteReplica", id)

	// Make API call
	response := client.Post[models.PostgresqlProvisionResponse](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
