// Code generated by generate-services. DO NOT EDIT.

package postgresql_addon

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PostgresqlRedeployDedicated `PUT /internal/{id}/redeploy`, `Internal.redeployDedicated`. Same three
gates, deployment insert and vendor `logscollector` call as
[`deploy_instruction`], then the instruction is published on
`deployment.bds.instructions` instead of returned in the body, and the
route answers a bare 204.

See `publish_redeploy_instruction`'s doc comment for the messaging
transport, byte-parity rationale, and the best-effort OVD leg.

Source: rewrite/rust/src/deploy/controller.rs — redeploy_dedicated
Issue: #712, #813 (deploy + messaging slice)

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: PostgreSQL addon string id (postgresql_<uuid>)
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := postgresql_addon.PostgresqlRedeployDedicated(ctx, client, tracer, id, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql_addon
operationId: postgresql_redeploy_dedicated
*/
func PostgresqlRedeployDedicated(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, opts ...Option) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "postgresql_redeploy_dedicated", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/providers/postgresql-addon/internal/%s/redeploy", id)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
