// Code generated by generate-services. DO NOT EDIT.

package postgresql_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PostgresqlBackupSignatureLegacy `GET /internal/{id}/signature/{fn}` — legacy alias of [`backup_signature`],
the filename segment is captured and ignored.

Source: rewrite/rust/src/backup_urls/routes.rs — upload_url_legacy

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: PostgreSQL addon string id (postgresql_<uuid>)
  - fn: Ignored (legacy filename segment)

# Returns the operation result or an error

Example:

	response := postgresql_addon.PostgresqlBackupSignatureLegacy(ctx, client, tracer, id, fn)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql_addon
operationId: postgresql_backup_signature_legacy
*/
func PostgresqlBackupSignatureLegacy(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, fn string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "postgresql_backup_signature_legacy", trace.WithAttributes(attribute.String("id", id), attribute.String("fn", fn)))
	defer span.End()

	path := utils.Path("/v2/providers/postgresql-addon/internal/%s/signature/%s", id, fn)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
