// Code generated by generate-services. DO NOT EDIT.

package postgresql_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PostgresqlInternalGetAddon `GET .../addons/{appId}` — one addon as its console view, or the exact
reference 404 envelope. Shared verbatim with [`v4_get_addon`]: the
reference aliases the two actions, only the guard differs.

Source: rewrite/rust/src/addons/controller.rs — get_addon

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - app_id: Application ID (addon consumer)

# Returns the operation result or an error

Example:

	response := postgresql_addon.PostgresqlInternalGetAddon(ctx, client, tracer, app_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql_addon
operationId: postgresql_internal_get_addon
*/
func PostgresqlInternalGetAddon(ctx context.Context, c *client.Client, tracer trace.Tracer, app_id string) client.Response[models.PostgresqlAddonView] {
	ctx, span := tracer.Start(ctx, "postgresql_internal_get_addon", trace.WithAttributes(attribute.String("app_id", app_id)))
	defer span.End()

	path := utils.Path("/v2/providers/postgresql-addon/internal/addon-providers/postgresql-addon/addons/%s", app_id)

	// Make API call
	response := client.Get[models.PostgresqlAddonView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
