// Code generated by generate-services. DO NOT EDIT.

package postgresql_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PostgresqlDashboardAddReadOnlyUser `POST /dashboard/addReadOnlyUser` — create a read-only role on the
dedicated addon's own database (shared plans refused by the dataplane
layer's own gate, `dataplane::create_read_only_user`), then append it to
`config_read_only_users`.

Source: rewrite/rust/src/dashboard/{routes,dataplane,writes,credentials}.rs — add_read_only_user
Issue: #712 (dashboard slice, part 2)

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := postgresql_addon.PostgresqlDashboardAddReadOnlyUser(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql_addon
operationId: postgresql_dashboard_add_read_only_user
*/
func PostgresqlDashboardAddReadOnlyUser(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[models.PostgresqlProvisionResponse] {
	ctx, span := tracer.Start(ctx, "postgresql_dashboard_add_read_only_user")
	defer span.End()

	path := utils.Path("/v2/providers/postgresql-addon/dashboard/addReadOnlyUser")

	// Make API call
	response := client.Post[models.PostgresqlProvisionResponse](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
