// Code generated by generate-services. DO NOT EDIT.

package postgresql_addon

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PostgresqlReapplyEnv `PUT /internal/{id}/reapplyenv`, `Internal.doSendEnvToCallback`. The
reference maps the vendor future with `_ => Ok("Done")`: the Either is
discarded, so a callback answering 4xx/5xx is STILL a 200 `Done`. Only an
unreachable callback (the failed future) escapes as a bare 500.

Axo addition: unconfigured CC API vendor credentials answer 501 — see
[`update_configuration_on_ccapi`]'s doc comment.

Source: rewrite/rust/src/vendor_config/controller.rs — do_send_env_to_callback
Issue: #712 (vendor_config slice)

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: PostgreSQL addon string id (postgresql_<uuid>)

# Returns the operation result or an error

Example:

	response := postgresql_addon.PostgresqlReapplyEnv(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql_addon
operationId: postgresql_reapply_env
*/
func PostgresqlReapplyEnv(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "postgresql_reapply_env", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/providers/postgresql-addon/internal/%s/reapplyenv", id)

	// Make API call
	response := client.Put[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
