// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteselfapplicationdependencybyappid DELETE /v2/self/applications/{app_id}/dependencies/{dep_id} — remove a dependency.

Legacy: SelfApplicationDependenciesHelper.java:48-51 removeDependency() -> ApplicationDependenciesHelper.java:56-73,143-151
Algorithm: Shape S3, then remove the raw dependency link; no dependency lookup or owner probe runs on DELETE.
Conformity: faithful — a missing link is 404/4004 and success is bodyless 200. Refs #2228

Source: cc-api SelfApplicationDependenciesAPI.java removeDependency()
Issue: #107

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - appId: Application ID
  - dependencyId: Dependency application ID

# Returns the operation result or an error

Example:

	response := applications.Deleteselfapplicationdependencybyappid(ctx, client, tracer, appId, dependencyId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: deleteSelfApplicationDependencyByAppId
*/
func Deleteselfapplicationdependencybyappid(ctx context.Context, c *client.Client, tracer trace.Tracer, appId string, dependencyId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteSelfApplicationDependencyByAppId", trace.WithAttributes(attribute.String("appId", appId), attribute.String("dependencyId", dependencyId)))
	defer span.End()

	path := utils.Path("/v2/self/applications/%s/dependencies/%s", appId, dependencyId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
