// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteorganisationapplication DELETE /v2/organisations/{id}/applications/{app_id} — soft-delete an org application.

Legacy: cc-api ApplicationHelper.java:765 doDeleteApp() + :883 delete()
Algorithm: Auth ADMIN/MANAGER (canRemoveApp); supports Jenkins token auth; stopApp() via BDS, remove TCP/UDP redirections, FTP/P...
Conformity: faithful — all steps replicated; DNS cleanup added

Source: cc-api OrganisationApplicationsAPI.java deleteOrganisationApplication()
The STOP instruction's cause is the calling consumer's name, not a hardcoded
string: legacy's delete() reads token.getConsumerName() and threads it into
_delete() as cause (ApplicationHelper.java:929-932).
Issues: #107, refs #2136

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - appId: Application ID

# Returns the operation result or an error

Example:

	response := applications.Deleteorganisationapplication(ctx, client, tracer, id, appId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: deleteOrganisationApplication
*/
func Deleteorganisationapplication(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, appId string) client.Response[models.Message] {
	ctx, span := tracer.Start(ctx, "deleteOrganisationApplication", trace.WithAttributes(attribute.String("id", id), attribute.String("appId", appId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/applications/%s", id, appId)

	// Make API call
	response := client.Delete[models.Message](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
