// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Editselfapplicationenvbyappidandenvname PUT /v2/self/applications/{app_id}/env/{env_name} — set a single env var.

Accepts `{"value": "..."}` (WannabeValue format, matching cc-api Java).

Source: cc-api SelfApplicationsAPI.java editSelfApplicationEnvByAppIdAndEnvName()
Behavior: cc-api accepts WannabeValue {value: String}, returns ApplicationView
Issue: #2228

Legacy: SelfApplicationsHelper.java:172-175 editApplicationEnv() -> ApplicationHelper.java:3577-3586 editApplicationEnv()
Algorithm: Shape S4b — canAddApp then owner-scoped 403 APPLICATION_BAD_OWNER before the unchanged env write.
Conformity: faithful — personal org_id, S4b errors, response, validation, and messaging. Refs #2228

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - appId: Application ID
  - envName: Env var name
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := applications.Editselfapplicationenvbyappidandenvname(ctx, client, tracer, appId, envName, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: editSelfApplicationEnvByAppIdAndEnvName
*/
func Editselfapplicationenvbyappidandenvname(ctx context.Context, c *client.Client, tracer trace.Tracer, appId string, envName string, requestBody *models.WannabeValue) client.Response[models.ApplicationView] {
	ctx, span := tracer.Start(ctx, "editSelfApplicationEnvByAppIdAndEnvName", trace.WithAttributes(attribute.String("appId", appId), attribute.String("envName", envName)))
	defer span.End()

	path := utils.Path("/v2/self/applications/%s/env/%s", appId, envName)

	// Make API call
	response := client.Put[models.ApplicationView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
