// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getselfapplicationinstancebyappandinstanceid Legacy: SelfApplicationsHelper.java:82-85 getAppInstance() -> ApplicationHelper.java:320-350 getAppInstance()
Algorithm: Shape S1b — scope, canAccessApps, and owner-scoped 404 APPLICATION_BAD_OWNER/4002 before the instance stub.
Conformity: stub — returns 404 always, OVD orchestration integration pending

GET /v2/self/applications/{app_id}/instances/{instance_id} — get specific instance.

Source: cc-api SelfApplicationsAPI.java getInstance()
Phase 1: returns 404 — instance data comes from OVD orchestration.
Issue: #2228

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - appId: Application ID
  - instanceId: Instance ID

# Returns the operation result or an error

Example:

	response := applications.Getselfapplicationinstancebyappandinstanceid(ctx, client, tracer, appId, instanceId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: getSelfApplicationInstanceByAppAndInstanceId
*/
func Getselfapplicationinstancebyappandinstanceid(ctx context.Context, c *client.Client, tracer trace.Tracer, appId string, instanceId string) client.Response[any] {
	ctx, span := tracer.Start(ctx, "getSelfApplicationInstanceByAppAndInstanceId", trace.WithAttributes(attribute.String("appId", appId), attribute.String("instanceId", instanceId)))
	defer span.End()

	path := utils.Path("/v2/self/applications/%s/instances/%s", appId, instanceId)

	// Make API call
	response := client.Get[any](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
