// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getselfvhostbyappid GET /v2/self/applications/{app_id}/vhosts — virtual hosts.

Source: cc-api SelfApplicationsAPI.java getSelfApplicationVhosts()
Issue: #2228

Legacy: SelfApplicationsHelper.java:124-127 getAllVhosts() -> ApplicationHelper.java:732-761 getAllVhosts()
Algorithm: Shape S1 — scope, canAccessApps, and owner-scoped 404 APPLICATION_NOT_FOUND before reading vhosts.
Conformity: faithful — personal org_id, canAccessApps, and owner-scoped 404/4004. Refs #2228

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - appId: Application ID

# Returns the operation result or an error

Example:

	response := applications.Getselfvhostbyappid(ctx, client, tracer, appId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: getSelfVhostByAppId
*/
func Getselfvhostbyappid(ctx context.Context, c *client.Client, tracer trace.Tracer, appId string) client.Response[[]models.VhostView] {
	ctx, span := tracer.Start(ctx, "getSelfVhostByAppId", trace.WithAttributes(attribute.String("appId", appId)))
	defer span.End()

	path := utils.Path("/v2/self/applications/%s/vhosts", appId)

	// Make API call
	response := client.Get[[]models.VhostView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
