// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Linkorganisationapplicationaddon POST /v2/organisations/{id}/applications/{app_id}/addons — link an addon.

Legacy: cc-api ApplicationHelper.java:3421-3477 linkAddon()
Algorithm: Auth (supports Jenkins token + OAuth); canAddApp; Reject if addonId starts with "app_" (FTP guard); Verify addon belo...
Conformity: faithful — ownership check matches Java's orga.hasAddon()

Source: cc-api OrganisationApplicationsAPI.java linkAddonToOrganisationApplication()
Issue: #107

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - appId: Application ID

# Returns the operation result or an error

Example:

	response := applications.Linkorganisationapplicationaddon(ctx, client, tracer, id, appId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: linkOrganisationApplicationAddon
*/
func Linkorganisationapplicationaddon(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, appId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "linkOrganisationApplicationAddon", trace.WithAttributes(attribute.String("id", id), attribute.String("appId", appId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/applications/%s/addons", id, appId)

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
