// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listorganisationapplicationaddonsenvironmentvariables GET /v2/organisations/{id}/applications/{app_id}/addons/env — env of linked addons.

Source: cc-api OrganisationApplicationsAPI.java getOrganisationApplicationLinkedAddonsEnv()
Issue: #107

Legacy: cc-api ApplicationHelper.java:3838-3845 getEnvOfAddonsLinkedToApplication()
Algorithm: Shape S4 — userAllowedInOrgaGuard(canAddApp) then the owner-scoped application lookup answering 404 APPLICATION_NOT_FOUND; For each linked addon, fetch addon env vars (encrypted values decrypted); Return as Link...
Conformity: faithful — shape S4: canAddApp (not a vague org-membership check), 404 APPLICATION_NOT_FOUND on the owner-scoped lookup miss; same query pattern, same LinkedAddonEnvironmentView shape. Refs #2211

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - appId: Application ID

# Returns the operation result or an error

Example:

	response := applications.Listorganisationapplicationaddonsenvironmentvariables(ctx, client, tracer, id, appId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: listOrganisationApplicationAddonsEnvironmentVariables
*/
func Listorganisationapplicationaddonsenvironmentvariables(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, appId string) client.Response[[]models.LinkedAddonEnvironmentView] {
	ctx, span := tracer.Start(ctx, "listOrganisationApplicationAddonsEnvironmentVariables", trace.WithAttributes(attribute.String("id", id), attribute.String("appId", appId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/applications/%s/addons/env", id, appId)

	// Make API call
	response := client.Get[[]models.LinkedAddonEnvironmentView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
