// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Redeployselfapplicationbyappid POST /v2/self/applications/{app_id}/instances — redeploy application.

Legacy: SelfApplicationsHelper.java:100-103 redeploy() -> ApplicationHelper.java:1501-1544 redeploy()
Algorithm: Shape S8, then retain commit resolution, the APPLICATION_NO_DEPLOYS guard (a never-deployed GIT app with no oauth/public-git link and no resolvable commit gets a 400, ApplicationHelper.java:1536-1539), user moderation (runs AFTER the guard, matching legacy's redeploy() -> _redeploy() sequence), the owner-less divert to `_undeploy` (ApplicationHelper.java:1283-1285 — an unresolvable owner short-circuits straight to the undeploy response, before the CPU quota or `bh.startApp` ever run), the CPU quota, then `undeployIfModerated`'s 403 APPLICATION_MODERATED (BdsHelper.java:93-119, reached through bh.startApp at :1318), deployment creation, BDS START, and state changes.
Conformity: enhanced — missing canStartApp, maintenance slots, boot deps

Source: cc-api SelfApplicationsAPI.java redeployApplication()
Behavior: creates deployment record, publishes BDS START instruction, updates app state, and returns the legacy redeploy success envelope with deploymentId.
`deployments.cause` and the BDS instruction's cause are both the calling
consumer's name, not a hardcoded string: legacy's redeploy() reads
token.getConsumerName() once and threads it into _redeploy() as cause
(ApplicationHelper.java:1543).
Issues: #2228, refs #2136, refs #2471, refs #2472, refs #2509, refs #2532, refs #2937

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - appId: Application ID
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := applications.Redeployselfapplicationbyappid(ctx, client, tracer, appId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: redeploySelfApplicationByAppId
*/
func Redeployselfapplicationbyappid(ctx context.Context, c *client.Client, tracer trace.Tracer, appId string, opts ...Option) client.Response[models.DeploySuccessMessage] {
	ctx, span := tracer.Start(ctx, "redeploySelfApplicationByAppId", trace.WithAttributes(attribute.String("appId", appId)))
	defer span.End()

	path := utils.Path("/v2/self/applications/%s/instances", appId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Post[models.DeploySuccessMessage](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
