// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Removeorganisationapplicationtag DELETE /v2/organisations/{id}/applications/{app_id}/tags/{tag} — remove a tag.

Legacy: cc-api OrganisationApplicationTagsAPI.java removeTag()
Algorithm: Auth + org membership; app.removeTag(tag) unconditionally; answer app.getTags()
Conformity: faithful — removes the tag unconditionally and answers the remaining
tags array, the same body GET .../tags returns (#2038).

Source: cc-api OrganisationApplicationsAPI.java removeOrganisationTag()
Source: cc-api ApplicationTagsHelper.java:103 removeTag() -> :55 returnTags()
Issue: #107, #2038

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - appId: Application ID
  - tag: Tag

# Returns the operation result or an error

Example:

	response := applications.Removeorganisationapplicationtag(ctx, client, tracer, id, appId, tag)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: removeOrganisationApplicationTag
*/
func Removeorganisationapplicationtag(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, appId string, tag string) client.Response[[]models.SemanticTag] {
	ctx, span := tracer.Start(ctx, "removeOrganisationApplicationTag", trace.WithAttributes(attribute.String("id", id), attribute.String("appId", appId), attribute.String("tag", tag)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/applications/%s/tags/%s", id, appId, tag)

	// Make API call
	response := client.Delete[[]models.SemanticTag](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
