// Code generated by generate-services. DO NOT EDIT.

package applications

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateorganisationapplication PUT /v2/organisations/{id}/applications/{app_id} — update an org application.

Legacy: cc-api ApplicationHelper.java:2304 edit() -> :2728 save()
Algorithm: Auth canAddApp; Validate zone, name length, instance variant; Update, tri...
Conformity: shape S10 — scope bit and canAddApp both 8103, 403 APPLICATION_BAD_OWNER on the app miss; nothing gates `archived`; rescale-on-edit ported bug-for-bug (refs #2666); still missing zone relocation

The `ApplicationEdition` publish fires only for a CUSTOMER-owned application (ownership
NULL or not SYSTEM), matching save()'s own gate (ApplicationHelper.java:3388).

Source: cc-api OrganisationApplicationsAPI.java updateApplication()
Issue: #107, fixes #2497, refs #2666

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - appId: Application ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := applications.Updateorganisationapplication(ctx, client, tracer, id, appId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: applications
operationId: updateOrganisationApplication
*/
func Updateorganisationapplication(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, appId string, requestBody *models.WannabeApplication) client.Response[models.ApplicationView] {
	ctx, span := tracer.Start(ctx, "updateOrganisationApplication", trace.WithAttributes(attribute.String("id", id), attribute.String("appId", appId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/applications/%s", id, appId)

	// Make API call
	response := client.Put[models.ApplicationView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
