// Code generated by generate-services. DO NOT EDIT.

package kms

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletekms `DELETE /v2/providers/addon-kms/resources/{addon_kms_id}`

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonKmsId: KMS resource identifier (`kms_<uuid>`)

# Returns the operation result or an error

Example:

	response := kms.Deletekms(ctx, client, tracer, addonKmsId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kms
operationId: deleteKms
*/
func Deletekms(ctx context.Context, c *client.Client, tracer trace.Tracer, addonKmsId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteKms", trace.WithAttributes(attribute.String("addonKmsId", addonKmsId)))
	defer span.End()

	path := utils.Path("/v2/providers/addon-kms/resources/%s", addonKmsId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
