// Code generated by generate-services. DO NOT EDIT.

package kms

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
DeleteKmsRegion `DELETE /v4/kms/regions/{region_id}` — refused while any cluster references it (FR-047).

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - region_id: Base region identifier

# Returns the operation result or an error

Example:

	response := kms.DeleteKmsRegion(ctx, client, tracer, region_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kms
operationId: delete_kms_region
*/
func DeleteKmsRegion(ctx context.Context, c *client.Client, tracer trace.Tracer, region_id string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "delete_kms_region", trace.WithAttributes(attribute.String("region_id", region_id)))
	defer span.End()

	path := utils.Path("/v4/kms/regions/%s", region_id)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
