// Code generated by generate-services. DO NOT EDIT.

package kms

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
ListKmsClusters `GET /v4/kms/clusters` — every cluster, optionally one zone's.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := kms.ListKmsClusters(ctx, client, tracer, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kms
operationId: list_kms_clusters
*/
func ListKmsClusters(ctx context.Context, c *client.Client, tracer trace.Tracer, opts ...Option) client.Response[[]models.KmsClusterView] {
	ctx, span := tracer.Start(ctx, "list_kms_clusters")
	defer span.End()

	path := utils.Path("/v4/kms/clusters")

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.KmsClusterView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
