// Code generated by generate-services. DO NOT EDIT.

package keycloak

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletekeycloak DELETE /v2/providers/addon-keycloak/resources/{keycloak_id}

📥 **Algo Source (Legacy):** `markToDelete` (`A:1173`) **soft-deletes**: sets
`deletion_date` and `status = TO_DELETE` on the addon and its child applications.
The row is kept so billing can still invoice the final period. Missing ids are
ignored (`ignoreNotFound`, `Keycloak.scala:56-59`) and still answer 204.

🔧 **Algo Rust (Implementation):** release every cc-api resource first
(applications, DNS, PostgreSQL addon, FS bucket), then `repo::soft_delete` in
one transaction. A teardown failure records `DELETION_ERROR`, leaves the row
live and answers 500 so the delete can be retried. An unknown or
already-deleted id is 404.

Source: references/legacy/ovd/modules/keycloak/src/main/scala/com/clevercloud/keycloak/actors/AddonKeycloakAddonActor.scala:1173
Issues: #313

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonKeycloakId: Keycloak addon id

# Returns the operation result or an error

Example:

	response := keycloak.Deletekeycloak(ctx, client, tracer, addonKeycloakId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: keycloak
operationId: deleteKeycloak
*/
func Deletekeycloak(ctx context.Context, c *client.Client, tracer trace.Tracer, addonKeycloakId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteKeycloak", trace.WithAttributes(attribute.String("addonKeycloakId", addonKeycloakId)))
	defer span.End()

	path := utils.Path("/v2/providers/addon-keycloak/resources/%s", addonKeycloakId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
