// Code generated by generate-services. DO NOT EDIT.

package keycloak

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
GetKeycloakProviderInformation GET /v4/addon-providers/addon-keycloak

Source: ovd AddonKeycloakAddonActor.scala:1317 getProviderInformation
Issue: #313

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := keycloak.GetKeycloakProviderInformation(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: keycloak
operationId: get_keycloak_provider_information
*/
func GetKeycloakProviderInformation(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[models.KeycloakProviderView] {
	ctx, span := tracer.Start(ctx, "get_keycloak_provider_information")
	defer span.End()

	path := utils.Path("/v4/addon-providers/addon-keycloak")

	// Make API call
	response := client.Get[models.KeycloakProviderView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
