// Code generated by generate-services. DO NOT EDIT.

package keycloak

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getkeycloakwithoutownerid GET /v4/addon-providers/addon-keycloak/addons/{keycloak_id}

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonKeycloakId: Keycloak instance ID

# Returns the operation result or an error

Example:

	response := keycloak.Getkeycloakwithoutownerid(ctx, client, tracer, addonKeycloakId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: keycloak
operationId: getKeycloakWithoutOwnerId
*/
func Getkeycloakwithoutownerid(ctx context.Context, c *client.Client, tracer trace.Tracer, addonKeycloakId string) client.Response[models.KeycloakView] {
	ctx, span := tracer.Start(ctx, "getKeycloakWithoutOwnerId", trace.WithAttributes(attribute.String("addonKeycloakId", addonKeycloakId)))
	defer span.End()

	path := utils.Path("/v4/addon-providers/addon-keycloak/addons/%s", addonKeycloakId)

	// Make API call
	response := client.Get[models.KeycloakView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
