// Code generated by generate-services. DO NOT EDIT.

package keycloak

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getallkeycloakconsumption

get all keycloak resources consumptions

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := keycloak.Getallkeycloakconsumption(ctx, client, tracer, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: keycloak
operationId: getAllKeycloakConsumption
*/
func Getallkeycloakconsumption(ctx context.Context, c *client.Client, tracer trace.Tracer, requestBody *models.KeycloakConsumptionQuery) client.Response[[]models.ResourceConsumption] {
	ctx, span := tracer.Start(ctx, "getAllKeycloakConsumption")
	defer span.End()

	path := utils.Path("/v4/keycloak/consumptions")

	// Make API call
	response := client.Post[[]models.ResourceConsumption](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
