// Code generated by generate-services. DO NOT EDIT.

package keycloak

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listallkeycloakconsumption POST /v4/keycloak/consumptions

📥 **Algo Source (Legacy):** `getAllResourceConsumption` (`A:261`) reports every
addon in the window, **including soft-deleted ones** — that is how the final
period gets invoiced.

Source: references/legacy/ovd/modules/keycloak/src/main/scala/com/clevercloud/keycloak/actors/AddonKeycloakAddonActor.scala:261
Issues: #313

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := keycloak.Listallkeycloakconsumption(ctx, client, tracer, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: keycloak
operationId: listAllKeycloakConsumption
*/
func Listallkeycloakconsumption(ctx context.Context, c *client.Client, tracer trace.Tracer, requestBody *models.KeycloakConsumptionQuery) client.Response[[]models.KeycloakConsumptionView] {
	ctx, span := tracer.Start(ctx, "listAllKeycloakConsumption")
	defer span.End()

	path := utils.Path("/v4/keycloak/consumptions")

	// Make API call
	response := client.Post[[]models.KeycloakConsumptionView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
