// Code generated by generate-services. DO NOT EDIT.

package materia_timeseries

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getmateriats GET /v4/addon-providers/addon-ts/addons/{addon_ts_id} — get TS addon view.

Legacy: ovd AddonTSAddonActor.scala:256 getAddonTS
Algorithm:
  - getAddonFromDatabaseTS (selectActiveAddonByID: WHERE id AND deletion_date IS NULL) → 404 if none
  - AddonView { resourceId = addonId, addonId = ccapiAddonId, ownerId, plan, resources.token = readToken }

Conformity: YES

Source: references/legacy/ovd/modules/ts/actors/AddonTSAddonActor.scala:256 getAddonTS
Source: references/legacy/ovd/modules/ts/repositories/AddonTSAddonRepository.scala:59 selectActiveAddonByID
Behavior: active addons only (deletion_date IS NULL); resources.token = read token; 404 if not found.

	Internal/broker only — end-user auth + owner-scoping are cc-api's job (see `docs/authentication.md`).

Issue: #313, #765

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - addonTsId: TS addon ID

# Returns the operation result or an error

Example:

	response := materia_timeseries.Getmateriats(ctx, client, tracer, addonTsId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: materia_timeseries
operationId: getMateriaTS
*/
func Getmateriats(ctx context.Context, c *client.Client, tracer trace.Tracer, addonTsId string) client.Response[models.TsAddonView] {
	ctx, span := tracer.Start(ctx, "getMateriaTS", trace.WithAttributes(attribute.String("addonTsId", addonTsId)))
	defer span.End()

	path := utils.Path("/v4/addon-providers/addon-ts/addons/%s", addonTsId)

	// Make API call
	response := client.Get[models.TsAddonView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
