// Code generated by generate-services. DO NOT EDIT.

package materia_timeseries

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getmateriatsquotalist

get quota list for MateriaTS addons

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := materia_timeseries.Getmateriatsquotalist(ctx, client, tracer, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: materia_timeseries
operationId: getMateriaTSQuotaList
*/
func Getmateriatsquotalist(ctx context.Context, c *client.Client, tracer trace.Tracer, opts ...Option) client.Response[models.QuotaListResponse] {
	ctx, span := tracer.Start(ctx, "getMateriaTSQuotaList")
	defer span.End()

	path := utils.Path("/v4/addon-providers/addon-ts/quotas")

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[models.QuotaListResponse](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
