// Code generated by generate-services. DO NOT EDIT.

package function

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createfunctiondeployment

# Create a  deployment for a function

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - functionId:
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := function.Createfunctiondeployment(ctx, client, tracer, ownerId, functionId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: function
operationId: createFunctionDeployment
*/
func Createfunctiondeployment(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, functionId string, requestBody *models.DeploymentCreateOpts) client.Response[models.DeploymentCreationResponse] {
	ctx, span := tracer.Start(ctx, "createFunctionDeployment", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("functionId", functionId)))
	defer span.End()

	path := utils.Path("/v4/functions/organisations/%s/functions/%s/deployments", ownerId, functionId)

	// Make API call
	response := client.Post[models.DeploymentCreationResponse](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
