// Code generated by generate-services. DO NOT EDIT.

package function

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getfunctiondeployment

# Get a deployment

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - functionId:
  - deploymentId:

# Returns the operation result or an error

Example:

	response := function.Getfunctiondeployment(ctx, client, tracer, ownerId, functionId, deploymentId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: function
operationId: getFunctionDeployment
*/
func Getfunctiondeployment(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, functionId string, deploymentId string) client.Response[models.Deployment1] {
	ctx, span := tracer.Start(ctx, "getFunctionDeployment", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("functionId", functionId), attribute.String("deploymentId", deploymentId)))
	defer span.End()

	path := utils.Path("/v4/functions/organisations/%s/functions/%s/deployments/%s", ownerId, functionId, deploymentId)

	// Make API call
	response := client.Get[models.Deployment1](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
