// Code generated by generate-services. DO NOT EDIT.

package vendorapi

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listapps GET /v2/vendor/apps — list all addons provisioned by this provider.

Source: cc-api AddonVendorAPI.java:108-116 listApps() → checkAuth()
Source: cc-api AddonVendorAPIHelper.java:132-177 listApps()
Provider is identified by HTTP Basic auth (provider_id:password).
Issue: #105
Algorithm: Authenticate the provider via vendor Basic auth (extractAuthData+checkAuth), then list addons WHERE provider_id = provider.id and enrich each.
Legacy: cc-api uses provider Basic auth, NOT an end-user OAuth1 token; a non-Basic Authorization header (the OAuth1 header api-bridge re-signs) makes extractAuthData throw → 500.
Conformity: faithful — non-provider caller reproduces cc-api production 500.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := vendorapi.Listapps(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: vendor
operationId: listApps
*/
func Listapps(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[[]models.VendorAppView] {
	ctx, span := tracer.Start(ctx, "listApps")
	defer span.End()

	path := utils.Path("/v2/vendor/apps")

	// Make API call
	response := client.Get[[]models.VendorAppView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
