// Code generated by generate-services. DO NOT EDIT.

package pulsar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deletepulsarv2 DELETE /v2/providers/addon-pulsar/resources/{pulsar_id} — deprovision a Pulsar addon.

**Legacy**: ovd PulsarController.scala:178 deletePulsarV2ServerEndpoint()
**Algorithm**:
  - Delegates to PulsarProvisioningService.markToDelete (line 147)
  - UPDATE status=TO_DELETE + ask_for_deletion_date=NOW, then SELECT to return view
  - Internal endpoint (Basic Auth), no ownership check

**Conformity**: YES

Source: references/legacy/ovd/modules/pulsar/controller/PulsarController.scala deletePulsarV2ServerEndpoint
Source: references/legacy/ovd/modules/pulsar/api/routes.scala deletePulsarV2
Behavior: marks addon as TO_DELETE with ask_for_deletion_date. Background cleanup job

	handles actual Pulsar tenant/namespace deletion once the addon's
	grace period is up — a year for access and audit logs, three days
	for the rest (`cleanup::LONG_RETENTION_DAYS`).
	Returns the current Pulsar view (Scala returns Ok with body).

Issue: #8

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - pulsarId: Pulsar addon ID

# Returns the operation result or an error

Example:

	response := pulsar.Deletepulsarv2(ctx, client, tracer, pulsarId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: pulsar
operationId: deletePulsarV2
*/
func Deletepulsarv2(ctx context.Context, c *client.Client, tracer trace.Tracer, pulsarId string) client.Response[models.Pulsar] {
	ctx, span := tracer.Start(ctx, "deletePulsarV2", trace.WithAttributes(attribute.String("pulsarId", pulsarId)))
	defer span.End()

	path := utils.Path("/v2/providers/addon-pulsar/resources/%s", pulsarId)

	// Make API call
	response := client.Delete[models.Pulsar](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
