// Code generated by generate-services. DO NOT EDIT.

package pulsar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getpulsarresourceinfo

# Get pulsar resource information

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - resourceId:

# Returns the operation result or an error

Example:

	response := pulsar.Getpulsarresourceinfo(ctx, client, tracer, ownerId, resourceId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: pulsar
operationId: getPulsarResourceInfo
*/
func Getpulsarresourceinfo(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, resourceId string) client.Response[models.ResourceInfo] {
	ctx, span := tracer.Start(ctx, "getPulsarResourceInfo", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("resourceId", resourceId)))
	defer span.End()

	path := utils.Path("/v4/pulsar/organisations/%s/pulsar/resources/%s", ownerId, resourceId)

	// Make API call
	response := client.Get[models.ResourceInfo](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
