// Code generated by generate-services. DO NOT EDIT.

package pulsar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listoutboxmessages

# Get all Outbox messages

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - tenantId:

# Returns the operation result or an error

Example:

	response := pulsar.Listoutboxmessages(ctx, client, tracer, tenantId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: pulsar
operationId: listOutboxMessages
*/
func Listoutboxmessages(ctx context.Context, c *client.Client, tracer trace.Tracer, tenantId string) client.Response[[]models.LoadbalanceroutboxT] {
	ctx, span := tracer.Start(ctx, "listOutboxMessages", trace.WithAttributes(attribute.String("tenantId", tenantId)))
	defer span.End()

	path := utils.Path("/v4/loadbalancers/organisations/%s/pulsar", tenantId)

	// Make API call
	response := client.Get[[]models.LoadbalanceroutboxT](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
