// Code generated by generate-services. DO NOT EDIT.

package pulsar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listpulsarclusters

# List all Pulsar clusters

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := pulsar.Listpulsarclusters(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: pulsar
operationId: listPulsarClusters
*/
func Listpulsarclusters(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[[]models.PulsarCluster] {
	ctx, span := tracer.Start(ctx, "listPulsarClusters")
	defer span.End()

	path := utils.Path("/v4/addon-providers/addon-pulsar/clusters")

	// Make API call
	response := client.Get[[]models.PulsarCluster](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
