// Code generated by generate-services. DO NOT EDIT.

package pulsar

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updatepulsarcluster

# Update Pulsar cluster

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - clusterId:
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := pulsar.Updatepulsarcluster(ctx, client, tracer, clusterId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: pulsar
operationId: updatePulsarCluster
*/
func Updatepulsarcluster(ctx context.Context, c *client.Client, tracer trace.Tracer, clusterId string, requestBody *models.WannabePulsarCluster) client.Response[models.PulsarCluster] {
	ctx, span := tracer.Start(ctx, "updatePulsarCluster", trace.WithAttributes(attribute.String("clusterId", clusterId)))
	defer span.End()

	path := utils.Path("/v4/addon-providers/addon-pulsar/clusters/%s", clusterId)

	// Make API call
	response := client.Put[models.PulsarCluster](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
