// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createorganisationconsumer POST /v2/organisations/{id}/consumers — create a new OAuth1 consumer for an org.

Source: cc-api OrganisationConsumersAPI.java createConsumer()
Generates a random key + secret. Persists the validated caller-supplied
rights (refs #1181); any right the caller did not send stays `false`,
matching the legacy default-false `CleverCloudOAuthRights()` +
`updateWith()` flow. `almighty` is never granted to the consumer
(`validateOAuthRight(..., false)`; refs #930 / F-021).
Issue: #103, #930, #1181

📥 **Algo Source (Legacy):**
Verify org membership (ADMIN/MANAGER/DEVELOPER via canAddApp),
generate UUID-based key (ck_) and secret (cs_), validate the rights map,
then `new CleverCloudOAuthRights()` (all false) flipped by
`updateWith()` for each caller-sent right, insert oauth1_consumers.
  - Legacy note: cc-api OrganisationConsumersAPI.java createConsumer() ->
    OAuth1ConsumersHelper.createOAuth1Consumer() ->
    `new CleverCloudOAuth1Consumer(c, _orga.right().getInfo())` whose
    constructor calls `updateWith(c)` to apply the validated rights map.

🔧 **Algo Rust (Implementation):**
  - ADMIN-only RBAC gate (refs #921, #922) on top of legacy validation:
    minting a consumer is administrative. Rights are whatever the caller
    validly requests; `almighty` is never granted (no escalation, F-021).
  - 400 OAUTH1_CONSUMER on missing/empty/unknown rights keys (refs #1181).
  - Conformity: faithful.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := organisations.Createorganisationconsumer(ctx, client, tracer, id, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: createOrganisationConsumer
*/
func Createorganisationconsumer(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, requestBody *models.WannabeOAuth1Consumer) client.Response[models.OAuth1ConsumerView] {
	ctx, span := tracer.Start(ctx, "createOrganisationConsumer", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/consumers", id)

	// Make API call
	response := client.Post[models.OAuth1ConsumerView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
