// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteprovider DELETE /v2/organisations/{id}/addonproviders/{provider_id} — soft-delete addon provider.

Source: cc-api OrganisationAddonProviderAPI.java deleteAddonProvider()
Issue: #103

📥 **Algo Source (Legacy):**
Verify ADMIN role + ownership, SET deletiondate = NOW().
- Legacy note: cc-api OrganisationAddonProviderAPI.java deleteAddonProvider()

🔧 **Algo Rust (Implementation):**
- Conformity: faithful

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - providerId: Provider ID

# Returns the operation result or an error

Example:

	response := organisations.Deleteprovider(ctx, client, tracer, id, providerId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: deleteProvider
*/
func Deleteprovider(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, providerId string) client.Response[models.Message] {
	ctx, span := tracer.Start(ctx, "deleteProvider", trace.WithAttributes(attribute.String("id", id), attribute.String("providerId", providerId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/addonproviders/%s", id, providerId)

	// Make API call
	response := client.Delete[models.Message](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
