// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteorganisationconsumer DELETE /v2/organisations/{id}/consumers/{key} — soft-delete a consumer.

Source: cc-api OrganisationConsumersAPI.java deleteConsumer()
Soft delete: sets deletion_date = NOW()
Issue: #103

📥 **Algo Source (Legacy):**
SET deletion_date = NOW(); 404 if not found.
- Legacy note: cc-api OrganisationConsumersAPI.java deleteConsumer()

🔧 **Algo Rust (Implementation):**
- Conformity: faithful

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - key: Consumer key

# Returns the operation result or an error

Example:

	response := organisations.Deleteorganisationconsumer(ctx, client, tracer, id, key)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: deleteOrganisationConsumer
*/
func Deleteorganisationconsumer(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, key string) client.Response[models.Message] {
	ctx, span := tracer.Start(ctx, "deleteOrganisationConsumer", trace.WithAttributes(attribute.String("id", id), attribute.String("key", key)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/consumers/%s", id, key)

	// Make API call
	response := client.Delete[models.Message](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
