// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getproviderplans GET /v2/organisations/{id}/addonproviders/{provider_id}/plans — list plans.

Source: cc-api OrganisationAddonProviderAPI.java getPlans()
Issue: #103

📥 **Algo Source (Legacy):**
Verify membership + ownership, SELECT from addon_plan ORDER BY price.
- Legacy note: cc-api OrganisationAddonProviderAPI.java getPlans()

🔧 **Algo Rust (Implementation):**
- Conformity: faithful

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - providerId: Provider ID

# Returns the operation result or an error

Example:

	response := organisations.Getproviderplans(ctx, client, tracer, id, providerId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: getProviderPlans
*/
func Getproviderplans(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, providerId string) client.Response[[]models.AddonPlanView] {
	ctx, span := tracer.Start(ctx, "getProviderPlans", trace.WithAttributes(attribute.String("id", id), attribute.String("providerId", providerId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/addonproviders/%s/plans", id, providerId)

	// Make API call
	response := client.Get[[]models.AddonPlanView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
