// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getservicetoken GET /v2/organisations/{id}/service-tokens/{token_id} — get a specific service token.

Source: cc-api OrganisationServiceTokensAPI.java:89 getServiceToken()
Source: cc-api ServiceTokenHelper.java:199 get()
Behavior: returns a single service token by ID (proxied from token API).
Issue: #855

📥 **Algo Source (Legacy):**
1. Auth: check caller is member of org with manage_organisations_services
2. Forward GET to token API /v4/tenants/{tenantId}/tokens/{tokenId}
3. Return token API response (200 with token details)

🔧 **Algo Rust (Implementation):**
Faithful reproduction.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - tokenId: Service token ID

# Returns the operation result or an error

Example:

	response := organisations.Getservicetoken(ctx, client, tracer, id, tokenId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: getServiceToken
*/
func Getservicetoken(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, tokenId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "getServiceToken", trace.WithAttributes(attribute.String("id", id), attribute.String("tokenId", tokenId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/service-tokens/%s", id, tokenId)

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
