// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listservicetokens GET /v2/organisations/{id}/service-tokens — list service tokens.

Source: cc-api OrganisationServiceTokensAPI.java:69 listServiceTokens()
Source: cc-api ServiceTokenHelper.java:180 list()
Behavior: returns list of service tokens for the organisation (proxied from token API).

	Returns 502 if token API communication fails.

Issue: #855

📥 **Algo Source (Legacy):**
1. Auth: check caller is member of org with manage_organisations_services
2. Build URL with optional limit/offset query params
3. Forward GET to token API /v4/tenants/{tenantId}/tokens
4. Return token API response (200 with list)

🔧 **Algo Rust (Implementation):**
Faithful reproduction. Uses reqwest to call local token API.

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := organisations.Listservicetokens(ctx, client, tracer, id, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: listServiceTokens
*/
func Listservicetokens(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, opts ...Option) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "listServiceTokens", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/service-tokens", id)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
