// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listorganisations GET /v2/organisations — list organisations the user belongs to.

Source: cc-api OrganisationsAPI.java GET /organisations
cc-api filters by user parameter, but most commonly returns orgs for the authenticated user.
Issue: #103

📥 **Algo Source (Legacy):**
Check canAccessOrganisations permission, Join organisations + owner_info + organisation_members WHERE user_id, state=ACTIVE
- Legacy note: cc-api OrganisationsAPI.java:62 getUserOrganisationss() -> OrganisationHelper.java:95 getOrgasForUser()

🔧 **Algo Rust (Implementation):**
- Conformity: faithful

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := organisations.Listorganisations(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: listOrganisations
*/
func Listorganisations(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[[]models.OrganisationView] {
	ctx, span := tracer.Start(ctx, "listOrganisations")
	defer span.End()

	path := utils.Path("/v2/organisations")

	// Make API call
	response := client.Get[[]models.OrganisationView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
