// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"fmt"
	"net/url"
	"strings"
)

// Option defines a functional option for organisations operations
type Option func(*Options)

// Options holds query parameters for organisations operations
type Options struct {
	Invitationkey *string `url:"invitationKey,omitempty"`
	Limit         *int64  `url:"limit,omitempty"`
	Offset        *any    `url:"offset,omitempty"`
}

// WithInvitationkey sets the invitationKey query parameter
func WithInvitationkey(invitationKey string) Option {
	return func(o *Options) {
		o.Invitationkey = &invitationKey
	}
}

// WithLimit sets the limit query parameter
func WithLimit(limit int64) Option {
	return func(o *Options) {
		o.Limit = &limit
	}
}

// WithOffset sets the offset query parameter
func WithOffset(offset any) Option {
	return func(o *Options) {
		o.Offset = &offset
	}
}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}

	var params []string
	if options.Invitationkey != nil {
		params = append(params, fmt.Sprintf("invitationKey=%s", url.QueryEscape(*options.Invitationkey)))
	}
	if options.Limit != nil {
		params = append(params, fmt.Sprintf("limit=%d", *options.Limit))
	}
	if options.Offset != nil {
		params = append(params, fmt.Sprintf("offset=%v", *options.Offset))
	}

	if len(params) == 0 {
		return ""
	}
	return strings.Join(params, "&")
}
