// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateproviderinfos PUT /v2/organisations/{id}/addonproviders/{provider_id} — update addon provider.

Source: cc-api OrganisationAddonProviderAPI.java updateAddonProvider()
Issue: #103

📥 **Algo Source (Legacy):**
Verify ADMIN role + ownership, update addon_provider_infos fields.
- Legacy note: cc-api OrganisationAddonProviderAPI.java updateAddonProvider()

🔧 **Algo Rust (Implementation):**
- Conformity: faithful

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - providerId: Provider ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := organisations.Updateproviderinfos(ctx, client, tracer, id, providerId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: updateProviderInfos
*/
func Updateproviderinfos(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, providerId string, requestBody *models.WannabeAddonProviderInfos) client.Response[models.AddonProviderEmbeddedView] {
	ctx, span := tracer.Start(ctx, "updateProviderInfos", trace.WithAttributes(attribute.String("id", id), attribute.String("providerId", providerId)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/addonproviders/%s", id, providerId)

	// Make API call
	response := client.Put[models.AddonProviderEmbeddedView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
