// Code generated by generate-services. DO NOT EDIT.

package organisations

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateorganisationconsumer PUT /v2/organisations/{id}/consumers/{key} — update a consumer.

Source: cc-api OrganisationConsumersAPI.java updateConsumer()
Issue: #103

📥 **Algo Source (Legacy):**
Update name/description/url/picture/base_url; 404 if not found.
- Legacy note: cc-api OrganisationConsumersAPI.java updateConsumer()

🔧 **Algo Rust (Implementation):**
- Validate + persist caller-supplied rights (refs #1181); 400 OAUTH1_CONSUMER on bad rights.
- Conformity: faithful

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - key: Consumer key
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := organisations.Updateorganisationconsumer(ctx, client, tracer, id, key, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: organisations
operationId: updateOrganisationConsumer
*/
func Updateorganisationconsumer(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, key string, requestBody *models.WannabeOAuth1Consumer) client.Response[models.OAuth1ConsumerView] {
	ctx, span := tracer.Start(ctx, "updateOrganisationConsumer", trace.WithAttributes(attribute.String("id", id), attribute.String("key", key)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/consumers/%s", id, key)

	// Make API call
	response := client.Put[models.OAuth1ConsumerView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
