// Code generated by generate-services. DO NOT EDIT.

package kubernetes

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createcluster

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := kubernetes.Createcluster(ctx, client, tracer, ownerId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kubernetes
operationId: createCluster
*/
func Createcluster(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, requestBody *models.ClusterCreationPayload) client.Response[models.ClusterView] {
	ctx, span := tracer.Start(ctx, "createCluster", trace.WithAttributes(attribute.String("ownerId", ownerId)))
	defer span.End()

	path := utils.Path("/v4/kubernetes/organisations/%s/clusters", ownerId)

	// Make API call
	response := client.Post[models.ClusterView](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
