// Code generated by generate-services. DO NOT EDIT.

package kubernetes

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getkuberneteshealth `GET /v4/kubernetes/health` — the cached, sanitized aggregate report; the thin
documented wrapper over [`api_health::aggregate_health`] (which carries the algorithm
— cache → sanitize → 200/503).

Doc carrier for `getKubernetesHealth`; the framework serves the route — do not mount.

200 when every constraint is HEALTHY, 503 otherwise. `message` and `duration` are
sanitized away on both, so an unauthenticated prober learns constraint names and
statuses only.

Issues: #3008

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := kubernetes.Getkuberneteshealth(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kubernetes
operationId: getKubernetesHealth
*/
func Getkuberneteshealth(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[models.ApiHealthReport] {
	ctx, span := tracer.Start(ctx, "getKubernetesHealth")
	defer span.End()

	path := utils.Path("/v4/kubernetes/health")

	// Make API call
	response := client.Get[models.ApiHealthReport](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
