// Code generated by generate-services. DO NOT EDIT.

package kubernetes

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getcluster

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - clusterId: A Kubernetes cluster identifier

# Returns the operation result or an error

Example:

	response := kubernetes.Getcluster(ctx, client, tracer, ownerId, clusterId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kubernetes
operationId: getCluster
*/
func Getcluster(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, clusterId string) client.Response[models.ClusterView] {
	ctx, span := tracer.Start(ctx, "getCluster", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("clusterId", clusterId)))
	defer span.End()

	path := utils.Path("/v4/kubernetes/organisations/%s/clusters/%s", ownerId, clusterId)

	// Make API call
	response := client.Get[models.ClusterView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
