// Code generated by generate-services. DO NOT EDIT.

package kubernetes

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getdeploymentprofile GET /v4/kubernetes/admin/deployment-profiles/{location_id}

📥 **Algo Source (Legacy):**
Return one location's deployment profile.
- `requireBasicAuth` → 403 otherwise
- `repository.findByLocationId(locationId)`; absent → 404 `DeploymentProfileError`
- `DeploymentProfileView.from` (secrets redacted)
- Source: ovd DeploymentProfileController.scala:78-97

🔧 **Algo Rust (Implementation):**
  - `AdminAccess` extractor → 403; `validate_location_id` → 400 on a malformed id
    (OVD's tapir `path[LocationId]` codec rejects it before the handler)
  - `find_by_location_id` → 404 when absent
  - Return the redacted view with 200 OK

Source: ovd controllers/DeploymentProfileController.scala:78-97
Schema: deployment_profile (V2.18.0__create_deployment_profile_table.sql)
Issue: #1625

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - locationId: Location id (location_<uuid>)

# Returns the operation result or an error

Example:

	response := kubernetes.Getdeploymentprofile(ctx, client, tracer, locationId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kubernetes
operationId: getDeploymentProfile
*/
func Getdeploymentprofile(ctx context.Context, c *client.Client, tracer trace.Tracer, locationId string) client.Response[models.DeploymentProfile] {
	ctx, span := tracer.Start(ctx, "getDeploymentProfile", trace.WithAttributes(attribute.String("locationId", locationId)))
	defer span.End()

	path := utils.Path("/v4/kubernetes/admin/deployment-profiles/%s", locationId)

	// Make API call
	response := client.Get[models.DeploymentProfile](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
