// Code generated by generate-services. DO NOT EDIT.

package kubernetes

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
K8sDeleteNodePool **Legacy**: ovd NodeGroupController.scala:116 delete()
**Algorithm**:
  - Sets flag_for_deletion=true via updateOneFlagForDeletion
  - Returns view with TERMINATING status; actual node cleanup is async

**Conformity**: YES

DELETE /v4/kubernetes/organisations/{owner_id}/clusters/{cluster_id}/node-pools/{pool_id} — delete a node pool.

Source: references/legacy/ovd/modules/kubernetes/controllers/NodeGroupController.scala — delete
Source: references/legacy/ovd/modules/kubernetes/repositories/NodeGroupRepository.scala — updateOneFlagForDeletion
Behavior: marks node group for deletion (flag_for_deletion=true). Returns view with

	TERMINATING status. Actual node cleanup is async.

Issue: #8

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - owner_id: Owner (org) ID
  - cluster_id: Cluster ID
  - pool_id: Node pool ID

# Returns the operation result or an error

Example:

	response := kubernetes.K8sDeleteNodePool(ctx, client, tracer, owner_id, cluster_id, pool_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kubernetes
operationId: k8s_delete_node_pool
*/
func K8sDeleteNodePool(ctx context.Context, c *client.Client, tracer trace.Tracer, owner_id string, cluster_id string, pool_id string) client.Response[models.NodeGroupView] {
	ctx, span := tracer.Start(ctx, "k8s_delete_node_pool", trace.WithAttributes(attribute.String("owner_id", owner_id), attribute.String("cluster_id", cluster_id), attribute.String("pool_id", pool_id)))
	defer span.End()

	path := utils.Path("/v4/kubernetes/organisations/%s/clusters/%s/node-pools/%s", owner_id, cluster_id, pool_id)

	// Make API call
	response := client.Delete[models.NodeGroupView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
