// Code generated by generate-services. DO NOT EDIT.

package kubernetes

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listclusterdeploymentevents

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - clusterId: A Kubernetes cluster identifier
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := kubernetes.Listclusterdeploymentevents(ctx, client, tracer, ownerId, clusterId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: kubernetes
operationId: listClusterDeploymentEvents
*/
func Listclusterdeploymentevents(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, clusterId string, opts ...Option) client.Response[[]models.DeploymentEvent] {
	ctx, span := tracer.Start(ctx, "listClusterDeploymentEvents", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("clusterId", clusterId)))
	defer span.End()

	path := utils.Path("/v4/kubernetes/organisations/%s/clusters/%s/deployment-events", ownerId, clusterId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.DeploymentEvent](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
