// Code generated by generate-services. DO NOT EDIT.

package kubernetes

import (
	"fmt"
	"net/url"
	"strings"
)

// Option defines a functional option for kubernetes operations
type Option func(*Options)

// Options holds query parameters for kubernetes operations
type Options struct {
	Resourceid *[]string `url:"resourceId,omitempty"`
	Since      *string   `url:"since,omitempty"`
	Status     *[]string `url:"status,omitempty"`
	Typeparam  *string   `url:"typeParam,omitempty"`
	Until      *string   `url:"until,omitempty"`
}

// WithResourceid sets the resourceId query parameter
func WithResourceid(resourceId []string) Option {
	return func(o *Options) {
		o.Resourceid = &resourceId
	}
}

// WithSince sets the since query parameter
func WithSince(since string) Option {
	return func(o *Options) {
		o.Since = &since
	}
}

// WithStatus sets the status query parameter
func WithStatus(status []string) Option {
	return func(o *Options) {
		o.Status = &status
	}
}

// WithTypeparam sets the typeParam query parameter
func WithTypeparam(typeParam string) Option {
	return func(o *Options) {
		o.Typeparam = &typeParam
	}
}

// WithUntil sets the until query parameter
func WithUntil(until string) Option {
	return func(o *Options) {
		o.Until = &until
	}
}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}

	var params []string
	if options.Resourceid != nil {
		params = append(params, fmt.Sprintf("resourceId=%v", *options.Resourceid))
	}
	if options.Since != nil {
		params = append(params, fmt.Sprintf("since=%s", url.QueryEscape(*options.Since)))
	}
	if options.Status != nil {
		params = append(params, fmt.Sprintf("status=%v", *options.Status))
	}
	if options.Typeparam != nil {
		params = append(params, fmt.Sprintf("typeParam=%s", url.QueryEscape(*options.Typeparam)))
	}
	if options.Until != nil {
		params = append(params, fmt.Sprintf("until=%s", url.QueryEscape(*options.Until)))
	}

	if len(params) == 0 {
		return ""
	}
	return strings.Join(params, "&")
}
