// Code generated by generate-services. DO NOT EDIT.

package users

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getuser GET /v2/users/{user_id} — get a user's public profile.

📥 **Algo Source (Legacy):**
Return the public profile of a user by ID.
- Auth via authAllowingInternal(crc, "user_id") — caller must be self, admin, or internal
- Java checks token.canAccessPersonalInformation() and current.isAdmin()
- If unauthorized: return 400 Bad Request (not 403)
- Query: SELECT from users LEFT JOIN owner_info for avatar_url
- Return 404 if user not found
- Source: cc-api UsersAPI.java:67 getUser(), UsersHelper.java:178-185

🔧 **Algo Rust (Implementation):**
  - Extract caller user_id from OAuth1 token
  - Gate exactly like cc-api UsersHelper.get: allowed only for almighty (admin)
    or internal/notification-API tokens — NOT for a plain self token. The
    denial is returned BEFORE any DB lookup of the target user, so it fires
    identically for existing and non-existing ids.
  - If not allowed: return 400 + USER_DATA_ACCESS (id 7301), not 404.
  - SELECT u.id, u.name, oi.avatar_url, u.lang FROM users u LEFT JOIN owner_info oi
  - Return PublicUserView or 404 (only reachable by admin/internal callers)

Source: cc-api UsersHelper.java:177-191 get() — canAccessPersonalInformation/isAdmin gate
Source: cc-api Errors.java:219 USER_DATA_ACCESS(7301)
Schema: users (id, name, lang), owner_info (id, avatar_url)
Issue: #109, #1187

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: User ID

# Returns the operation result or an error

Example:

	response := users.Getuser(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: users
operationId: getUser
*/
func Getuser(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[models.PublicUserView] {
	ctx, span := tracer.Start(ctx, "getUser", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/users/%s", id)

	// Make API call
	response := client.Get[models.PublicUserView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
