// Code generated by generate-services. DO NOT EDIT.

package postgresql

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteuser **Legacy**: ovd users.scala:122 deleteUser()
**Algorithm**:
  - Verify addon, fetch user from metadata
  - DROP USER on addon DB (terminate sessions, reassign owned, drop owned, drop user)
  - Soft-delete user in metadata by setting deletion_date

**Conformity**: YES

DELETE /v4/postgresql/organisations/{ownerId}/postgresql/{postgreSQLId}/users/{userId}

Source: ovd PostgreSQLUserPrivilegeRepository.scala — deleteUser (soft delete via deletion_date)
Source: ovd PostgreSQLAccessController.scala — deleteUser (DROP USER on addon DB)
Behavior: soft-deletes user by setting deletion_date
Issue: #646

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - postgreSQLId: PostgreSQL addon ID
  - pgUserId: PostgreSQL user ID

# Returns the operation result or an error

Example:

	response := postgresql.Deleteuser(ctx, client, tracer, ownerId, postgreSQLId, pgUserId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql
operationId: deleteUser
*/
func Deleteuser(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, postgreSQLId string, pgUserId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteUser", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("postgreSQLId", postgreSQLId), attribute.String("pgUserId", pgUserId)))
	defer span.End()

	path := utils.Path("/v4/postgresql/organisations/%s/postgresql/%s/users/%s", ownerId, postgreSQLId, pgUserId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
