// Code generated by generate-services. DO NOT EDIT.

package postgresql

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listdatabasesprivileges **Legacy**: ovd users.scala:52 getDatabasesPrivileges()
**Algorithm**:
  - Verify addon, SELECT privileges with dynamic WHERE (oid, userId filters)

**Conformity**: YES

GET .../users/privileges/databases — list all database-level privileges.

Source: ovd PostgreSQLUserPrivilegeRepository.scala — selectDatabasesPrivileges
Issue: #646

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - postgreSQLId: PostgreSQL addon ID
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := postgresql.Listdatabasesprivileges(ctx, client, tracer, ownerId, postgreSQLId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql
operationId: listDatabasesPrivileges
*/
func Listdatabasesprivileges(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, postgreSQLId string, opts ...Option) client.Response[[]models.PgDatabasePrivilegesView] {
	ctx, span := tracer.Start(ctx, "listDatabasesPrivileges", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("postgreSQLId", postgreSQLId)))
	defer span.End()

	path := utils.Path("/v4/postgresql/organisations/%s/postgresql/%s/users/privileges/databases", ownerId, postgreSQLId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.PgDatabasePrivilegesView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
