// Code generated by generate-services. DO NOT EDIT.

package postgresql

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listdatabases **Legacy**: ovd databases.scala:30 getAllDatabases()
**Algorithm**:
  - Verify addon ownership, SELECT all non-deleted databases for addon

**Conformity**: YES

GET /v4/postgresql/organisations/{ownerId}/postgresql/{postgreSQLId}/databases

Source: ovd PostgreSQLDatabaseRepository.scala — selectActiveAddonDatabases
Source: ovd PostgreSQLDatabaseService.scala — getPostgreSQLDatabases
Behavior: returns all non-deleted databases for the given addon
Issue: #646

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - postgreSQLId: PostgreSQL addon ID

# Returns the operation result or an error

Example:

	response := postgresql.Listdatabases(ctx, client, tracer, ownerId, postgreSQLId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql
operationId: listDatabases
*/
func Listdatabases(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, postgreSQLId string) client.Response[[]models.PostgreSQLDatabase] {
	ctx, span := tracer.Start(ctx, "listDatabases", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("postgreSQLId", postgreSQLId)))
	defer span.End()

	path := utils.Path("/v4/postgresql/organisations/%s/postgresql/%s/databases", ownerId, postgreSQLId)

	// Make API call
	response := client.Get[[]models.PostgreSQLDatabase](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
