// Code generated by generate-services. DO NOT EDIT.

package postgresql

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Listschemaoids **Legacy**: ovd oids.scala:50 getSchemas()
**Algorithm**:
  - Verify addon, query pg_namespace catalog for schema OID+name pairs

**Conformity**: STUB (requires direct connection to addon DB instance)

GET .../oids/schemas — list schema OIDs.

Source: ovd PostgreSQLAccessController.scala — selectSchemas
Behavior: STUB — returns empty list. Requires direct addon DB connection.
Issue: #646

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - postgreSQLId: PostgreSQL addon ID
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := postgresql.Listschemaoids(ctx, client, tracer, ownerId, postgreSQLId, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql
operationId: listSchemaOids
*/
func Listschemaoids(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, postgreSQLId string, opts ...Option) client.Response[[]models.OIdSchemaPair] {
	ctx, span := tracer.Start(ctx, "listSchemaOids", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("postgreSQLId", postgreSQLId)))
	defer span.End()

	path := utils.Path("/v4/postgresql/organisations/%s/postgresql/%s/oids/schemas", ownerId, postgreSQLId)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[[]models.OIdSchemaPair](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
