// Code generated by generate-services. DO NOT EDIT.

package postgresql

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PgGetUser **Legacy**: ovd users.scala:35 getUsersData() (single-user filter)
**Algorithm**:
  - Verify addon, SELECT user by ID, 404 if not found

**Conformity**: PARTIAL (password decryption deferred)

GET /v4/postgresql/organisations/{ownerId}/postgresql/{postgreSQLId}/users/{userId}

Source: ovd PostgreSQLUserPrivilegeRepository.scala — selectUsersPrivileges with userId filter
Behavior: returns 404 if user not found
Issue: #646

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - owner_id: Owner (org) ID
  - postgresql_id: PostgreSQL addon ID
  - user_id: PostgreSQL user ID (pg-user_ prefixed)

# Returns the operation result or an error

Example:

	response := postgresql.PgGetUser(ctx, client, tracer, owner_id, postgresql_id, user_id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql
operationId: pg_get_user
*/
func PgGetUser(ctx context.Context, c *client.Client, tracer trace.Tracer, owner_id string, postgresql_id string, user_id string) client.Response[models.PgUserDataView] {
	ctx, span := tracer.Start(ctx, "pg_get_user", trace.WithAttributes(attribute.String("owner_id", owner_id), attribute.String("postgresql_id", postgresql_id), attribute.String("user_id", user_id)))
	defer span.End()

	path := utils.Path("/v4/postgresql/organisations/%s/postgresql/%s/users/%s", owner_id, postgresql_id, user_id)

	// Make API call
	response := client.Get[models.PgUserDataView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
