// Code generated by generate-services. DO NOT EDIT.

package postgresql

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
PgPatchSchemasPrivileges **Legacy**: ovd users.scala:201 patchSchemasPrivileges()
**Algorithm**:
  - Verify addon, UPSERT schema privilege with read/readAllTables/writeAllTables
  - GRANT/REVOKE on addon DB is deferred

**Conformity**: YES (GRANT/REVOKE on addon DB + metadata UPSERT)

PATCH .../users/{userId}/privileges/databases/{databaseOid}/schemas/{schemaOid}

Source: ovd PostgreSQLUserPrivilegeRepository.scala — updateSchemaPrivileges (UPSERT)
Issue: #646

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (org) ID
  - postgreSQLId: PostgreSQL addon ID
  - pgUserId: PostgreSQL user ID
  - databaseOid: Database OID
  - schemaOid: Schema OID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := postgresql.PgPatchSchemasPrivileges(ctx, client, tracer, ownerId, postgreSQLId, pgUserId, databaseOid, schemaOid, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql
operationId: pg_patch_schemas_privileges
*/
func PgPatchSchemasPrivileges(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, postgreSQLId string, pgUserId string, databaseOid int, schemaOid int, requestBody *models.SchemaPrivilegePatch) client.Response[models.PgSchemaPrivileges] {
	ctx, span := tracer.Start(ctx, "pg_patch_schemas_privileges", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("postgreSQLId", postgreSQLId), attribute.String("pgUserId", pgUserId), attribute.Int("databaseOid", databaseOid), attribute.Int("schemaOid", schemaOid)))
	defer span.End()

	path := utils.Path("/v4/postgresql/organisations/%s/postgresql/%s/users/%s/privileges/databases/%s/schemas/%s", ownerId, postgreSQLId, pgUserId, databaseOid, schemaOid)

	// Make API call
	response := client.Patch[models.PgSchemaPrivileges](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
