// Code generated by generate-services. DO NOT EDIT.

package postgresql

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateschemasprivileges

# Update the user's schema privileges in the given PostgreSQL addon

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - postgreSQLId: PostgreSQL ID
  - pgUserId: PostgreSQL User ID
  - objectId: PostgreSQL Object ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := postgresql.Updateschemasprivileges(ctx, client, tracer, ownerId, postgreSQLId, pgUserId, objectId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: postgresql
operationId: updateSchemasPrivileges
*/
func Updateschemasprivileges(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, postgreSQLId string, pgUserId string, objectId int, requestBody *models.ReadPrivilege) client.Response[models.PgSchemaPrivileges] {
	ctx, span := tracer.Start(ctx, "updateSchemasPrivileges", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("postgreSQLId", postgreSQLId), attribute.String("pgUserId", pgUserId), attribute.Int("objectId", objectId)))
	defer span.End()

	path := utils.Path("/v4/postgresql/organisations/%s/postgresql/%s/users/%s/privileges/databases/%s/schemas/%s", ownerId, postgreSQLId, pgUserId, objectId)

	// Make API call
	response := client.Patch[models.PgSchemaPrivileges](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
