// Code generated by generate-services. DO NOT EDIT.

package build_cache

import (
	"context"
	"fmt"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
RequestDepsCache Fetch the dependencies archive.

Same contract as [`request_build_cache`], against the deps key — which
carries no commit, so one archive is shared by every commit of the app at
that BAS version.

📥 **Algo Source (Legacy):** as `requestBuildCache`, but keyed on
`getDepsCacheFilename` — `{basVersion}-cache-deps-app-{appId}`, with no commit,
so every commit of the app at that BAS version shares one archive.
Source: build-cache-api app/controllers/Application.scala:225-271

🔧 **Algo Rust (Implementation):** the same `fetch` body with
`CacheKind::Deps`, which selects `BuildDefinition::deps_key`.

Source: build-cache-api app/controllers/Application.scala:225-271

	(`requestDepsCache`) — v1.0.2, NOT vendored

Behavior: ticket-authenticated; `303` + `Location` on a hit, `404` + body on

	a miss or when `push_only` is set, `401` on a bad ticket.

Issue: #1652

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - app_id: Application id
  - commit_id: Deployed commit
  - bas_version: BAS version, `{type}-{version}`
  - opts: optional query parameters

# Returns the operation result or an error

Example:

	response := build_cache.RequestDepsCache(ctx, client, tracer, app_id, commit_id, bas_version, opts...)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: build_cache
operationId: request_deps_cache
*/
func RequestDepsCache(ctx context.Context, c *client.Client, tracer trace.Tracer, app_id string, commit_id string, bas_version string, opts ...Option) client.Response[any] {
	ctx, span := tracer.Start(ctx, "request_deps_cache", trace.WithAttributes(attribute.String("app_id", app_id), attribute.String("commit_id", commit_id), attribute.String("bas_version", bas_version)))
	defer span.End()

	path := utils.Path("/api/builds/deps-cache/%s/%s/%s", app_id, commit_id, bas_version)

	// Build query parameters
	query := buildQueryString(opts...)
	if query != "" {
		path = fmt.Sprintf("%s?%s", path, query)
	}

	// Make API call
	response := client.Get[any](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
