// Code generated by generate-services. DO NOT EDIT.

package payments

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getinvoicebyorga GET /v2/organisations/{id}/payments/billings/{bid} — discontinued.

Source: cc-api OrganisationPaymentsAPI.java:101 getInvoice() — 501
Issues: #213, #2428

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID
  - bid: Invoice/billing ID

# Returns the operation result or an error

Example:

	response := payments.Getinvoicebyorga(ctx, client, tracer, id, bid)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: payments
operationId: getInvoiceByOrga
*/
func Getinvoicebyorga(ctx context.Context, c *client.Client, tracer trace.Tracer, id string, bid string) client.Response[any] {
	ctx, span := tracer.Start(ctx, "getInvoiceByOrga", trace.WithAttributes(attribute.String("id", id), attribute.String("bid", bid)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/payments/billings/%s", id, bid)

	// Make API call
	response := client.Get[any](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
