// Code generated by generate-services. DO NOT EDIT.

package payments

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getamountfororga GET /v2/organisations/{id}/credits — discontinued.

Not part of `OrganisationPaymentsAPI.java`, but discontinued all the same:
`OrganisationCreditsAPI.java` holds one method, `getAmount()`, whose whole
body is `NOT_IMPLEMENTED_BILLING`. It used to answer 200 with a balance read
from `account_balance`/`billing_context` — figures cc-api refuses to serve,
and which `crates/tooling/parity-runner/scenarios/26-billing-v2.json` already
expected to be 501.

Source: cc-api OrganisationCreditsAPI.java getAmount() — 501
Issues: #267, #2428

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID

# Returns the operation result or an error

Example:

	response := payments.Getamountfororga(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: payments
operationId: getAmountForOrga
*/
func Getamountfororga(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[any] {
	ctx, span := tracer.Start(ctx, "getAmountForOrga", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/credits", id)

	// Make API call
	response := client.Get[any](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
