// Code generated by generate-services. DO NOT EDIT.

package payments

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getorganisationpaymentinfo GET /v2/organisations/{id}/payment-info — billing/payment address for the org.

Source: cc-api OrganisationAPI.java:159 getPaymentInfo() — implemented in cc-api
Source: billing-api AddressDAO.scala getByOwnerId()
Schema: 00015_billing_schema.sql — table address (name, company, address, zipcode, city, country_alpha2, vat_number)
Spec: analysis-output/12-billing-api-deep-analysis.md §Billing address
Issue: #267

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID

# Returns the operation result or an error

Example:

	response := payments.Getorganisationpaymentinfo(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: payments
operationId: getOrganisationPaymentInfo
*/
func Getorganisationpaymentinfo(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[models.PaymentInfoView] {
	ctx, span := tracer.Start(ctx, "getOrganisationPaymentInfo", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/payment-info", id)

	// Make API call
	response := client.Get[models.PaymentInfoView](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
