// Code generated by generate-services. DO NOT EDIT.

package payments

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getselfstripetoken GET /v2/self/payments/tokens/stripe — discontinued.

Source: cc-api SelfPaymentsAPI.java:232 getStripeToken() — 501
Issues: #289, #2428

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability

# Returns the operation result or an error

Example:

	response := payments.Getselfstripetoken(ctx, client, tracer)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: payments
operationId: getSelfStripeToken
*/
func Getselfstripetoken(ctx context.Context, c *client.Client, tracer trace.Tracer) client.Response[any] {
	ctx, span := tracer.Start(ctx, "getSelfStripeToken")
	defer span.End()

	path := utils.Path("/v2/self/payments/tokens/stripe")

	// Make API call
	response := client.Get[any](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
