// Code generated by generate-services. DO NOT EDIT.

package payments

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Getunpaidinvoicesbyorga GET /v2/organisations/{id}/payments/methods — discontinued.

Source: cc-api OrganisationPaymentsAPI.java getPaymentMethods() — 501
Issues: #289, #2428

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - id: Organisation ID

# Returns the operation result or an error

Example:

	response := payments.Getunpaidinvoicesbyorga(ctx, client, tracer, id)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: payments
operationId: getUnpaidInvoicesByOrga
*/
func Getunpaidinvoicesbyorga(ctx context.Context, c *client.Client, tracer trace.Tracer, id string) client.Response[any] {
	ctx, span := tracer.Start(ctx, "getUnpaidInvoicesByOrga", trace.WithAttributes(attribute.String("id", id)))
	defer span.End()

	path := utils.Path("/v2/organisations/%s/payments/methods", id)

	// Make API call
	response := client.Get[any](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
