// Code generated by generate-services. DO NOT EDIT.

package payments

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updatestripepayment PUT /v2/payments/{bid}/end/stripe — discontinued.

Source: cc-api PaymentsAPI.java:76 updateStripePayment() — 501
Issues: #106, #2428

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - bid: Invoice number

# Returns the operation result or an error

Example:

	response := payments.Updatestripepayment(ctx, client, tracer, bid)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: payments
operationId: updateStripePayment
*/
func Updatestripepayment(ctx context.Context, c *client.Client, tracer trace.Tracer, bid string) client.Response[any] {
	ctx, span := tracer.Start(ctx, "updateStripePayment", trace.WithAttributes(attribute.String("bid", bid)))
	defer span.End()

	path := utils.Path("/v2/payments/%s/end/stripe", bid)

	// Make API call
	response := client.Put[any](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
