// Code generated by generate-services. DO NOT EDIT.

package ai

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	models "go.clever-cloud.dev/sdk/models"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Createotoroshiapikey **Legacy**: ovd AIProviderController.scala:155 createApiKeys()
**Algorithm**:
  - Verify addon + endpoint tenancy, create apikey on Otoroshi, deploy

**Conformity**: YES (Cloud Versatile: 501 when Otoroshi not configured)

POST /v4/ai/organisations/{owner_id}/ai/{ai_id}/endpoints/{endpoint_id}/apikeys — create API key.

Source: references/legacy/ovd/modules/ai/controllers/AIProviderController.scala — createApiKeys
Source: references/legacy/ovd/modules/ai/services/AIProviderService.scala — createApiKeys()
Behavior: verifies addon + endpoint tenancy, creates apikey on Otoroshi,

	deploys apikey on target. Returns Otoroshi JSON.

Issue: #647

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (user or org) ID
  - aiId: AI addon ID
  - endpointId: Otoroshi endpoint ID
  - requestBody: the request payload

# Returns the operation result or an error

Example:

	response := ai.Createotoroshiapikey(ctx, client, tracer, ownerId, aiId, endpointId, requestBody)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ai
operationId: createOtoroshiApiKey
*/
func Createotoroshiapikey(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, aiId string, endpointId string, requestBody *models.CreateApiKeyRequest) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "createOtoroshiApiKey", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("aiId", aiId), attribute.String("endpointId", endpointId)))
	defer span.End()

	path := utils.Path("/v4/ai/organisations/%s/ai/%s/endpoints/%s/apikeys", ownerId, aiId, endpointId)

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, requestBody)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
