// Code generated by generate-services. DO NOT EDIT.

package ai

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteaiendpoint

# Create endpoint to otoroshi cluster

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId:
  - addonAIId:
  - endpointId:

# Returns the operation result or an error

Example:

	response := ai.Deleteaiendpoint(ctx, client, tracer, ownerId, addonAIId, endpointId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ai
operationId: deleteAIEndpoint
*/
func Deleteaiendpoint(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, addonAIId string, endpointId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteAIEndpoint", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("addonAIId", addonAIId), attribute.String("endpointId", endpointId)))
	defer span.End()

	path := utils.Path("/v4/ai/organisations/%s/ai/%s/endpoints/%s", ownerId, addonAIId, endpointId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
