// Code generated by generate-services. DO NOT EDIT.

package ai

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Deleteaiendpoint **Legacy**: ovd AIProviderController.scala:143 deleteEndpointEndpoint()
**Algorithm**:
  - Verify addon + tenancy, undeploy + delete on Otoroshi (best-effort)
  - Always delete tenant row from addon_ai_tenancy

**Conformity**: YES (Otoroshi calls best-effort, DB cleanup always runs)

DELETE /v4/ai/organisations/{owner_id}/ai/{ai_id}/endpoints/{endpoint_id} — delete endpoint.

Source: references/legacy/ovd/modules/ai/controllers/AIProviderController.scala — deleteEndpointEndpoint
Source: references/legacy/ovd/modules/ai/services/AIProviderService.scala — deleteEndpoint()
Behavior: verifies addon + tenancy, resolves config, calls otoroshiClient.undeployEndpoint,

	then otoroshiClient.delete, then deletes tenant row from addon_ai_tenancy.

Schema: addon_ai_tenancy — DELETE WHERE addon_id = $1 AND otoroshi_id = $2
Issue: #647

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (user or org) ID
  - aiId: AI addon ID
  - endpointId: Otoroshi endpoint ID

# Returns the operation result or an error

Example:

	response := ai.Deleteaiendpoint(ctx, client, tracer, ownerId, aiId, endpointId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ai
operationId: deleteAiEndpoint
*/
func Deleteaiendpoint(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, aiId string, endpointId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "deleteAiEndpoint", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("aiId", aiId), attribute.String("endpointId", endpointId)))
	defer span.End()

	path := utils.Path("/v4/ai/organisations/%s/ai/%s/endpoints/%s", ownerId, aiId, endpointId)

	// Make API call
	response := client.Delete[client.Nothing](ctx, c, path)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
