// Code generated by generate-services. DO NOT EDIT.

package ai

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateendpoint **Legacy**: ovd AIProviderController.scala:132 updateEndpointEndpoint()
**Algorithm**:
  - Verify addon + tenancy, forward update to Otoroshi, deploy updated endpoint

**Conformity**: YES (Cloud Versatile: 501 when Otoroshi not configured)

POST /v4/ai/organisations/{owner_id}/ai/{ai_id}/endpoints/{endpoint_id} — update endpoint.

Source: references/legacy/ovd/modules/ai/controllers/AIProviderController.scala — updateEndpointEndpoint
Source: references/legacy/ovd/modules/ai/services/AIProviderService.scala — updateEndpoint()
Behavior: verifies addon + tenancy, forwards to otoroshiClient.updateEndpoint,

	extracts uid from response, deploys the updated endpoint. Returns Otoroshi JSON.

Issue: #647

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (user or org) ID
  - aiId: AI addon ID
  - endpointId: Otoroshi endpoint ID

# Returns the operation result or an error

Example:

	response := ai.Updateendpoint(ctx, client, tracer, ownerId, aiId, endpointId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ai
operationId: updateEndpoint
*/
func Updateendpoint(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, aiId string, endpointId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "updateEndpoint", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("aiId", aiId), attribute.String("endpointId", endpointId)))
	defer span.End()

	path := utils.Path("/v4/ai/organisations/%s/ai/%s/endpoints/%s", ownerId, aiId, endpointId)

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
