// Code generated by generate-services. DO NOT EDIT.

package ai

import (
	"context"
	client "go.clever-cloud.dev/client"
	utils "go.clever-cloud.dev/sdk/internal/utils"
	attribute "go.opentelemetry.io/otel/attribute"
	trace "go.opentelemetry.io/otel/trace"
)

/*
Updateotoroshiapikey **Legacy**: ovd AIProviderController.scala:194 updateApiKeyEndpoint()
**Algorithm**:
  - Verify addon + tenancy, call Otoroshi updateApiKey + deployApiKey

**Conformity**: YES (Cloud Versatile: 501 when Otoroshi not configured)

POST /v4/ai/.../endpoints/{endpoint_id}/apikeys/{apikey_id} — update API key.

Source: references/legacy/ovd/modules/ai/controllers/AIProviderController.scala — updateApiKeyEndpoint
Source: references/legacy/ovd/modules/ai/services/AIProviderService.scala — updateApiKey()
Behavior: verifies addon + tenancy, calls otoroshiClient.updateApiKey + deployApiKey.
Issue: #647

Parameters:
  - ctx: context for the request
  - client: the Clever Cloud client
  - tracer: OpenTelemetry tracer for observability
  - ownerId: Owner (user or org) ID
  - aiId: AI addon ID
  - endpointId: Otoroshi endpoint ID
  - apikeyId: Otoroshi API key ID

# Returns the operation result or an error

Example:

	response := ai.Updateotoroshiapikey(ctx, client, tracer, ownerId, aiId, endpointId, apikeyId)
	if response.HasError() {
		// Handle error
	}
	result := response.Payload()

x-service: ai
operationId: updateOtoroshiApiKey
*/
func Updateotoroshiapikey(ctx context.Context, c *client.Client, tracer trace.Tracer, ownerId string, aiId string, endpointId string, apikeyId string) client.Response[client.Nothing] {
	ctx, span := tracer.Start(ctx, "updateOtoroshiApiKey", trace.WithAttributes(attribute.String("ownerId", ownerId), attribute.String("aiId", aiId), attribute.String("endpointId", endpointId), attribute.String("apikeyId", apikeyId)))
	defer span.End()

	path := utils.Path("/v4/ai/organisations/%s/ai/%s/endpoints/%s/apikeys/%s", ownerId, aiId, endpointId, apikeyId)

	// Make API call
	response := client.Post[client.Nothing](ctx, c, path, nil)

	if response.HasError() {
		span.RecordError(response.Error())
	}

	return response
}
