// Code generated by generate-models. DO NOT EDIT.

package models

// AICreationResponse
type AICreationResponse struct {
	APIKey   any     `json:"apiKey"`
	Endpoint any     `json:"endpoint"`
	Error    *string `json:"error,omitempty"`
}
