// Code generated by generate-models. DO NOT EDIT.

package models

// AdvancedOptions
type AdvancedOptions struct {
	DiskImage    *string       `json:"diskImage,omitempty"`
	EtcdPlatform *EtcdPlatform `json:"etcdPlatform,omitempty"`
}
