// Code generated by generate-models. DO NOT EDIT.

package models

// AiCreationResponse Endpoint creation response — aggregates endpoint + apikey JSON from Otoroshi.  Source: references...
type AiCreationResponse struct {
	APIKey   any     `json:"apiKey"`          // Otoroshi apikey JSON
	Endpoint any     `json:"endpoint"`        // Otoroshi endpoint JSON
	Error    *string `json:"error,omitempty"` // Error description if partial failure
}
