// Code generated by generate-models. DO NOT EDIT.

package models

const AllInOneTopologyDiscriminator = "ALL_IN_ONE"

// AllInOne
type AllInOne struct {
	Flavor                NodeFlavor `json:"flavor"`
	ReplicationFactor     int        `json:"replicationFactor"`
	TopologyDiscriminator string     `json:"topologyDiscriminator"`
}

// GetType returns the type identifier for AllInOne
func (r AllInOne) GetType() string {
	return AllInOneTopologyDiscriminator
}

// isTopologyConfig implements TopologyConfig
func (r AllInOne) isTopologyConfig() {}
