// Code generated by generate-models. DO NOT EDIT.

package models

// ApiHealthStatus represents Aggregate / per-constraint health status. Serializes UPPERCASE (`"HEALTHY"`/`"DEGRADED"`/`"UNHEAL...
type ApiHealthStatus string

const (
	ApiHealthStatusHEALTHY   ApiHealthStatus = "HEALTHY"
	ApiHealthStatusDEGRADED  ApiHealthStatus = "DEGRADED"
	ApiHealthStatusUNHEALTHY ApiHealthStatus = "UNHEALTHY"
)

// String returns the underlying string value
func (e ApiHealthStatus) String() string {
	return string(e)
}
