// Code generated by generate-models. DO NOT EDIT.

package models

// Authentication Authentication set (:307-309).
type Authentication struct {
	Bearers []BearerCredentials `json:"bearers,omitempty"` // Bearer tokens.
	Users   []BasicCredentials  `json:"users,omitempty"`   // Basic users.
}
