// Code generated by generate-models. DO NOT EDIT.

package models

// BackendTcpTransport Backend TCP transport (:165-169).
type BackendTcpTransport struct {
	Transport BackendTcpChoice `json:"transport"` // The composable inner transport.
}
