// Code generated by generate-models. DO NOT EDIT.

package models

// BackendUdpTransport Backend UDP transport (:137-141).
type BackendUdpTransport struct {
	Transport BackendUdpChoice `json:"transport"` // The composable inner transport.
}
