// Code generated by generate-models. DO NOT EDIT.

package models

// Branch
type Branch struct {
	ID            string        `json:"id"`
	Kind          BranchKind    `json:"kind"`
	Label         string        `json:"label"`
	PostalAddress PostalAddress `json:"postalAddress"`
	Tags          []string      `json:"tags,omitempty"`
}
