// Code generated by generate-models. DO NOT EDIT.

package models

// BuildTarget The `{appId, commitId, basVersion}` block echoed back to the guest.  Source: build-cache-api app/...
type BuildTarget struct {
	AppID      string `json:"appId"`
	BasVersion string `json:"basVersion"`
	CommitID   string `json:"commitId"`
}
