// Code generated by generate-models. DO NOT EDIT.

package models

// CellarPlan represents
type CellarPlan string

const (
	CellarPlanAddonPulsarOffload CellarPlan = "ADDON_PULSAR_OFFLOAD"
	CellarPlanBACKUP             CellarPlan = "BACKUP"
	CellarPlanOrganisationLogs   CellarPlan = "ORGANISATION_LOGS"
	CellarPlanS                  CellarPlan = "S"
)

// String returns the underlying string value
func (e CellarPlan) String() string {
	return string(e)
}
