// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// CellarView Full Cellar addon view returned by GET /v4/addon-providers/addon-cellar/addons/{id}.  Source: ref...
type CellarView struct {
	AddonID      string       `json:"addonId"`                // cc-api addon ID
	Buckets      BucketsCount `json:"buckets"`                // Bucket statistics
	CreationDate time.Time    `json:"creationDate"`           // Creation timestamp
	DeletionDate *time.Time   `json:"deletionDate,omitempty"` // Deletion timestamp
	ID           string       `json:"id"`                     // Provider-internal resource ID (cellar_*)
	Name         string       `json:"name"`                   // Human-readable name
	OwnerID      string       `json:"ownerId"`                // Owner (user or org) ID
	Plan         string       `json:"plan"`                   // Plan slug
	Status       string       `json:"status"`                 // Addon lifecycle status
	Traffic      TrafficView  `json:"traffic"`                // Traffic statistics
}
