// Code generated by generate-models. DO NOT EDIT.

package models

// CellarErrorBody Structured Cellar API error body — the 4-field OVD error envelope `{apiRequestId, code, context, ...
type CellarErrorBody struct {
	APIRequestID string             `json:"apiRequestId"` // Per-request id, `request_<uuid>` (from `api_errors::ovd_envelope::request_id`).
	Code         string             `json:"code"`         // Machine-readable error code (e.g. "clever.cellar.bucket-not-found").
	Context      CellarErrorContext `json:"context"`      // Typed error context (resource / input / empty).
	Error        string             `json:"error"`        // Human-readable error message (must NOT leak raw S3/Ceph errors).
}
