// Code generated by generate-models. DO NOT EDIT.

package models

// CellarConsumptionItem One billed consumption line (metric reference + quantity + unit + per-interval detail).  Source: ...
type CellarConsumptionItem struct {
	Details    ConsumptionDetail `json:"details"`              // Per-interval breakdown.
	Quantity   float64           `json:"quantity"`             // Measured quantity in `unit` (sum of `details.quantities`).
	Reference  string            `json:"reference"`            // Metric reference, e.g. `cellar.traffic.in`, `cellar.storage`.
	ResourceID *string           `json:"resourceId,omitempty"` // Set only when a resource consumes another (e.g. Keycloak → Java app); always `null` for Cellar. L...
	Unit       string            `json:"unit"`                 // Unit of `quantity` (always `byte` for Cellar).
}
