// Code generated by generate-models. DO NOT EDIT.

package models

// CellarAddonStatus represents Cellar addon lifecycle status.  Source: references/legacy/ovd/modules/cellar/models/package.scala...
type CellarAddonStatus string

const (
	CellarAddonStatusACTIVE   CellarAddonStatus = "ACTIVE"
	CellarAddonStatusToDelete CellarAddonStatus = "TO_DELETE"
	CellarAddonStatusDELETING CellarAddonStatus = "DELETING"
	CellarAddonStatusDELETED  CellarAddonStatus = "DELETED"
)

// String returns the underlying string value
func (e CellarAddonStatus) String() string {
	return string(e)
}
