// Code generated by generate-models. DO NOT EDIT.

package models

// CephClusterPatch
type CephClusterPatch struct {
	Dashboard *CephDashboard `json:"dashboard,omitempty"`
	Monitors  []any          `json:"monitors,omitempty"`
}
