// Code generated by generate-models. DO NOT EDIT.

package models

// CephDashboard
type CephDashboard struct {
	Credentials BasicCredentials `json:"credentials"`
	Endpoint    string           `json:"endpoint"` // Absolute URL
}
