// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

// Cipher TLS cipher suite supported by load balancers.  Encoded the way OVD's circe derives it — externall...
// Tagged union - can hold one of: map[string]any, map[string]any, map[string]any, map[string]any, map[string]any, map[string]any, map[string]any, map[string]any, map[string]any
type Cipher struct {
	raw json.RawMessage
}

// Type returns the OpenAPI discriminator ("type" field) of the held value.
// Returns "" when empty or when the payload is not a JSON object with a "type" key.
func (u Cipher) Type() string {
	t, _ := peekType(u.raw)
	return t
}

// MarshalJSON returns the raw JSON payload of the held value, or null if empty.
func (u Cipher) MarshalJSON() ([]byte, error) {
	if u.raw == nil {
		return []byte("null"), nil
	}
	return u.raw, nil
}

// UnmarshalJSON stores the raw payload. Use Type() to inspect the discriminator
// or As<Member>() to materialize a concrete value.
func (u *Cipher) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	return nil
}
