// Code generated by generate-models. DO NOT EDIT.

package models

// CleverPeer
type CleverPeer struct {
	Endpoint     WireguardEndpoint `json:"endpoint"`
	Hostname     string            `json:"hostname"`
	Hv           string            `json:"hv"`
	ID           string            `json:"id"`
	Label        *string           `json:"label,omitempty"`
	ParentEvent  *string           `json:"parentEvent,omitempty"`
	ParentMember string            `json:"parentMember"`
	PublicKey    string            `json:"publicKey"`
}
