// Code generated by generate-models. DO NOT EDIT.

package models

// ClusterNode
type ClusterNode struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	RamBytes int            `json:"ramBytes"`
	Status   NodeStatusType `json:"status"`
	VCpus    int            `json:"vCpus"`
}
