// Code generated by generate-models. DO NOT EDIT.

package models

// ClusterVersionCheck
type ClusterVersionCheck struct {
	Available  []string `json:"available"`
	Installed  string   `json:"installed"`
	Latest     string   `json:"latest"`
	NeedUpdate bool     `json:"needUpdate"`
}
