// Code generated by generate-models. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"
)

const ClusterItemEvent = "CLUSTER_ITEM"

// ClusterItem
type ClusterItem struct {
	Data     *PublicClusterItemData `json:"data,omitempty"`
	Date     time.Time              `json:"date"`
	Event    string                 `json:"event"`
	ID       string                 `json:"id"`
	ItemType ClusterItemType        `json:"itemType"`
	Status   ClusterItemStatusType  `json:"status"`
}

// GetType returns the type identifier for ClusterItem
func (r ClusterItem) GetType() string {
	return ClusterItemEvent
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(ClusterItem{...}) always produces a valid
// payload — no need to set the type field manually.
func (v ClusterItem) MarshalJSON() ([]byte, error) {
	v.Event = ClusterItemEvent
	type alias ClusterItem
	return json.Marshal((alias)(v))
}

// ToClusterDeploymentEvent wraps the value into a ClusterDeploymentEvent ready to be JSON-encoded.
// The discriminator is set automatically by ClusterItem's MarshalJSON.
func (v ClusterItem) ToClusterDeploymentEvent() ClusterDeploymentEvent {
	raw, _ := json.Marshal(v)
	return ClusterDeploymentEvent{raw: raw}
}
