// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

// ClusterDeploymentEvent A unified event log entry returned by `GET /v4/kubernetes/…/clusters/{id}/events`.  Each entry is...
// Tagged union - can hold one of: map[string]any, map[string]any, map[string]any
type ClusterDeploymentEvent struct {
	raw json.RawMessage
}

// Type returns the OpenAPI discriminator ("type" field) of the held value.
// Returns "" when empty or when the payload is not a JSON object with a "type" key.
func (u ClusterDeploymentEvent) Type() string {
	t, _ := peekType(u.raw)
	return t
}

// MarshalJSON returns the raw JSON payload of the held value, or null if empty.
func (u ClusterDeploymentEvent) MarshalJSON() ([]byte, error) {
	if u.raw == nil {
		return []byte("null"), nil
	}
	return u.raw, nil
}

// UnmarshalJSON stores the raw payload. Use Type() to inspect the discriminator
// or As<Member>() to materialize a concrete value.
func (u *ClusterDeploymentEvent) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	return nil
}
