// Code generated by generate-models. DO NOT EDIT.

package models

// ClusterNode A node within a node group, as embedded in the aggregate cluster view.  Source: references/legacy...
type ClusterNode struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	RamBytes int            `json:"ramBytes"`
	Status   NodeStatusType `json:"status"`
	VCpus    int            `json:"vCpus"`
}
