// Code generated by generate-models. DO NOT EDIT.

package models

// ConsumptionDetail
type ConsumptionDetail struct {
	Interval   string `json:"interval"`
	Quantities []int  `json:"quantities,omitempty"`
}
