// Code generated by generate-models. DO NOT EDIT.

package models

// ConsumerSummary OAuth1 consumer summary inside the summary response.  Source: cc-api output/summary/OAuth1Consume...
type ConsumerSummary struct {
	Key     string  `json:"key"`
	Name    *string `json:"name,omitempty"`
	Picture *string `json:"picture,omitempty"`
}
