// Code generated by generate-models. DO NOT EDIT.

package models

// ConsumptionItemView
type ConsumptionItemView struct {
	Details    ConsumptionDetailView `json:"details"`
	Quantity   float64               `json:"quantity"`
	Reference  string                `json:"reference"`
	ResourceID *string               `json:"resourceId,omitempty"`
	Unit       string                `json:"unit"`
}
