// Code generated by generate-models. DO NOT EDIT.

package models

// ConsumptionDetail Per-interval consumption breakdown.  Source: references/legacy/ovd/core — ConsumptionDetail Schem...
type ConsumptionDetail struct {
	Interval   string    `json:"interval"`   // Interval granularity (legacy uses `"hourly"`).
	Quantities []float64 `json:"quantities"` // Quantity per interval period (`[1.0; days]`).
}
