// Code generated by generate-models. DO NOT EDIT.

package models

// ConsumptionDetail
type ConsumptionDetail struct {
	Interval   string    `json:"interval"`
	Quantities []float64 `json:"quantities,omitempty"`
}
