// Code generated by generate-models. DO NOT EDIT.

package models

// ContactEntry A single contact entry for PUT /v2/internal/organisations/{id}/contacts.  Source: cc-api WannabeC...
type ContactEntry struct {
	ContactType  string  `json:"contact_type"`           // Contact type: SECURITY, PRIVACY, or ABUSE.
	EmailAddress string  `json:"email_address"`          // Contact email address.
	PhoneNumber  *string `json:"phone_number,omitempty"` // Contact phone number (optional).
}
