// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// ContainerRegistryToken Container Registry Token view returned by the v4 API.  Source: references/legacy/ovd/modules/cont...
type ContainerRegistryToken struct {
	CreationDate time.Time                    `json:"creationDate"`        // Creation timestamp
	ExpiresAt    *time.Time                   `json:"expiresAt,omitempty"` // Expiration timestamp (None = never expires)
	ID           string                       `json:"id"`                  // Token ID
	IsActive     bool                         `json:"isActive"`            // Whether the token is currently active (not revoked, not expired)
	Rights       ContainerRegistryTokenRights `json:"rights"`              // Token rights (READ or READ_WRITE)
	Scope        []ScopePattern               `json:"scope"`               // Scope patterns for access control
}
