// Code generated by generate-models. DO NOT EDIT.

package models

const CoreMaxLimitType = "CoreMaxLimit"

// CoreMaxLimit
type CoreMaxLimit struct {
	Maximum int    `json:"maximum"`
	Type    string `json:"type"`
}

// GetType returns the type identifier for CoreMaxLimit
func (r CoreMaxLimit) GetType() string {
	return CoreMaxLimitType
}

// isQuotaItem implements QuotaItem
func (r CoreMaxLimit) isQuotaItem() {}
