// Code generated by generate-models. DO NOT EDIT.

package models

// CreateBucketRequest Request body for creating a bucket.  Source: references/legacy/ovd/modules/cellar/models/package....
type CreateBucketRequest struct {
	Name       string `json:"name"`                 // Bucket name
	Versioning *bool  `json:"versioning,omitempty"` // Whether to enable versioning
}
