// Code generated by generate-models. DO NOT EDIT.

package models

// CreateCephXUserRequest Request body for creating a Ceph X user.  Source: references/legacy/ovd/modules/storage/controlle...
type CreateCephXUserRequest struct {
	Caps     any    `json:"caps"`     // Capabilities to grant.
	EntityID string `json:"entityId"` // Entity ID for the new Ceph auth user.
}
