// Code generated by generate-models. DO NOT EDIT.

package models

// CreateTardisTokenRequest Request to create a Tardis addon token.  Source: ovd tardis create token request body Issue: #742
type CreateTardisTokenRequest struct {
	Name       string  `json:"name"`                 // Human-readable token name.
	Properties *any    `json:"properties,omitempty"` // Token properties (JSON).
	TTL        *int    `json:"ttl,omitempty"`        // Time-to-live in seconds.
	Type       *string `json:"type,omitempty"`       // Token type.
}
