// Code generated by generate-models. DO NOT EDIT.

package models

// CreateClusterRequest Request body for creating a new Cellar cluster.  Source: references/legacy/ovd/modules/cellar/mod...
type CreateClusterRequest struct {
	Available *bool  `json:"available,omitempty"` // Whether the cluster accepts new provisions
	Host      string `json:"host"`                // S3 endpoint host
	Password  string `json:"password"`            // Ceph admin password
	Username  string `json:"username"`            // Ceph admin username
	Zone      string `json:"zone"`                // Availability zone
}
