// Code generated by generate-models. DO NOT EDIT.

package models

// CreateReadTokenRequest
type CreateReadTokenRequest struct {
	Applications []string   `json:"applications,omitempty"`
	Attributes   *MapString `json:"attributes,omitempty"`
	Labels       *MapString `json:"labels,omitempty"`
	Owners       []string   `json:"owners,omitempty"`
	Producers    []string   `json:"producers,omitempty"`
	Resource     string     `json:"resource"`
	TTL          string     `json:"ttl"`
	Tenant       TenantID   `json:"tenant"`
}
