// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const DedicatedComputeTopologyDiscriminator = "DEDICATED_COMPUTE"

// DedicatedCompute
type DedicatedCompute struct {
	Flavor                NodeFlavor `json:"flavor"`
	ReplicationFactor     int        `json:"replicationFactor"`
	TopologyDiscriminator string     `json:"topologyDiscriminator"`
}

// GetType returns the type identifier for DedicatedCompute
func (r DedicatedCompute) GetType() string {
	return DedicatedComputeTopologyDiscriminator
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(DedicatedCompute{...}) always produces a valid
// payload — no need to set the type field manually.
func (v DedicatedCompute) MarshalJSON() ([]byte, error) {
	v.TopologyDiscriminator = DedicatedComputeTopologyDiscriminator
	type alias DedicatedCompute
	return json.Marshal((alias)(v))
}

// ToTopologyConfig wraps the value into a TopologyConfig ready to be JSON-encoded.
// The discriminator is set automatically by DedicatedCompute's MarshalJSON.
func (v DedicatedCompute) ToTopologyConfig() TopologyConfig {
	raw, _ := json.Marshal(v)
	return TopologyConfig{raw: raw}
}
