// Code generated by generate-models. DO NOT EDIT.

package models

// DeploymentStatus
type DeploymentStatus struct {
	PlacementHypothesis MapHypervisormetadata `json:"placementHypothesis"`
	Step                DeploymentStep        `json:"step"`
	VmStatus            MapVmdeploymentstatus `json:"vmStatus"`
}
