// Code generated by generate-models. DO NOT EDIT.

package models

// DeploymentStepType represents The deployment pipeline step tags for a Kubernetes cluster — the port of OVD's `DeploymentStepNam...
type DeploymentStepType string

const (
	DeploymentStepTypeNetworkGroupCreation        DeploymentStepType = "NETWORK_GROUP_CREATION"
	DeploymentStepTypeLoadBalancerNetworkCreation DeploymentStepType = "LOAD_BALANCER_NETWORK_CREATION"
	DeploymentStepTypeMateriaLogicaldb            DeploymentStepType = "MATERIA_LOGICALDB"
	DeploymentStepTypeOtelConfig                  DeploymentStepType = "OTEL_CONFIG"
	DeploymentStepTypeControlPlaneDeployment      DeploymentStepType = "CONTROL_PLANE_DEPLOYMENT"
	DeploymentStepTypeLoadBalancerConfiguration   DeploymentStepType = "LOAD_BALANCER_CONFIGURATION"
	DeploymentStepTypePluginInstallation          DeploymentStepType = "PLUGIN_INSTALLATION"
	DeploymentStepTypeFeatureProvision            DeploymentStepType = "FEATURE_PROVISION"
	DeploymentStepTypePluginReconcile             DeploymentStepType = "PLUGIN_RECONCILE"
	DeploymentStepTypeStorageDeployment           DeploymentStepType = "STORAGE_DEPLOYMENT"
	DeploymentStepTypeRedeployBeforeYaml          DeploymentStepType = "REDEPLOY_BEFORE_YAML"
	DeploymentStepTypeRedeployAfterYaml           DeploymentStepType = "REDEPLOY_AFTER_YAML"
	DeploymentStepTypeRedeployOrphanSweep         DeploymentStepType = "REDEPLOY_ORPHAN_SWEEP"
)

// String returns the underlying string value
func (e DeploymentStepType) String() string {
	return string(e)
}
