// Code generated by generate-models. DO NOT EDIT.

package models

// DirectTransport
type DirectTransport struct {
	ClusterID StringMaxLength128 `json:"clusterId"`
	Tags      []string           `json:"tags,omitempty"`
}
