// Code generated by generate-models. DO NOT EDIT.

package models

// DrainRecipient
// Union type - can be one of: DatadogRecipient, ElasticsearchRecipient, NewRelicRecipient, OVHTCPRecipient, RawRecipient, SyslogTCPRecipient, SyslogUDPRecipient
type DrainRecipient interface {
	isDrainRecipient()
	GetType() string
}
