// Code generated by generate-models. DO NOT EDIT.

package models

// Dtls
type Dtls struct {
	Dtls BackendDTLSTransport `json:"dtls"`
}

// isTransport1 implements Transport1
func (r Dtls) isTransport1() {}
