// Code generated by generate-models. DO NOT EDIT.

package models

const ElasticsearchRecipient1Type = "ELASTICSEARCH"

// ElasticsearchRecipient1
type ElasticsearchRecipient1 struct {
	Index           string   `json:"index"`
	Password        *string  `json:"password,omitempty"` // Masked password
	TLSVerification *TLSMode `json:"tlsVerification,omitempty"`
	Type            string   `json:"type"`
	URL             string   `json:"url"`
	Username        *string  `json:"username,omitempty"`
}

// GetType returns the type identifier for ElasticsearchRecipient1
func (r ElasticsearchRecipient1) GetType() string {
	return ElasticsearchRecipient1Type
}

// isDrainRecipient implements DrainRecipient
func (r ElasticsearchRecipient1) isDrainRecipient() {}
