// Code generated by generate-models. DO NOT EDIT.

package models

// ElasticsearchRecipient
type ElasticsearchRecipient struct {
	Index           string   `json:"index"`
	Password        *string  `json:"password,omitempty"`
	TlsVerification *TLSMode `json:"tlsVerification,omitempty"`
	Type            string   `json:"type"`
	URL             string   `json:"url"`
	Username        *string  `json:"username,omitempty"`
}
