// Code generated by generate-models. DO NOT EDIT.

package models

// Feature A provider feature flag, serialised as `{"name": ..., "enabled": ...}`.  Source: references/legac...
type Feature struct {
	Enabled *bool  `json:"enabled,omitempty"`
	Name    string `json:"name"`
}
