// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

// Flavor
// Tagged union - can hold one of: LOcto, MOcto, MQuattro, SDuo, SQuattro, XsDuo, XsQuattro
type Flavor struct {
	raw json.RawMessage
}

// Type returns the OpenAPI discriminator ("type" field) of the held value.
// Returns "" when empty or when the payload is not a JSON object with a "type" key.
func (u Flavor) Type() string {
	t, _ := peekType(u.raw)
	return t
}

// MarshalJSON returns the raw JSON payload of the held value, or null if empty.
func (u Flavor) MarshalJSON() ([]byte, error) {
	if u.raw == nil {
		return []byte("null"), nil
	}
	return u.raw, nil
}

// String returns the JSON representation of the held value, or "null" if empty.
// Implemented so that fmt %v/%+v print readable JSON rather than the underlying bytes.
func (u Flavor) String() string {
	if u.raw == nil {
		return "null"
	}
	return string(u.raw)
}

// UnmarshalJSON stores the raw payload. Use Type() to inspect the discriminator
// or As<Member>() to materialize a concrete value.
func (u *Flavor) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	return nil
}
