// Code generated by generate-models. DO NOT EDIT.

package models

// FunctionTriggerPulsarDetails
type FunctionTriggerPulsarDetails struct {
	External               bool    `json:"external"`
	PulsarToken            *string `json:"pulsar_token,omitempty"`
	PulsarTopicFqdn        string  `json:"pulsar_topic_fqdn"`
	PulsarTopicFqdnIsRegex bool    `json:"pulsar_topic_fqdn_is_regex"`
	PulsarURL              string  `json:"pulsar_url"`
}
