// Code generated by generate-models. DO NOT EDIT.

package models

// FunctionPlatform represents Platform that the function is using
type FunctionPlatform string

const (
	FunctionPlatformAssemblyScript FunctionPlatform = "ASSEMBLY_SCRIPT"
	FunctionPlatformJavaScript     FunctionPlatform = "JAVA_SCRIPT"
	FunctionPlatformRUST           FunctionPlatform = "RUST"
	FunctionPlatformTinyGo         FunctionPlatform = "TINY_GO"
)
