// Code generated by generate-models. DO NOT EDIT.

package models

// HTTPErrorContext
// Union type - can be one of: Empty, Typed, Typed, Typed, Typed, Typed, Typed, Typed
type HTTPErrorContext interface {
	isHTTPErrorContext()
	GetType() string
}
