// Code generated by generate-models. DO NOT EDIT.

package models

// Http4
type Http4 struct {
	HTTP HttpTransport `json:"http"`
}

// isTransport4 implements Transport4
func (r Http4) isTransport4() {}
