// Code generated by generate-models. DO NOT EDIT.

package models

// HypervisorStorage Source: ovd hypervisor/Storage.scala — Storage (sizes in bytes, bandwidth in bytes/s)
type HypervisorStorage struct {
	Capacity    StorageQuantities `json:"capacity"`
	Kind        any               `json:"kind"`
	Metadata    StorageMetadata   `json:"metadata"`
	Utilization StorageQuantities `json:"utilization"`
}
