// Code generated by generate-models. DO NOT EDIT.

package models

// HypervisorQuantities Source: ovd Hypervisor.scala — HypervisorQuantities
type HypervisorQuantities struct {
	MilliCpu int `json:"milliCpu"`
	Ram      int `json:"ram"` // RAM in bytes.
}
