// Code generated by generate-models. DO NOT EDIT.

package models

// IAMBiscuitType represents
type IAMBiscuitType string

const (
	IAMBiscuitTypeRESOURCE IAMBiscuitType = "RESOURCE"
	IAMBiscuitTypeROOT     IAMBiscuitType = "ROOT"
	IAMBiscuitTypeSERVICE  IAMBiscuitType = "SERVICE"
	IAMBiscuitTypeUSER     IAMBiscuitType = "USER"
)
