// Code generated by generate-models. DO NOT EDIT.

package models

// IAMBiscuitType represents
type IAMBiscuitType string

const (
	IAMBiscuitTypeRESOURCE IAMBiscuitType = "RESOURCE"
	IAMBiscuitTypeROOT     IAMBiscuitType = "ROOT"
	IAMBiscuitTypeSERVICE  IAMBiscuitType = "SERVICE"
	IAMBiscuitTypeUSER     IAMBiscuitType = "USER"
)

// String returns the underlying string value
func (e IAMBiscuitType) String() string {
	return string(e)
}
