// Code generated by generate-models. DO NOT EDIT.

package models

// ImpersonationTokenView Impersonation token response for `GET /v2/internal/tokenforuser/{userId}`.  Source: cc-api Intern...
type ImpersonationTokenView struct {
	Secret string `json:"secret"` // OAuth1 token secret (32 random chars).
	Token  string `json:"token"`  // OAuth1 access token (32 hex chars, UUID without dashes).
}
