// Code generated by generate-models. DO NOT EDIT.

package models

// Input
type Input struct {
	Names []string `json:"names,omitempty"`
}

// isHTTPErrorContext implements HTTPErrorContext
func (r Input) isHTTPErrorContext() {}
