// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// KeycloakConsumptionQuery
type KeycloakConsumptionQuery struct {
	Since time.Time `json:"since"`
	Until time.Time `json:"until"`
}
