// Code generated by generate-models. DO NOT EDIT.

package models

// KeycloakConsumptionItem One billed item inside a consumption line.  Source: references/legacy/ovd/modules/keycloak/src/ma...
type KeycloakConsumptionItem struct {
	Details    KeycloakConsumptionDetail `json:"details"`
	Quantity   float64                   `json:"quantity"` // Whole DAYS the addon was active — `ChronoUnit.DAYS.between`, not seconds.
	Reference  string                    `json:"reference"`
	ResourceID *string                   `json:"resourceId,omitempty"` // Always `null` for keycloak, but legacy emits the key.  Source: references/legacy/ovd/core/src/mai...
	Unit       string                    `json:"unit"`
}
