// Code generated by generate-models. DO NOT EDIT.

package models

// Kind represents
type Kind string

const (
	KindKV Kind = "KV"
)

// String returns the underlying string value
func (e Kind) String() string {
	return string(e)
}
