// Code generated by generate-models. DO NOT EDIT.

package models

// KmsPlanIdentifier represents KMS addon plan identifiers.  Source: references/legacy/ovd/modules/kms/models/AddonPlanIdentifier...
type KmsPlanIdentifier string

const (
	KmsPlanIdentifierALPHA KmsPlanIdentifier = "ALPHA"
	KmsPlanIdentifierBETA  KmsPlanIdentifier = "BETA"
	KmsPlanIdentifierBASE  KmsPlanIdentifier = "BASE"
)

// String returns the underlying string value
func (e KmsPlanIdentifier) String() string {
	return string(e)
}
