// Code generated by generate-models. DO NOT EDIT.

package models

// KubernetesTaint Kubernetes taint.  Source: references/legacy/ovd/modules/kubernetes/models/types/Taint.scala
type KubernetesTaint struct {
	Effect TaintEffect `json:"effect"`          // Taint effect
	Key    string      `json:"key"`             // Taint key
	Value  *string     `json:"value,omitempty"` // Taint value
}
