// Code generated by generate-models. DO NOT EDIT.

package models

// KubernetesServiceConfig
type KubernetesServiceConfig struct {
	Topologies []TopologyConstraints `json:"topologies,omitempty"`
	Versions   []string              `json:"versions,omitempty"`
}
