// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

// ListTokensResponse The **wire** shape of `GET /v4/tenants/{tenant_id}/tokens` — one of two, chosen by `paginate`.  T...
// Tagged union - can hold one of: []TokenView, PageTokenview
type ListTokensResponse struct {
	raw json.RawMessage
}

// Type returns the OpenAPI discriminator ("type" field) of the held value.
// Returns "" when empty or when the payload is not a JSON object with a "type" key.
func (u ListTokensResponse) Type() string {
	t, _ := peekType(u.raw)
	return t
}

// MarshalJSON returns the raw JSON payload of the held value, or null if empty.
func (u ListTokensResponse) MarshalJSON() ([]byte, error) {
	if u.raw == nil {
		return []byte("null"), nil
	}
	return u.raw, nil
}

// UnmarshalJSON stores the raw payload. Use Type() to inspect the discriminator
// or As<Member>() to materialize a concrete value.
func (u *ListTokensResponse) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	return nil
}
