// Code generated by generate-models. DO NOT EDIT.

package models

// LoadbalanceroutboxT OVD `LoadBalancerOutbox` (LoadBalancerOutbox.scala:25-30) — row 45. `payload` is the protobuf dec...
type LoadbalanceroutboxT struct {
	LoadbalancerID string         `json:"loadbalancerId"`
	OutboxOffset   int            `json:"outboxOffset"`
	Payload        map[string]any `json:"payload"`
	ServerID       string         `json:"serverId"`
}
