// Code generated by generate-models. DO NOT EDIT.

package models

// LoadBalancerAudit1
type LoadBalancerAudit1 struct{}

// isResourceType implements ResourceType
func (r LoadBalancerAudit1) isResourceType() {}
