// Code generated by generate-models. DO NOT EDIT.

package models

// LoadBalancerListenersAndClusters The listeners/clusters halves of a stored configuration (:19-24). Decoding applies the Set semant...
type LoadBalancerListenersAndClusters struct {
	Certificates *map[string]any `json:"certificates,omitempty"` // SHA-256 leaf fingerprint to certificate and private key.
	Clusters     []Cluster       `json:"clusters"`               // Cluster set — structurally deduplicated, first-occurrence order.
	Listeners    []Listener      `json:"listeners"`              // Ordered listener sequence — order preserved verbatim (decision 6).
}
