// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// LoadBalancerOutput
type LoadBalancerOutput struct {
	AppliedConfigVersion         *int                          `json:"appliedConfigVersion,omitempty"`
	CoOwners                     []TenantID                    `json:"coOwners,omitempty"`
	CreatedAt                    time.Time                     `json:"createdAt"`
	DomainName                   DnsDomainName                 `json:"domainName"`
	Flavor                       Flavor                        `json:"flavor"`
	Frozen                       bool                          `json:"frozen"`
	ID                           LoadBalancerId                `json:"id"`
	Ips                          []string                      `json:"ips,omitempty"`
	LoadbalancerParentResourceID *LoadBalancerParentResourceId `json:"loadbalancerParentResourceId,omitempty"`
	Mutualized                   bool                          `json:"mutualized"`
	OwnerID                      TenantID                      `json:"ownerId"`
	RegionID                     RegionId                      `json:"regionId"`
	Tags                         []string                      `json:"tags,omitempty"`
}
