// Code generated by generate-models. DO NOT EDIT.

package models

// MapHypervisor Source: references/legacy/ovd/modules/compute/placement/PlacementService.scala PlacementResult
type MapHypervisor struct {
	Failures    map[string]any `json:"failures"`
	Hypervisors map[string]any `json:"hypervisors"`
}
