// Code generated by generate-models. DO NOT EDIT.

package models

// MateriaProvisionResponse Provision/get response: `message` is exactly `"Created"` on provision and `"Addon found"` on get ...
type MateriaProvisionResponse struct {
	Config  map[string]any `json:"config"`
	ID      string         `json:"id"`
	Message string         `json:"message"`
}
