// Code generated by generate-models. DO NOT EDIT.

package models

// MatomoPlanIdentifier represents Plan identifier accepted in provision requests. Matomo has a single plan (`BETA`); any other valu...
type MatomoPlanIdentifier string

const (
	MatomoPlanIdentifierBETA MatomoPlanIdentifier = "BETA"
)

// String returns the underlying string value
func (e MatomoPlanIdentifier) String() string {
	return string(e)
}
