// Code generated by generate-models. DO NOT EDIT.

package models

// Memory Source: ovd Memory.scala (frequency in Hz)
type Memory struct {
	Frequency float64       `json:"frequency"`
	Sticks    []MemoryStick `json:"sticks"`
}
