// Code generated by generate-models. DO NOT EDIT.

package models

// MetabasePatchRequest Request body for the version-update endpoint.  Source: references/legacy/ovd/modules/metabase/mod...
type MetabasePatchRequest struct {
	TargetVersion string `json:"targetVersion"` // Target version to upgrade/downgrade to.
}
