// Code generated by generate-models. DO NOT EDIT.

package models

// MetricsHeatmapResponse
type MetricsHeatmapResponse struct {
	AccessCount int     `json:"accessCount"`
	Lat         float64 `json:"lat"`
	Long        float64 `json:"long"`
}
