// Code generated by generate-models. DO NOT EDIT.

package models

// MetricsDataValues
type MetricsDataValues struct {
	Timestamp *int   `json:"timestamp,omitempty"`
	Value     string `json:"value"`
}
