// Code generated by generate-models. DO NOT EDIT.

package models

// MfaRecoveryCodeView One recovery code returned by GET /v2/self/mfa/{kind}/backupcodes.  cc-api serializes `List<MFARe...
type MfaRecoveryCodeView struct {
	Code string `json:"code"`
}
