// Code generated by generate-models. DO NOT EDIT.

package models

// MigrationKind represents Migration kind.  Source: ovd V0__init_postgresql_addon.sql — CREATE TYPE t_migration_kind
type MigrationKind string

const (
	MigrationKindToDetermine          MigrationKind = "TO_DETERMINE"
	MigrationKindSharedToShared       MigrationKind = "SHARED_TO_SHARED"
	MigrationKindSharedToDedicated    MigrationKind = "SHARED_TO_DEDICATED"
	MigrationKindDedicatedToDedicated MigrationKind = "DEDICATED_TO_DEDICATED"
	MigrationKindDedicatedToShared    MigrationKind = "DEDICATED_TO_SHARED"
)

// String returns the underlying string value
func (e MigrationKind) String() string {
	return string(e)
}
