// Code generated by generate-models. DO NOT EDIT.

package models

// NamespaceView Namespace view for GET /v2/organisations/{id}/namespaces.  Source: cc-api Organisation.java getNa...
type NamespaceView struct {
	Namespace string `json:"namespace"`
}
