// Code generated by generate-models. DO NOT EDIT.

package models

// NetworkGroup
type NetworkGroup struct {
	ID    string              `json:"id"`
	Peers []NetworkGroupPeer1 `json:"peers,omitempty"`
}

// isNetworkDetails implements NetworkDetails
func (r NetworkGroup) isNetworkDetails() {}

// isNetworkGroupComponent implements NetworkGroupComponent
func (r NetworkGroup) isNetworkGroupComponent() {}
