// Code generated by generate-models. DO NOT EDIT.

package models

// NetworkGroupServerEndpoint
type NetworkGroupServerEndpoint struct {
	PrivateAddress any `json:"privateAddress"`
	PublicAddress  any `json:"publicAddress"`
}
