// Code generated by generate-models. DO NOT EDIT.

package models

// NetworkGroupConfig
type NetworkGroupConfig struct {
	NetworkGroup NetworkGroup `json:"networkGroup"`
}

// isConfiguration implements Configuration
func (r NetworkGroupConfig) isConfiguration() {}
