// Code generated by generate-models. DO NOT EDIT.

package models

// NetworkGroupServerEndpoint
type NetworkGroupServerEndpoint struct {
	PrivateAddress string `json:"privateAddress"`
	PublicAddress  string `json:"publicAddress"`
}
