// Code generated by generate-models. DO NOT EDIT.

package models

// NetworkGroupComponent
// Union type - can be one of: CleverPeer, ExternalPeer, Member, NetworkGroup
type NetworkGroupComponent interface {
	isNetworkGroupComponent()
	GetType() string
}
