// Code generated by generate-models. DO NOT EDIT.

package models

const NewRelicRecipientType = "NEWRELIC"

// NewRelicRecipient
type NewRelicRecipient struct {
	APIKey string `json:"apiKey"`
	Type   string `json:"type"`
	URL    string `json:"url"`
}

// GetType returns the type identifier for NewRelicRecipient
func (r NewRelicRecipient) GetType() string {
	return NewRelicRecipientType
}

// isDrainRecipient1 implements DrainRecipient1
func (r NewRelicRecipient) isDrainRecipient1() {}
