// Code generated by generate-models. DO NOT EDIT.

package models

// NewsfeedEntry Newsfeed entry returned by GET /v2/newsfeeds/blog and /engineering.  Source: cc-api NewsFeedAPI.j...
type NewsfeedEntry struct {
	Date  *string `json:"date,omitempty"`
	Link  *string `json:"link,omitempty"`
	Title *string `json:"title,omitempty"`
}
