// Code generated by generate-models. DO NOT EDIT.

package models

// NodeGroupStatusType represents
type NodeGroupStatusType string

const (
	NodeGroupStatusTypeCREATED     NodeGroupStatusType = "CREATED"
	NodeGroupStatusTypeDELETED     NodeGroupStatusType = "DELETED"
	NodeGroupStatusTypeDEPLOYED    NodeGroupStatusType = "DEPLOYED"
	NodeGroupStatusTypeDEPLOYING   NodeGroupStatusType = "DEPLOYING"
	NodeGroupStatusTypeFAILED      NodeGroupStatusType = "FAILED"
	NodeGroupStatusTypePENDING     NodeGroupStatusType = "PENDING"
	NodeGroupStatusTypeREADY       NodeGroupStatusType = "READY"
	NodeGroupStatusTypeRESIZING    NodeGroupStatusType = "RESIZING"
	NodeGroupStatusTypeTERMINATING NodeGroupStatusType = "TERMINATING"
	NodeGroupStatusTypeToResize    NodeGroupStatusType = "TO_RESIZE"
	NodeGroupStatusTypeToTerminate NodeGroupStatusType = "TO_TERMINATE"
)

// String returns the underlying string value
func (e NodeGroupStatusType) String() string {
	return string(e)
}
