// Code generated by generate-models. DO NOT EDIT.

package models

// NodeGroupPatchPayload
type NodeGroupPatchPayload struct {
	AutoscalingEnabled *bool                `json:"autoscalingEnabled,omitempty"`
	Description        *StringMaxLength4096 `json:"description,omitempty"`
	MaxNodeCount       *int                 `json:"maxNodeCount,omitempty"`
	MinNodeCount       *int                 `json:"minNodeCount,omitempty"`
	Name               NodeGroupName        `json:"name"`
	Tag                *StringMaxLength1024 `json:"tag,omitempty"`
	TargetNodeCount    int                  `json:"targetNodeCount"`
}
