// Code generated by generate-models. DO NOT EDIT.

package models

// OVDErrorFieldContext
type OVDErrorFieldContext struct {
	FieldName  string `json:"fieldName"`
	FieldValue string `json:"fieldValue"`
}

// isOVDErrorContext implements OVDErrorContext
func (r OVDErrorFieldContext) isOVDErrorContext() {}
