// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const OVHTCPRecipient1Type = "OVH_TCP"

// OVHTCPRecipient1
type OVHTCPRecipient1 struct {
	Rfc5424StructuredDataParameters *string `json:"rfc5424StructuredDataParameters,omitempty"`
	Token                           *string `json:"token,omitempty"` // Masked authentication token
	Type                            string  `json:"type"`
	URL                             string  `json:"url"`
}

// GetType returns the type identifier for OVHTCPRecipient1
func (r OVHTCPRecipient1) GetType() string {
	return OVHTCPRecipient1Type
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(OVHTCPRecipient1{...}) always produces a valid
// payload — no need to set the type field manually.
func (v OVHTCPRecipient1) MarshalJSON() ([]byte, error) {
	v.Type = OVHTCPRecipient1Type
	type alias OVHTCPRecipient1
	return json.Marshal((alias)(v))
}

// ToDrainRecipient wraps the value into a DrainRecipient ready to be JSON-encoded.
// The discriminator is set automatically by OVHTCPRecipient1's MarshalJSON.
func (v OVHTCPRecipient1) ToDrainRecipient() DrainRecipient {
	raw, _ := json.Marshal(v)
	return DrainRecipient{raw: raw}
}
