// Code generated by generate-models. DO NOT EDIT.

package models

// OVDErrorOperationContext
type OVDErrorOperationContext struct {
	Operation    string  `json:"operation"`
	ResourceName *string `json:"resourceName,omitempty"`
	ResourceType string  `json:"resourceType"`
}

// isOVDErrorContext implements OVDErrorContext
func (r OVDErrorOperationContext) isOVDErrorContext() {}
