// Code generated by generate-models. DO NOT EDIT.

package models

const OVHTCPRecipientViewType = "OVH_TCP"

// OVHTCPRecipientView
type OVHTCPRecipientView struct {
	Rfc5424StructuredDataParameters *string `json:"rfc5424StructuredDataParameters,omitempty"`
	Token                           *string `json:"token,omitempty"` // Masked authentication token
	Type                            string  `json:"type"`
	URL                             string  `json:"url"`
}

// GetType returns the type identifier for OVHTCPRecipientView
func (r OVHTCPRecipientView) GetType() string {
	return OVHTCPRecipientViewType
}

// isDrainRecipientView implements DrainRecipientView
func (r OVHTCPRecipientView) isDrainRecipientView() {}
