// Code generated by generate-models. DO NOT EDIT.

package models

// OVDInvalidResponseBody
type OVDInvalidResponseBody struct {
	APIRequestID string          `json:"apiRequestId"`
	Code         string          `json:"code"`
	Context      OVDErrorContext `json:"context"`
	Error        string          `json:"error"`
}
