// Code generated by generate-models. DO NOT EDIT.

package models

// OVHTCPRecipient
type OVHTCPRecipient struct {
	Rfc5424StructuredDataParameters *string `json:"rfc5424StructuredDataParameters,omitempty"`
	Token                           *string `json:"token,omitempty"`
	Type                            string  `json:"type"`
	URL                             string  `json:"url"`
}
