// Code generated by generate-models. DO NOT EDIT.

package models

// OpenTelemetryGatewayView View of an OpenTelemetry gateway (admin token is never exposed).  Source: references/legacy/ovd/m...
type OpenTelemetryGatewayView struct {
	ID  string `json:"id"`  // Gateway ID
	URL string `json:"url"` // Gateway base URL
}
