// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// OtelNamespace Namespace response — OVD `NamespaceResponse`, `@encodedName("OtelNamespace")`.  `location` and `g...
type OtelNamespace struct {
	CreatedAt       time.Time `json:"createdAt"`
	GatewayEndpoint string    `json:"gatewayEndpoint"`
	GatewayID       string    `json:"gatewayId"` // `otelgw_<uuid>`.
	ID              string    `json:"id"`        // `otel_<uuid>`.
	Location        string    `json:"location"`
	OwnerID         string    `json:"ownerId"` // The path `ownerId`, stored verbatim (`orga_<uuid>`).
	ReadToken       string    `json:"readToken"`
	UpdatedAt       time.Time `json:"updatedAt"`
}
