// Code generated by generate-models. DO NOT EDIT.

package models

// OtoroshiApi
type OtoroshiApi struct {
	Openapi string `json:"openapi"`
	Secret  string `json:"secret"`
	URL     string `json:"url"`
	User    string `json:"user"`
}
