// Code generated by generate-models. DO NOT EDIT.

package models

// OtoroshiPlan represents
type OtoroshiPlan string

const (
	OtoroshiPlanALPHA OtoroshiPlan = "ALPHA"
	OtoroshiPlanBASE  OtoroshiPlan = "BASE"
	OtoroshiPlanBETA  OtoroshiPlan = "BETA"
)

// String returns the underlying string value
func (e OtoroshiPlan) String() string {
	return string(e)
}
