// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// PaginationMetadata
type PaginationMetadata struct {
	HasMore    bool       `json:"hasMore"`
	NextCursor *time.Time `json:"nextCursor,omitempty"`
}
