// Code generated by generate-models. DO NOT EDIT.

package models

// PaginatedEvents A page of events on the wire — the `{items, metadata}` envelope as a **concrete** `ToSchema` type...
type PaginatedEvents struct {
	Items    []Event                      `json:"items"`    // The page of events.
	Metadata MonitoringPaginationMetadata `json:"metadata"` // Pagination metadata.
}
