// Code generated by generate-models. DO NOT EDIT.

package models

// PatchClusterVersion Patch cluster version payload.  Source: references/legacy/ovd/modules/kubernetes/models/PatchClus...
type PatchClusterVersion struct {
	TargetVersion Version `json:"targetVersion"` // Target Kubernetes version to upgrade to
}
