// Code generated by generate-models. DO NOT EDIT.

package models

// PeerView OVD `PeerView(peer_id, peer_ip, peer_hostname)` — snake_case on purpose ("KEEP snake_case, used i...
type PeerView struct {
	PeerHostname string `json:"peer_hostname"`
	PeerID       string `json:"peer_id"`
	PeerIP       string `json:"peer_ip"`
}
