// Code generated by generate-models. DO NOT EDIT.

package models

// PeerKind represents
type PeerKind string

const (
	PeerKindCLEVER   PeerKind = "CLEVER"
	PeerKindEXTERNAL PeerKind = "EXTERNAL"
)
