// Code generated by generate-models. DO NOT EDIT.

package models

// PingRequest Watchdog ping action (request).  Source: cc-api com.clevercloud.watchdog.PingAction enum + Ping.j...
type PingRequest struct {
	Action string  `json:"action"`         // Action — must be "PING" for a valid watchdog request.
	Data   *string `json:"data,omitempty"` // Opaque payload echoed back in the PONG response.
}
