// Code generated by generate-models. DO NOT EDIT.

package models

// PlacementDryRunInput Source: references/legacy/ovd/modules/compute/routes/HypervisorController.scala dryRunPlacement
type PlacementDryRunInput struct {
	VirtualMachines []VirtualMachineSpecInput `json:"virtualMachines"`
}
