// Code generated by generate-models. DO NOT EDIT.

package models

// PlatformApplication represents
type PlatformApplication string

const (
	PlatformApplicationAddonApiCellar    PlatformApplication = "ADDON_API_CELLAR"
	PlatformApplicationMETRICS           PlatformApplication = "METRICS"
	PlatformApplicationMetricsAccesslogs PlatformApplication = "METRICS_ACCESSLOGS"
)

// String returns the underlying string value
func (e PlatformApplication) String() string {
	return string(e)
}
