// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// PlatformTokenOutput Platform token output.  Source: references/legacy/ovd/modules/warp10/src/main/scala/com/cleverclo...
type PlatformTokenOutput struct {
	Applications []PlatformApplication `json:"applications"` // Resolved platform applications that this token can access.  Source: ovd PlatformTokenModels.scala...
	CreatedAt    time.Time             `json:"createdAt"`    // Creation timestamp.
	ExpiresAt    time.Time             `json:"expiresAt"`    // Expiration timestamp.
	Labels       map[string]any        `json:"labels"`       // Injected labels (app_id, owner_id) from path parameters.  Source: ovd PlatformTokenModels.scala —...
	RevocationID RevocationId          `json:"revocationId"` // Revocation ID (16 hex characters).
	Scope        TokenScope            `json:"scope"`        // Token scope: "READ" or "WRITE".
	Token        Warp10TokenSecret     `json:"token"`        // The generated Warp10 token string.
}
