// Code generated by generate-models. DO NOT EDIT.

package models

// PostgresqlAddonFullView The FULL internal addon representation `GET .../addons/configHost/{configHost}` renders — referen...
type PostgresqlAddonFullView struct {
	AddonID              string                    `json:"addonId"`
	AppID                string                    `json:"appId"`
	CallbackURL          string                    `json:"callbackUrl"`
	ClusterID            *string                   `json:"clusterId,omitempty"`
	Config               PostgresqlAddonConfigView `json:"config"`
	CreationDate         string                    `json:"creationDate"`
	DeletionDate         *string                   `json:"deletionDate,omitempty"`
	EditDate             *string                   `json:"editDate,omitempty"`
	EncryptionPassphrase *string                   `json:"encryptionPassphrase,omitempty"`
	InstanceID           *string                   `json:"instanceId,omitempty"`
	LogplexToken         string                    `json:"logplexToken"`
	OwnerID              *string                   `json:"ownerId,omitempty"`
	Password             string                    `json:"password"`
	Plan                 string                    `json:"plan"`
	Status               string                    `json:"status"`
	Zone                 string                    `json:"zone"`
}
