// Code generated by generate-models. DO NOT EDIT.

package models

// PostgreSQLSchemaPrivileges
type PostgreSQLSchemaPrivileges struct {
	SchemaName string                      `json:"schemaName"`
	Tables     []PostgreSQLTablePrivileges `json:"tables,omitempty"`
	Users      []PostgreSQLObjectPrivilege `json:"users,omitempty"`
}
