// Code generated by generate-models. DO NOT EDIT.

package models

// PostgresqlAddonConfigView The nested `config` object of [`PostgresqlAddonFullView`] — reference `PostgresqlConfig::to_json`...
type PostgresqlAddonConfigView struct {
	CustomConfiguration any                      `json:"customConfiguration"`
	Db                  string                   `json:"db"`
	DirectHostOnly      bool                     `json:"directHostOnly"`
	DoBackup            bool                     `json:"doBackup"`
	FerretDB            bool                     `json:"ferretDB"`
	FerretDBDirectPort  *int                     `json:"ferretDBDirectPort,omitempty"`
	FerretDBHostname    *string                  `json:"ferretDBHostname,omitempty"`
	FerretDBPort        *int                     `json:"ferretDBPort,omitempty"`
	Host                string                   `json:"host"`
	HvHostname          *string                  `json:"hvHostname,omitempty"`
	HvPort              *int                     `json:"hvPort,omitempty"`
	MigrateDumpAll      bool                     `json:"migrateDumpAll"`
	Password            string                   `json:"password"`
	Port                *int                     `json:"port,omitempty"`
	ReadOnlyUsers       []PostgresqlReadOnlyUser `json:"readOnlyUsers"`
	ReplicationPassword *string                  `json:"replicationPassword,omitempty"`
	ReplicationUser     *string                  `json:"replicationUser,omitempty"`
	Role                string                   `json:"role"`
	RootPassword        *string                  `json:"rootPassword,omitempty"`
	RootUser            *string                  `json:"rootUser,omitempty"`
	Token               *string                  `json:"token,omitempty"`
	User                string                   `json:"user"`
	Version             string                   `json:"version"`
}
