// Code generated by generate-models. DO NOT EDIT.

package models

// PostgresqlMigrationStep One entry of the `steps` jsonb array — reused, unlike the frozen rewrite's split `Step`/`StepCons...
type PostgresqlMigrationStep struct {
	EndDate   *string                     `json:"endDate,omitempty"`
	Message   *string                     `json:"message,omitempty"`
	StartDate string                      `json:"startDate"`
	Status    PostgresqlMigrationStatus   `json:"status"`
	Value     PostgresqlMigrationStepType `json:"value"`
}
