// Code generated by generate-models. DO NOT EDIT.

package models

// PostgresqlFerretDbStateView `FerretDBProvisioningStateView`, 14 fields in declaration order, `None` fields OMITTED (five of t...
type PostgresqlFerretDbStateView struct {
	ActorThreadID   *string `json:"actor_thread_id,omitempty"`
	AddonID         string  `json:"addon_id"`
	CreatedAt       string  `json:"created_at"`
	ErrorDetails    *string `json:"error_details,omitempty"`
	ErrorMessage    *string `json:"error_message,omitempty"`
	IsActive        bool    `json:"is_active"`
	IsCompleted     bool    `json:"is_completed"`
	IsFailed        bool    `json:"is_failed"`
	IsPaused        bool    `json:"is_paused"`
	LastStep        *string `json:"last_step,omitempty"`
	PauseCycleCount int     `json:"pause_cycle_count"`
	State           string  `json:"state"`
	StepToResume    *string `json:"step_to_resume,omitempty"`
	UpdatedAt       string  `json:"updated_at"`
}
