// Code generated by generate-models. DO NOT EDIT.

package models

// PostgresqlProvidersConsoleViewV2 `GET /resources/providerInfos` response body.  Source: rewrite/rust/src/provider/views.rs — Postg...
type PostgresqlProvidersConsoleViewV2 struct {
	Clusters  []PostgresqlClusterConsoleViewV2 `json:"clusters"`
	Dedicated map[string]any                   `json:"dedicated"`
}
