// Code generated by generate-models. DO NOT EDIT.

package models

// PresignRequest The `/url` body: which part of which upload to presign.
type PresignRequest struct {
	Bucket     string         `json:"bucket"`               // Must equal the macaroon's `bucket` caveat.
	Key        string         `json:"key"`                  // Must equal the macaroon's `key` caveat.
	Parameters *PresignParams `json:"parameters,omitempty"` // The query bag. `parameters` is the shipped Rust client's name for it; `params` is the Go client's...
}
