// Code generated by generate-models. DO NOT EDIT.

package models

// PresignParams `params` carries repeated query values, so every field is a LIST — that is how `map[string][]stri...
type PresignParams struct {
	PartNumber []string `json:"partNumber,omitempty"` // Single-element list holding the 1-based part number.
	UploadID   []string `json:"uploadId,omitempty"`   // Single-element list holding the upload id.
}
