// Code generated by generate-models. DO NOT EDIT.

package models

// PresignedUrl Presigned URL response for kubeconfig download.  **`url` only** — OVD's `PresignedURL` encodes ex...
type PresignedUrl struct {
	URL string `json:"url"` // The self-authenticating presigned URL (carries its capability token in `?authorization=`).
}
