// Code generated by generate-models. DO NOT EDIT.

package models

// ProviderSummary Addon provider summary inside the summary response.  Source: cc-api output/summary/ProviderSummar...
type ProviderSummary struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}
