// Code generated by generate-models. DO NOT EDIT.

package models

// PublicBackendDtlsTransport
type PublicBackendDtlsTransport struct {
	ClientCertificate *any           `json:"clientCertificate,omitempty"`
	Dtls              map[string]any `json:"dtls"`
	Verification      *any           `json:"verification,omitempty"`
}
