// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const PublicNodeGroupDataType = "PublicNodeGroupData"

// PublicNodeGroupData
type PublicNodeGroupData struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

// GetType returns the type identifier for PublicNodeGroupData
func (r PublicNodeGroupData) GetType() string {
	return PublicNodeGroupDataType
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(PublicNodeGroupData{...}) always produces a valid
// payload — no need to set the type field manually.
func (v PublicNodeGroupData) MarshalJSON() ([]byte, error) {
	v.Type = PublicNodeGroupDataType
	type alias PublicNodeGroupData
	return json.Marshal((alias)(v))
}

// ToPublicClusterItemData wraps the value into a PublicClusterItemData ready to be JSON-encoded.
// The discriminator is set automatically by PublicNodeGroupData's MarshalJSON.
func (v PublicNodeGroupData) ToPublicClusterItemData() PublicClusterItemData {
	raw, _ := json.Marshal(v)
	return PublicClusterItemData{raw: raw}
}
