// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const PublicOtelConfigDataType = "PublicOtelConfigData"

// PublicOtelConfigData
type PublicOtelConfigData struct {
	LogsEndpoint    string  `json:"logsEndpoint"`
	MetricsEndpoint string  `json:"metricsEndpoint"`
	OtelID          string  `json:"otelId"`
	TenantID        OwnerID `json:"tenantId"`
	TracesEndpoint  string  `json:"tracesEndpoint"`
	Type            string  `json:"type"`
}

// GetType returns the type identifier for PublicOtelConfigData
func (r PublicOtelConfigData) GetType() string {
	return PublicOtelConfigDataType
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(PublicOtelConfigData{...}) always produces a valid
// payload — no need to set the type field manually.
func (v PublicOtelConfigData) MarshalJSON() ([]byte, error) {
	v.Type = PublicOtelConfigDataType
	type alias PublicOtelConfigData
	return json.Marshal((alias)(v))
}

// ToPublicClusterItemData wraps the value into a PublicClusterItemData ready to be JSON-encoded.
// The discriminator is set automatically by PublicOtelConfigData's MarshalJSON.
func (v PublicOtelConfigData) ToPublicClusterItemData() PublicClusterItemData {
	raw, _ := json.Marshal(v)
	return PublicClusterItemData{raw: raw}
}
