// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const PublicSchedulerType = "PublicScheduler"

// PublicScheduler
type PublicScheduler struct {
	Type string `json:"type"`
}

// GetType returns the type identifier for PublicScheduler
func (r PublicScheduler) GetType() string {
	return PublicSchedulerType
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(PublicScheduler{...}) always produces a valid
// payload — no need to set the type field manually.
func (v PublicScheduler) MarshalJSON() ([]byte, error) {
	v.Type = PublicSchedulerType
	type alias PublicScheduler
	return json.Marshal((alias)(v))
}

// ToPublicBundledComponent wraps the value into a PublicBundledComponent ready to be JSON-encoded.
// The discriminator is set automatically by PublicScheduler's MarshalJSON.
func (v PublicScheduler) ToPublicBundledComponent() PublicBundledComponent {
	raw, _ := json.Marshal(v)
	return PublicBundledComponent{raw: raw}
}
