// Code generated by generate-models. DO NOT EDIT.

package models

// PulsarZoneOverride One zone's exception to [`PlacementView::default_cluster`].  Issue: #2986
type PulsarZoneOverride struct {
	Cluster string `json:"cluster"` // The cluster that zone provisions onto instead of the default.
	Zone    string `json:"zone"`    // The zone as cc-api spells it in a provision request (`rbx`), which is also how it is written in t...
}
