// Code generated by generate-models. DO NOT EDIT.

package models

// QuotaItem
// Union type - can be one of: APIRateLimit, CoreMaxLimit, MaxIp, MaxMonthlyGtsCount, MaxParrallelConnections, MaxPointsPerDay, MillivCPUMaxLimit, RamMaxUsage
type QuotaItem interface {
	isQuotaItem()
}
