// Code generated by generate-models. DO NOT EDIT.

package models

// RedeployControlPlanePayload
type RedeployControlPlanePayload struct {
	AfterYamls  []string `json:"afterYamls,omitempty"`
	BeforeYamls []string `json:"beforeYamls,omitempty"`
}
