// Code generated by generate-models. DO NOT EDIT.

package models

const RedeployType = "Redeploy"

// Redeploy
type Redeploy struct {
	Type string `json:"type"`
}

// GetType returns the type identifier for Redeploy
func (r Redeploy) GetType() string {
	return RedeployType
}

// isRedeployPayload implements RedeployPayload
func (r Redeploy) isRedeployPayload() {}
