// Code generated by generate-models. DO NOT EDIT.

package models

// RefreshTokenStateType represents A refresh token's lifecycle state — **computed** from timestamps, never stored. Precedence (OVD `...
type RefreshTokenStateType string

const (
	RefreshTokenStateTypeACTIVE   RefreshTokenStateType = "ACTIVE"
	RefreshTokenStateTypeCONSUMED RefreshTokenStateType = "CONSUMED"
	RefreshTokenStateTypeEXPIRED  RefreshTokenStateType = "EXPIRED"
	RefreshTokenStateTypeREVOKED  RefreshTokenStateType = "REVOKED"
)

// String returns the underlying string value
func (e RefreshTokenStateType) String() string {
	return string(e)
}
