// Code generated by generate-models. DO NOT EDIT.

package models

// ReplaceLoadBalancerConfigurationInput Complete replacement body for the listeners, clusters, and certificate store.
type ReplaceLoadBalancerConfigurationInput struct {
	Certificates *map[string]any `json:"certificates,omitempty"`
	Clusters     []Cluster       `json:"clusters,omitempty"`
	Listeners    []Listener      `json:"listeners,omitempty"`
}
