// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const Reserved1Status = "Reserved"

// Reserved1
type Reserved1 struct {
	Hypervisor HypervisorMetadata `json:"hypervisor"`
	Status     string             `json:"status"`
}

// GetType returns the type identifier for Reserved1
func (r Reserved1) GetType() string {
	return Reserved1Status
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(Reserved1{...}) always produces a valid
// payload — no need to set the type field manually.
func (v Reserved1) MarshalJSON() ([]byte, error) {
	v.Status = Reserved1Status
	type alias Reserved1
	return json.Marshal((alias)(v))
}

// ToVMDeploymentStatus wraps the value into a VMDeploymentStatus ready to be JSON-encoded.
// The discriminator is set automatically by Reserved1's MarshalJSON.
func (v Reserved1) ToVMDeploymentStatus() VMDeploymentStatus {
	raw, _ := json.Marshal(v)
	return VMDeploymentStatus{raw: raw}
}
