// Code generated by generate-models. DO NOT EDIT.

package models

// Resource
type Resource struct {
	Consumption Consumption        `json:"consumption"`
	Description string             `json:"description"`
	ID          ResourceID         `json:"id"`
	Kind        IdentifiedKind     `json:"kind"`
	Name        StringMaxLength128 `json:"name"`
	ProductID   string             `json:"productId"`
	Statuses    []IdentifiedStatus `json:"statuses,omitempty"`
	Tags        []string           `json:"tags,omitempty"`
	TenantID    TenantID           `json:"tenantId"`
	Version     string             `json:"version"`
}
