// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// ResourceAclView OVD `ResourceACL` (ipam types) — rows 37-38 response schema. Not producible in WP3 (the ACL store...
type ResourceAclView struct {
	Allow      []string  `json:"allow"`
	CreatedAt  time.Time `json:"createdAt"`
	Deny       []string  `json:"deny"`
	ID         string    `json:"id"`
	OwnerID    string    `json:"ownerId"`
	ResourceID string    `json:"resourceId"`
	UpdatedAt  time.Time `json:"updatedAt"`
}
