// Code generated by generate-models. DO NOT EDIT.

package models

// RevocationFeed The revocation feed's wire envelope — the shape legacy OVD served and cc-api's `BiscuitRevocation...
type RevocationFeed struct {
	Items    []string               `json:"items"` // The revocation ids — bare strings, because cc-api deserializes `List<String>`.
	Metadata RevocationFeedMetadata `json:"metadata"`
}
