// Code generated by generate-models. DO NOT EDIT.

package models

const SelectorType = "selector"

// Selector
type Selector struct {
	Path []string `json:"path,omitempty"`
	Type string   `json:"type"`
}

// GetType returns the type identifier for Selector
func (r Selector) GetType() string {
	return SelectorType
}

// isTyped implements Typed
func (r Selector) isTyped() {}
