// Code generated by generate-models. DO NOT EDIT.

package models

const ServerEndpointType = "ServerEndpoint"

// ServerEndpoint
type ServerEndpoint struct {
	NgTerm     any    `json:"ngTerm"`
	PublicTerm any    `json:"publicTerm"`
	Type       string `json:"type"`
}

// GetType returns the type identifier for ServerEndpoint
func (r ServerEndpoint) GetType() string {
	return ServerEndpointType
}

// isWireguardEndpoint implements WireguardEndpoint
func (r ServerEndpoint) isWireguardEndpoint() {}
