// Code generated by generate-models. DO NOT EDIT.

package models

// Server Source: ovd Server.scala
type Server struct {
	NetworkDevices []NetworkDevice `json:"networkDevices,omitempty"`
	Spec           ServerSpec      `json:"spec"`
	Status         ServerStatus    `json:"status"`
	StorageDevices []StorageDevice `json:"storageDevices,omitempty"`
}
