// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// ServerView OVD `Server` (Server.scala:12-22) — `drain` included (V10).
type ServerView struct {
	AvailabilityZone     string    `json:"availabilityZone"`
	CreatedAt            time.Time `json:"createdAt"`
	Drain                bool      `json:"drain"`
	ID                   string    `json:"id"`
	LoadbalancerCapacity int       `json:"loadbalancerCapacity"`
	Maintenance          bool      `json:"maintenance"`
	OwnerID              string    `json:"ownerId"`
	RegionID             string    `json:"regionId"`
	UpdatedAt            time.Time `json:"updatedAt"`
}
