// Code generated by generate-models. DO NOT EDIT.

package models

import "time"

// Server
type Server struct {
	AvailabilityZone     string    `json:"availabilityZone"`
	CreatedAt            time.Time `json:"createdAt"`
	Drain                bool      `json:"drain"`
	ID                   string    `json:"id"`
	LoadbalancerCapacity int       `json:"loadbalancerCapacity"`
	Maintenance          bool      `json:"maintenance"`
	OwnerID              TenantID  `json:"ownerId"`
	RegionID             RegionId  `json:"regionId"`
	UpdatedAt            time.Time `json:"updatedAt"`
}
