// Code generated by generate-models. DO NOT EDIT.

package models

// SetAllowedMonthlyInvoicesRequest Request body for PUT /v2/internal/organisations/{id}/allowed_monthly_invoices.  Source: cc-api In...
type SetAllowedMonthlyInvoicesRequest struct {
	Limit int `json:"limit"` // Maximum number of allowed monthly invoices.
}
