// Code generated by generate-models. DO NOT EDIT.

package models

// SignedUrlRequest Request body for the org-scoped `upload-url` / `download-url` endpoints.  The object key comes fr...
type SignedUrlRequest struct {
	ExpiresIn *int   `json:"expiresIn,omitempty"` // Expiry in seconds. Defaults to 300 and is passed through with **no clamp** (1:1 with legacy `expi...
	ObjectKey string `json:"objectKey"`           // Object key to presign.
}
