// Code generated by generate-models. DO NOT EDIT.

package models

// Specification
type Specification struct {
	Ciphers       *Ciphers               `json:"ciphers,omitempty"`
	Connections   int                    `json:"connections"`
	Loadbalancing *LoadBalancingStrategy `json:"loadbalancing,omitempty"`
	Memory        int                    `json:"memory"`
	StickyName    *string                `json:"stickyName,omitempty"`
	Timeouts      *Timeouts              `json:"timeouts,omitempty"`
	Vcpus         int                    `json:"vcpus"`
}
