// Code generated by generate-models. DO NOT EDIT.

package models

// Specification Load balancer specification — hardware capabilities + user-configurable settings.  Source: refere...
type Specification struct {
	Ciphers       *any    `json:"ciphers,omitempty"`
	Connections   int     `json:"connections"`
	Loadbalancing *any    `json:"loadbalancing,omitempty"`
	Memory        int     `json:"memory"` // Memory in MB.
	StickyName    *string `json:"stickyName,omitempty"`
	Timeouts      *any    `json:"timeouts,omitempty"`
	Vcpus         int     `json:"vcpus"`
}
