// Code generated by generate-models. DO NOT EDIT.

package models

// StepExecutionStatus represents Status of a deployment step execution.  Source: references/legacy/ovd/modules/kubernetes/models/t...
type StepExecutionStatus string

const (
	StepExecutionStatusPENDING    StepExecutionStatus = "PENDING"
	StepExecutionStatusInProgress StepExecutionStatus = "IN_PROGRESS"
	StepExecutionStatusCOMPLETED  StepExecutionStatus = "COMPLETED"
	StepExecutionStatusFAILED     StepExecutionStatus = "FAILED"
	StepExecutionStatusSKIPPED    StepExecutionStatus = "SKIPPED"
)

// String returns the underlying string value
func (e StepExecutionStatus) String() string {
	return string(e)
}
