// Code generated by generate-models. DO NOT EDIT.

package models

// StorageQuantities Source: ovd hypervisor/Storage.scala — StorageQuantities
type StorageQuantities struct {
	Bandwidth float64 `json:"bandwidth"`
	Iops      int     `json:"iops"`
	Size      int     `json:"size"`
}
