// Code generated by generate-models. DO NOT EDIT.

package models

// StorageConfigurationPolicies
type StorageConfigurationPolicies struct {
	DurationInMinutes *int `json:"durationInMinutes,omitempty"`
	SizeInBytes       *int `json:"sizeInBytes,omitempty"`
}
