// Code generated by generate-models. DO NOT EDIT.

package models

// TS TS addon view returned by GET /v4/addon-providers/addon-ts/addons/{id}.  Source: references/legac...
type TS struct {
	AddonID    string      `json:"addonId"`
	OwnerID    string      `json:"ownerId"`
	Plan       TSPlan      `json:"plan"`
	ResourceID TsId        `json:"resourceId"`
	Resources  TsResources `json:"resources"`
}
