// Code generated by generate-models. DO NOT EDIT.

package models

// TardisAddonStatus represents Tardis addon status.  Source: ovd tardis migration — status ENUM Issue: #742
type TardisAddonStatus string

const (
	TardisAddonStatusACTIVE        TardisAddonStatus = "ACTIVE"
	TardisAddonStatusToDelete      TardisAddonStatus = "TO_DELETE"
	TardisAddonStatusTokensDeleted TardisAddonStatus = "TOKENS_DELETED"
	TardisAddonStatusDELETED       TardisAddonStatus = "DELETED"
)

// String returns the underlying string value
func (e TardisAddonStatus) String() string {
	return string(e)
}
