// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const TcpType = "Tcp"

// Tcp
type Tcp struct {
	Tcp  TcpTransport `json:"tcp"`
	Type string       `json:"type"`
}

// GetType returns the type identifier for Tcp
func (r Tcp) GetType() string {
	return TcpType
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(Tcp{...}) always produces a valid
// payload — no need to set the type field manually.
func (v Tcp) MarshalJSON() ([]byte, error) {
	v.Type = TcpType
	type alias Tcp
	return json.Marshal((alias)(v))
}

// ToTransport wraps the value into a Transport ready to be JSON-encoded.
// The discriminator is set automatically by Tcp's MarshalJSON.
func (v Tcp) ToTransport() Transport {
	raw, _ := json.Marshal(v)
	return Transport{raw: raw}
}
