// Code generated by generate-models. DO NOT EDIT.

package models

// TcpTransport Frontend TCP transport (:445-449).
type TcpTransport struct {
	Transport TcpTransportChoice `json:"transport"` // The composable inner transport.
}
