// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

const Tls1Type = "Tls"

// Tls1
type Tls1 struct {
	TLS  TlsTransport `json:"tls"`
	Type string       `json:"type"`
}

// GetType returns the type identifier for Tls1
func (r Tls1) GetType() string {
	return Tls1Type
}

// MarshalJSON forces the discriminator field to the constant value before
// encoding so that json.Marshal(Tls1{...}) always produces a valid
// payload — no need to set the type field manually.
func (v Tls1) MarshalJSON() ([]byte, error) {
	v.Type = Tls1Type
	type alias Tls1
	return json.Marshal((alias)(v))
}

// ToTransport5 wraps the value into a Transport5 ready to be JSON-encoded.
// The discriminator is set automatically by Tls1's MarshalJSON.
func (v Tls1) ToTransport5() Transport5 {
	raw, _ := json.Marshal(v)
	return Transport5{raw: raw}
}
