// Code generated by generate-models. DO NOT EDIT.

package models

const Tls1Type = "Tls"

// Tls1
type Tls1 struct {
	TLS  TlsTransport `json:"tls"`
	Type string       `json:"type"`
}

// GetType returns the type identifier for Tls1
func (r Tls1) GetType() string {
	return Tls1Type
}

// isTransport5 implements Transport5
func (r Tls1) isTransport5() {}
