// Code generated by generate-models. DO NOT EDIT.

package models

// TlsEcdheRsaWithAes128GcmSha256
type TlsEcdheRsaWithAes128GcmSha256 struct{}

// isCipher implements Cipher
func (r TlsEcdheRsaWithAes128GcmSha256) isCipher() {}
