// Code generated by generate-models. DO NOT EDIT.

package models

// TlsVersion represents TLS protocol bounds carried by the SDK. TLS 1.0 and 1.1 are deliberately not representable.
type TlsVersion string

const (
	TlsVersionTlsVersionUnspecified TlsVersion = "TLS_VERSION_UNSPECIFIED"
	TlsVersionTlsVersion12          TlsVersion = "TLS_VERSION_1_2"
	TlsVersionTlsVersion13          TlsVersion = "TLS_VERSION_1_3"
)

// String returns the underlying string value
func (e TlsVersion) String() string {
	return string(e)
}
