// Code generated by generate-models. DO NOT EDIT.

package models

// TopologyConstraints
type TopologyConstraints struct {
	AvailableFlavors  []NodeFlavor            `json:"availableFlavors,omitempty"`
	ReplicationFactor ReplicationFactorConfig `json:"replicationFactor"`
	Topology          TopologyType            `json:"topology"`
}
