// Code generated by generate-models. DO NOT EDIT.

package models

// TopologyConfig
// Union type - can be one of: AllInOne, DedicatedCompute, Distributed
type TopologyConfig interface {
	isTopologyConfig()
	GetType() string
}
