// Code generated by generate-models. DO NOT EDIT.

package models

// TopologyType represents Cluster control-plane topology discriminator.  Source: references/legacy/ovd/modules/kubernetes/m...
type TopologyType string

const (
	TopologyTypeAllInOne         TopologyType = "ALL_IN_ONE"
	TopologyTypeDedicatedCompute TopologyType = "DEDICATED_COMPUTE"
	TopologyTypeDISTRIBUTED      TopologyType = "DISTRIBUTED"
)

// String returns the underlying string value
func (e TopologyType) String() string {
	return string(e)
}
