// Code generated by generate-models. DO NOT EDIT.

package models

import "encoding/json"

// Transport
// Tagged union - can hold one of: Tcp, Udp
type Transport struct {
	raw json.RawMessage
}

// Type returns the OpenAPI discriminator ("type" field) of the held value.
// Returns "" when empty or when the payload is not a JSON object with a "type" key.
func (u Transport) Type() string {
	t, _ := peekType(u.raw)
	return t
}

// MarshalJSON returns the raw JSON payload of the held value, or null if empty.
func (u Transport) MarshalJSON() ([]byte, error) {
	if u.raw == nil {
		return []byte("null"), nil
	}
	return u.raw, nil
}

// UnmarshalJSON stores the raw payload. Use Type() to inspect the discriminator
// or As<Member>() to materialize a concrete value.
func (u *Transport) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	return nil
}

// TransportVariant is satisfied by every concrete type that can be wrapped into a Transport.
// Lets generic code accept any variant without naming each one.
type TransportVariant interface {
	ToTransport() Transport
}

// AsTcp decodes the held payload as a Tcp. The bool is false if the union
// does not currently hold this variant or the payload fails to decode.
func (u Transport) AsTcp() (Tcp, bool) {
	var v Tcp
	if t, err := peekType(u.raw); err != nil || t != TcpType {
		return v, false
	}
	if err := json.Unmarshal(u.raw, &v); err != nil {
		return v, false
	}
	return v, true
}

// NewTransportFromTcp wraps a Tcp into a Transport ready to be JSON-encoded.
func NewTransportFromTcp(v Tcp) (Transport, error) {
	raw, err := json.Marshal(v)
	if err != nil {
		return Transport{}, err
	}
	return Transport{raw: raw}, nil
}

// AsUdp decodes the held payload as a Udp. The bool is false if the union
// does not currently hold this variant or the payload fails to decode.
func (u Transport) AsUdp() (Udp, bool) {
	var v Udp
	if t, err := peekType(u.raw); err != nil || t != UdpType {
		return v, false
	}
	if err := json.Unmarshal(u.raw, &v); err != nil {
		return v, false
	}
	return v, true
}

// NewTransportFromUdp wraps a Udp into a Transport ready to be JSON-encoded.
func NewTransportFromUdp(v Udp) (Transport, error) {
	raw, err := json.Marshal(v)
	if err != nil {
		return Transport{}, err
	}
	return Transport{raw: raw}, nil
}
