// Code generated by generate-models. DO NOT EDIT.

package models

// UnloadTopicRequest Request to unload a topic from the broker.  Source: references/legacy/ovd/modules/pulsar/models/p...
type UnloadTopicRequest struct {
	Persistent bool   `json:"persistent"` // Whether the topic is persistent
	TopicName  string `json:"topicName"`  // Topic name to unload
}
