// Code generated by generate-models. DO NOT EDIT.

package models

// Upgrade
type Upgrade struct {
	TargetVersion KubeMinorVersion `json:"targetVersion"`
}

// isRedeployPayload implements RedeployPayload
func (r Upgrade) isRedeployPayload() {}
