// Code generated by generate-models. DO NOT EDIT.

package models

// VersionsConfig
type VersionsConfig struct {
	Available []string `json:"available,omitempty"`
	Default   string   `json:"default"`
}
