// Code generated by generate-models. DO NOT EDIT.

package models

// VersionsView Cluster console view — returned by GET /resources/versions.  Source: references/legacy/addon-api/...
type VersionsView struct {
	Clusters          []RedisClusterConsole `json:"clusters"`
	DedicatedVersions []string              `json:"dedicatedVersions"`
}
