// Code generated by generate-models. DO NOT EDIT.

package models

// Version A Kubernetes version, serialized as a plain `MAJOR.MINOR[.PATCH]` string.  Source: references/leg...
type Version = string
