// Code generated by generate-models. DO NOT EDIT.

package models

// VirtualMachineDeploymentSpec Source: ovd VirtualMachineDeploymentSpec.scala
type VirtualMachineDeploymentSpec struct {
	Constraints  any           `json:"constraints"`
	Image        string        `json:"image"`
	Instructions any           `json:"instructions"`
	Kernel       VmKernel      `json:"kernel"`
	Labels       HashMap       `json:"labels"`
	Name         string        `json:"name"`
	ResourceID   *string       `json:"resourceId,omitempty"`
	Resources    ResourcesSpec `json:"resources"`
	Tags         Vec           `json:"tags"`
	Uid          string        `json:"uid"`
}
