// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeDeploymentProfile The create / update request body — the same triple, un-redacted.  Source: ovd models/DeploymentPr...
type WannabeDeploymentProfile struct {
	LocationID  string `json:"locationId"`
	ProfileData any    `json:"profileData"`
	RegionID    string `json:"regionId"`
}
