// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeAddonProvision Request body for POST /v2/self/addons and POST /v2/organisations/{id}/addons.  Source: cc-api Wan...
type WannabeAddonProvision struct {
	Name       string          `json:"name"`              // Addon display name.
	Options    *map[string]any `json:"options,omitempty"` // Provider-specific options (null treated as empty map for Terraform compat).
	Plan       string          `json:"plan"`              // Plan ID (plan slug resolved by looking up the plan).
	ProviderID string          `json:"providerId"`        // Provider ID (e.g., "postgresql-addon").
	Region     string          `json:"region"`            // Region/zone name (e.g., "par").
}
