// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeContainerRegistry Request to create a new container registry with optional initial tokens.  Source: references/lega...
type WannabeContainerRegistry struct {
	Tokens []WannabeContainerRegistryToken `json:"tokens,omitempty"` // Optional initial tokens to create with the registry
}
