// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeGateway
type WannabeGateway struct {
	Endpoint string `json:"endpoint"` // Absolute URL
	Location string `json:"location"`
	Token    string `json:"token"`
}
