// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeCephXUser Request body for creating a Ceph X user.  Source: references/legacy/ovd/modules/storage/controlle...
type WannabeCephXUser struct {
	Caps     any    `json:"caps"`     // Capabilities to grant.
	EntityID string `json:"entityId"` // Entity ID for the new Ceph auth user.
}
