// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeValue Request body for PUT /env/{name} — just `{"value": "..."}`.  Source: cc-api WannabeValue.java (co...
type WannabeValue struct {
	Value string `json:"value"`
}
