// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeSigningKey Body of a signing-key create. `locationId` is optional and defaults to `"default"` at the core.
type WannabeSigningKey struct {
	LocationID *string `json:"locationId,omitempty"`
}
