// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeProduct
type WannabeProduct struct {
	Description string             `json:"description"`
	Limitations Limitations        `json:"limitations"`
	LogoURL     string             `json:"logoUrl"` // URL
	Maturity    MaturityKind       `json:"maturity"`
	Name        StringMaxLength128 `json:"name"`
	ProviderURL string             `json:"providerUrl"` // URL
	Tags        []string           `json:"tags,omitempty"`
	Version     string             `json:"version"`
}
