// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeUser Request body for PUT /v2/self — update user profile. Only non-null fields are applied (partial up...
type WannabeUser struct {
	Address *string `json:"address,omitempty"`
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
	Lang    *string `json:"lang,omitempty"`
	Name    *string `json:"name,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Zipcode *string `json:"zipcode,omitempty"`
}
