// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeBuildFlavor Request body for PUT /applications/{id}/buildflavor.  Source: cc-api SelfApplicationsAPI.java put...
type WannabeBuildFlavor struct {
	FlavorName *string `json:"flavorName,omitempty"`
}
