// Code generated by generate-models. DO NOT EDIT.

package models

// WannabeApplication Request body for POST /applications — create application.  Source: cc-api input/WannabeApplicatio...
type WannabeApplication struct {
	ApplianceID            *string       `json:"applianceId,omitempty"` // Source: cc-api openapi/ccapiv3.json WannabeApplication.applianceId Used by Terraform provider for...
	Archived               *bool         `json:"archived,omitempty"`
	Branch                 *string       `json:"branch,omitempty"`
	BuildFlavor            *string       `json:"buildFlavor,omitempty"`
	CancelOnPush           *bool         `json:"cancelOnPush,omitempty"`
	Deploy                 *string       `json:"deploy,omitempty"`
	Description            *string       `json:"description,omitempty"`
	Env                    *any          `json:"env,omitempty"` // Source: cc-api openapi/ccapiv3.json — environment variables for the application.  A `serde_json::...
	Favourite              *bool         `json:"favourite,omitempty"`
	ForceHTTPS             *string       `json:"forceHttps,omitempty"`
	Homogeneous            *bool         `json:"homogeneous,omitempty"`
	InstanceLifetime       *string       `json:"instanceLifetime,omitempty"` // Source: cc-api WannabeApplication.instanceLifetime — enum REGULAR, MIGRATION, TASK
	InstanceType           *string       `json:"instanceType,omitempty"`
	InstanceVariant        *string       `json:"instanceVariant,omitempty"`
	InstanceVersion        *string       `json:"instanceVersion,omitempty"`
	MaxFlavor              *string       `json:"maxFlavor,omitempty"`
	MaxInstances           *any          `json:"maxInstances,omitempty"`
	MinFlavor              *string       `json:"minFlavor,omitempty"`
	MinInstances           *any          `json:"minInstances,omitempty"`
	Name                   *string       `json:"name,omitempty"` // Application name. Required for POST (create), optional for PUT (update). Console3 sends PUT witho...
	OauthApp               *any          `json:"oauthApp,omitempty"`
	OauthAppID             *string       `json:"oauthAppId,omitempty"`             // Source: cc-api openapi/ccapiv3.json WannabeApplication schema
	OauthService           *string       `json:"oauthService,omitempty"`           // Source: cc-api Application.java absorb() — creates ApplicationOauthData
	PublicGitRepositoryURL *string       `json:"publicGitRepositoryUrl,omitempty"` // Source: cc-api Application.java absorb() — sets publicGitUrl from this field
	SeparateBuild          *bool         `json:"separateBuild,omitempty"`
	Shutdownable           *bool         `json:"shutdownable,omitempty"`
	StickySessions         *bool         `json:"stickySessions,omitempty"`
	Tags                   []SemanticTag `json:"tags,omitempty"`
	Zone                   *string       `json:"zone,omitempty"`
}
