// Code generated by generate-models. DO NOT EDIT.

package models

// WebhookView Webhook notification configuration.  Source: notification-api WebhookView Store: MongoDB `hooks` ...
type WebhookView struct {
	Events  []string     `json:"events"` // Event types: ["META_DEPLOYMENT_RESULT"] or ["ALL"].
	ID      string       `json:"id"`
	Name    string       `json:"name"`
	OwnerID string       `json:"ownerId"`
	Scope   []string     `json:"scope"` // Scope: list of resource IDs (app_xxx, addon_yyy) or empty for org-wide.
	Urls    []WebhookUrl `json:"urls"`
}
