// Code generated by generate-services. DO NOT EDIT.

package monitoring

import (
	"fmt"
	"net/url"
	"strings"
)

// Option defines a functional option for monitoring operations
type Option func(*Options)

// Options holds query parameters for monitoring operations
type Options struct {
	Cursor        *string   `url:"cursor,omitempty"`
	Drivereventid *string   `url:"driverEventId,omitempty"`
	Kind          *[]string `url:"kind,omitempty"`
	Limit         *int64    `url:"limit,omitempty"`
	Resourceid    *string   `url:"resourceId,omitempty"`
	Since         *string   `url:"since,omitempty"`
	Source        *string   `url:"source,omitempty"`
	Until         *string   `url:"until,omitempty"`
}

// WithCursor sets the cursor query parameter
func WithCursor(cursor string) Option {
	return func(o *Options) {
		o.Cursor = &cursor
	}
}

// WithDrivereventid sets the driverEventId query parameter
func WithDrivereventid(driverEventId string) Option {
	return func(o *Options) {
		o.Drivereventid = &driverEventId
	}
}

// WithKind sets the kind query parameter
func WithKind(kind []string) Option {
	return func(o *Options) {
		o.Kind = &kind
	}
}

// WithLimit sets the limit query parameter
func WithLimit(limit int64) Option {
	return func(o *Options) {
		o.Limit = &limit
	}
}

// WithResourceid sets the resourceId query parameter
func WithResourceid(resourceId string) Option {
	return func(o *Options) {
		o.Resourceid = &resourceId
	}
}

// WithSince sets the since query parameter
func WithSince(since string) Option {
	return func(o *Options) {
		o.Since = &since
	}
}

// WithSource sets the source query parameter
func WithSource(source string) Option {
	return func(o *Options) {
		o.Source = &source
	}
}

// WithUntil sets the until query parameter
func WithUntil(until string) Option {
	return func(o *Options) {
		o.Until = &until
	}
}

// buildQueryString builds a query string from options
func buildQueryString(opts ...Option) string {
	options := &Options{}
	for _, opt := range opts {
		opt(options)
	}

	var params []string
	if options.Cursor != nil {
		params = append(params, fmt.Sprintf("cursor=%s", url.QueryEscape(*options.Cursor)))
	}
	if options.Drivereventid != nil {
		params = append(params, fmt.Sprintf("driverEventId=%s", url.QueryEscape(*options.Drivereventid)))
	}
	if options.Kind != nil {
		params = append(params, fmt.Sprintf("kind=%v", *options.Kind))
	}
	if options.Limit != nil {
		params = append(params, fmt.Sprintf("limit=%d", *options.Limit))
	}
	if options.Resourceid != nil {
		params = append(params, fmt.Sprintf("resourceId=%s", url.QueryEscape(*options.Resourceid)))
	}
	if options.Since != nil {
		params = append(params, fmt.Sprintf("since=%s", url.QueryEscape(*options.Since)))
	}
	if options.Source != nil {
		params = append(params, fmt.Sprintf("source=%s", url.QueryEscape(*options.Source)))
	}
	if options.Until != nil {
		params = append(params, fmt.Sprintf("until=%s", url.QueryEscape(*options.Until)))
	}

	if len(params) == 0 {
		return ""
	}
	return strings.Join(params, "&")
}
